### ISSUE TITLE
Streams/videos not playing on a JU6000

### ISSUE THREAD

**Issue by cremvursti** [fgl27/smarttv-twitch#10]
Videos can't be played, with or without the auth token added. Whenever I select a video/stream it opens it up but then it just won't load it. Having the same issue with nikitakatchik's fork,

Running on a JU6000, Tizen 2.3 firmware 1530

**Comment by Kurtzisa** [comment]
I have the same problem here on a ju6500 TV. I cam see the preview but not the streaming

**Comment by fgl27** [comment]
@cremvursti I explain in the readme https://github.com/fgl27/smarttv-twitch#smarttv-twitch

> Full support for all 2015 TV is not possible as the TV firmware doesn't supports it, Samsung doesn't seems to care and may have remove the featuring intentionally (as the featuring simply stop working), a discussion about it was done in a issue from a repository that is no longer available, the final answer from Samsung can be read here [Samsung final answer about 2015 TV](https://fgl27.github.io/smarttv-twitch/screenshot/etc/samsung_final.png) it summarize what happened from they side. 

The support is not there anymore they remove it. If the TV doesn't receives Tizen 2.4 update noting can be done

**Comment by fgl27** [comment]
@Kurtzisa  "I found the problem! Select a video or a stream, press the ok button twice and it works!"
that is the process to reset the video in case it freezes, but the process of open a video is the same so if the above works the normal process also must.

In that case I need a log to see what is going on that need that workaround to be able to play

how to share a log here https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**Comment by fgl27** [comment]
@cremvursti are you satisfy with the explanation?

@Kurtzisa Are you going to log the issue? or is resolved?

**Comment by alexgosu** [comment]
@fgl27 I have the same problem on UJ6200
Stream hangs just before start, only loading icon.

Logs:
[tizen-logs.txt](https://github.com/fgl27/smarttv-twitch/files/3123698/tizen-logs.txt)

**Comment by alexgosu** [comment]
I've added 1 line just before error:

console.log('Play_onPlayer state is ' + Play_avplay.getState());    ///<<<<<<<
        Play_avplay.stop();
        Play_avplay.open(Play_playingUrl);

It says:

> **Play_onPlayer state is READY Play.js:644**
> Play_onPlayer open PLAYER_ERROR_INVALID_STATE:  Play.js:648
> PLAYER_ERROR_INVALID_STATE:  Play.js:665
> Play_onPlayer Play.js:665
> Play_qualityChanged Play.js:588
> Play_loadDataSuccess Play.js:522
> onreadystatechange

Hope it will help to fix issue.

**Comment by cremvursti** [comment]
Unfortunately I can't try what @alexgosu suggested since I get [this ](https://imgur.com/a/t3fniB3) error when I try to run the master version with the "debug as" option.

I managed to get the [standard](https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V2/4.0.1_V2.zip) version to play the streams by following the advice @Kurtzisa provided above, but instead of double tapping "OK" I have to double tap "Play" on my remote. At that point it says that the stream has ended and takes me back to the main menu, but after that every stream I load up seems to be working fine.

**Comment by alexgosu** [comment]
@cremvursti I had the same error sometimes. 
You can enter "Apps" menu on TV (using remote control) and remove Twitch App manually.
So Tizen IDE wouldn't have to "Uninstall package" and installation continue without errors.

**Comment by cremvursti** [comment]
@alexgosu Yeah, checked for that as well, unfortunately it happens even when i don't have the Twitch app already installed :( not quite sure what exactly it tries to uninstall.

**Comment by fgl27** [comment]
@alexgosu nice find, I hope this works for everyone .

That **close** option is no where recommended to be used, not even samsung uses on they player sample that they say is the one that must be used as base for any player as work on any TV.

the documentation is odd
https://developer.samsung.com/tv/develop/api-references/samsung-product-api-references/avplay-api

> close
> Destroys the player object.
> void close();

So I never used as I don't wanna have to be reloading the object all the time, but I tested here and as you wrote you can **close** and all works fine if works here and there must work for all if not we check when someone report a problem.

:+1:

**Comment by fgl27** [comment]
@alexgosu have you try to power off by removing from the wall, I have that issue some times and that resolves. is also recommended that you uninstall all apps named twitch on that occasion.

But as I already update the release you can just open it check if version in about shows as **042719** and it must play OK if not close the app so it can update. If it doesn't work after the version change let me know.

**Comment by cremvursti** [comment]
Well, I figured out how to run the app in debug mode: after selecting **Debug as**, instead of selecting Tizen Web App I selected "Debug Configurations" and in the **Common** under **Display in favourites Menu** tab I only selected **Debug** and then once again hit **Debug** in the lower right corner of the window.

Weird thing is after I've run the master build (both in normal and debug mode) I no longer need to double press "Play" in order for the video to load up. I even tried with 4.0.1_v2 and it's the same with that version.

**Comment by fgl27** [comment]
To check the app version you open side panel and select about, if there says **042719** that is the update version with the finds of @alexgosu to fi the issue so no need to others workaround. The version 4.0.1_v2 is just the zip name the real name is in the about.

Are you running that version? the update **042719**?

If yes that is way works.

**Comment by MaxBreida** [comment]
I have the exact same problem as the others above, can't get a single stream to work. The double tap solution doesn't work for me as well. I installed the debug version and tried to open a stream until i hit the timeout.

```
index.html:1

 Failed to decode downloaded font: https://fgl27.github.io/smarttv-twitch/release/githubio/css/fonts/BabelStoneHan.woff
index.html:1 OTS parsing error: OS/2: failed to parse table
Main.js:203 language is en_GB
Screens.js:6 InitScreens place holder
VM241:1 Entering setDisplayRect
VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:1425 [productinfo.js] getFirmware  begin
webapis.min.js:1431 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1435 [productinfo.js] getFirmware message data T-KTMDEUC-1262.0
webapis.min.js:1425 [productinfo.js] getModel  begin
webapis.min.js:1431 [productinfo.js] getModel  end [object Object]
webapis.min.js:1435 [productinfo.js] getModel message data UMU6100
Main.js:738 Tizen Version: 3.0 | TV: UMU6100 | FW: T-KTMDEUC-1262.0
webapis.min.js:3684 [network.js] addNetworkStateChangeListener  success
webapis.min.js:3689 [network.js] listenerId 0
SmartHub.js:40 Cannot read property 'setPreviewData' of undefined
webapis.min.js:47 [webapi.js] cbArr length: 1, then remove Callback!
Play.js:490 0
Play.js:491 
Play.js:490 0
Play.js:491 
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrsD6zSYpZ2wvD8h-hhkie…ocuwvqLEoH34pF4Fu5vLEaO8vQSEOsmCYQ9OeiNKNJqEZ1dlZQaDB16uI-mXaQyzYLajA.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrsD6zSYpZ2wvD8h-hhkie…ocuwvqLEoH34pF4Fu5vLEaO8vQSEOsmCYQ9OeiNKNJqEZ1dlZQaDB16uI-mXaQyzYLajA.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrsD6zSYpZ2wvD8h-hhkie…ocuwvqLEoH34pF4Fu5vLEaO8vQSEOsmCYQ9OeiNKNJqEZ1dlZQaDB16uI-mXaQyzYLajA.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDjZ3xQOoPleako-MNwJ…hbkuigJFbiD2QoJx--i7bETsNNEhDOvwPQ8fCSK3sOxnRsR8gQGgwPhoAAvggIFDHA-ZE.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDjZ3xQOoPleako-MNwJ…hbkuigJFbiD2QoJx--i7bETsNNEhDOvwPQ8fCSK3sOxnRsR8gQGgwPhoAAvggIFDHA-ZE.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDkkl2SuNwORTSLbi7-1…Iqn4bd2mrViMtUR5B8CI4o8ZmgEhCguIDOcGsYD4X91_sAgR94GgzFwixIEb4M_wnv9F4.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDkkl2SuNwORTSLbi7-1…Iqn4bd2mrViMtUR5B8CI4o8ZmgEhCguIDOcGsYD4X91_sAgR94GgzFwixIEb4M_wnv9F4.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDVE1D5eaNQP6Ln9aF_c…XIITtwBXWdjZXPRrxRhA1gOAJ2EhAU-Vr_ug1XIntvQrHj-reeGgwFinb-rNeML_9nnc0.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDVE1D5eaNQP6Ln9aF_c…XIITtwBXWdjZXPRrxRhA1gOAJ2EhAU-Vr_ug1XIntvQrHj-reeGgwFinb-rNeML_9nnc0.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDUfUrA33nh0wY6VYTpk…EJ-ymAn4o6_r7Sq-CG-BsOCWSGEhAykmcTHl7sGindcVrzQ9dhGgx-afwKzf6G9G7eH20.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDUfUrA33nh0wY6VYTpk…EJ-ymAn4o6_r7Sq-CG-BsOCWSGEhAykmcTHl7sGindcVrzQ9dhGgx-afwKzf6G9G7eH20.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDNhDGBiPbJuRJ3quYTd…Fgr2dTTM4A_f3_JyOmqWxih1HHEhDFiLnHAG7ILzhfl61fpAf2GgzNvRcfsQfbkJEzYRI.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
Play.js:643 Play_onPlayer: 

"https://video-weaver.fra02.hls.ttvnw.net/v1/playlist/CrkDNhDGBiPbJuRJ3quYTd…Fgr2dTTM4A_f3_JyOmqWxih1HHEhDFiLnHAG7ILzhfl61fpAf2GgzNvRcfsQfbkJEzYRI.m3u8"

VM241:1 adding listener
VM241:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:47 [webapi.js] cbArr length: 1, then remove Callback!
```

**Comment by fgl27** [comment]
@MaxBreida not the same issue open a separated issue please

**Comment by cremvursti** [comment]
@fgl27 hmm, yeah, I'm running **042719** though I could swear I used a .zip file I downloaded a few days ago.

**Comment by fgl27** [comment]
@cremvursti 4.0.1_v2.zip is a self update zip.

**Comment by alexgosu** [comment]
@fgl27 I can confirm that now it is working fine on my J6200.
Used previous "auto-updatable" archive 4.0.1_V2.zip.
Version is **042719**

Thank you very much!

**Comment by cremvursti** [comment]
@fgl27 I saw in another issue thread that you packed a separate .zip for the autodelete issue

**Comment by fgl27** [comment]
@cremvursti yes do you have the auto delete issue?
if yes please open a separated issue so I can track that separated.
