### ISSUE TITLE
Navigation problem on Featured page

### ISSUE THREAD

**Issue by ClashHexmen** [fgl27/smarttv-twitch#102]
Hey. I think I've encountered an error when browsing the featured page. Once I go down to the fourth row of streams the left-button on the remote stops working. As far as I can tell this only happens on the featured page. Refreshing temporarily fixes the issue.

**Comment by fgl27** [comment]
check again all OK for me.

**Comment by ClashHexmen** [comment]
Yeah weird. I can't reproduce the error anymore. Yesterday it happened all the time. As soon as any stream in forth row was selected the left button stopped working. TV is a Q70R btw. Maybe it was related to a specific stream on the featured page or the number of streams? Probably not worth looking into if it can't be reproduced...

**Comment by fgl27** [comment]
Twitch was laging sporadiac... I put a new check, I expect no problem regarding this.
