### ISSUE TITLE
Unable to install- macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by Hassanwich** [fgl27/smarttv-twitch#103]
[**Describe](url) the bug**

After downloading the application (Tizen Studio 3.6) and opening the installer;

![Screen Shot 2020-03-13 at 1 46 49 AM](https://user-images.githubusercontent.com/62134441/76605051-0a2cc180-64cd-11ea-9922-614e3673040f.png)

installer” can’t be opened because Apple cannot check it for malicious software.

If is a installation issue screenshot any error or wherever related that is generated during the installation.

Thanks,
-Sam

**Comment by fgl27** [comment]
I'm not Samsung or have a mac so I can't help with that, try a Samsung help page search about it.

**Comment by fgl27** [comment]
close because of the lack of communication.
