### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by Supernoodles1990** [fgl27/smarttv-twitch#104]
Hello I'm having an issue that I believe is with the app but I'm not 100% sure

So basically I watch a stream and randomly the audio just continuosly cuts out and returns over and over for different periods of time

Also while it is happening if I exit out of a stream and try to re enter the stream it just doesn't load it's just stuck on a still image or will only play at lowest quality like 160p.

I have factory reset my TV and tried all different combinations of sound settings and it only happens with this app

The only thing that fixes it and doesn't even fix it for long at times is holding the power button on the TV control to soft reset the TV.

I have a UE50MU6120 running the latest 1280 firmware.

**Comment by fgl27** [comment]
This is not something I can reproduce on my side, I don't have that TV or anyone has ever had a similar issue.

Did the app ever worked well on that TV? it happens to any streams? or only to a very particularly one? with stream?

For me yours TV has a problem, and I don't have a real idea of what causes it... 

For the audio to cut without any image problem assuming that is the case by what you tell me, is very odd and seems a bug on the TV side causing a lag, the same lag prevents the player from playing anything above 160p as you say, so the device losses performance capability and can't play higher resolution content.

I don't really know what can cause that on a particularly TV and not on others, the app works in the same on all TVs, so there is maybe a very specific thing you do that causes it, if the issue isn't a TV issue, so we need to find what it there is one.

**Comment by Supernoodles1990** [comment]
Yeah it's a really odd one it used to be fine but for about the last two to three weeks it's been happening.

It's really random for example it did it today but after doing the soft reset it's been fine all day today.

I doubt it is something you'll be able to fix maybe it will just randomly stop doing it for me eventually it's not a huge issue to fix just soft resetting

**Comment by fgl27** [comment]
let it open please, unless you sure it is 100% fixed.

**Comment by Supernoodles1990** [comment]
So things I have tried.

WiFi and Ethernet = not fixed
TV speakers only = not fixed
Soundbar only = not fixed
Low latency = not fixed
Standard latency = not fixed
Stream start buffer tried 1-10 = not fixed

Sometimes switching between qualities will fix it but after a few mins it starts cutting out again.

Testing on Monstercat Channel
160p = no cut outs
360p = no cut outs
480p = no cut outs
720p = no cut outs
1080p Source 4.83Mbps = sound cuts out

Testing on ChillhopMusic
160p = no cut outs
360p = no cut outs
480p = no cut outs
720p = no cut outs
1080p source 3.09Mbps = no cut outs

Testing on uhSnow
160p = no cut outs
360p = no cut outs
480p = no cut outs
720p = no cut outs
720p60 = cut outs (but less frequent)
Source 900p60 6.93Mbps = cut outs

So I believe it is either source related or bitrate related I'm totally lost on how it is fine after a soft restart.

Also sometimes when switching between qualities the stream just doesn't load and I have to spam the resolution change button.

And sometimes streams open and it's just a still image and I have to either close out of the stream and go back in or click on resolution button a few times like above.

**Comment by Supernoodles1990** [comment]
yes i literally turn on my tv connect the soundbar then open the app and start a stream.

Interestingly i had about two days in a row with no issue and then it started again yesterday.

**Comment by fgl27** [comment]
I don't know what can be I check and there is noting on the app that can cause a issue like that so must be something odd on the OS side, you can try to debug the issue to see if something shows up on the logs when the issue starts.

The only problem is that in order to see the log you need to be connected from a PC to the TV 100% of the time until the issue start, so if you can try that do.

Use the bellow zip and create a new project use the bellow the same way you use the release.zip to install the app.

[app_debug.zip](https://github.com/fgl27/smarttv-twitch/files/4446496/app_debug.zip)

After all imported OK install the app like this

![image](https://user-images.githubusercontent.com/13755892/78708031-da17e900-78e7-11ea-8715-f0e587ca447e.png)

After the installation finished you need to press OK on the TV remote, and a browser window will open on the PC

![image](https://user-images.githubusercontent.com/13755892/78708106-f74cb780-78e7-11ea-9276-0e6f526d61a8.png)

On that select `console` as in the SS above, then use the app the way you do and wait until the issue start and check if anything newis sowing on the logs...

If there is something copy the text and share it.

That zip I share will install a new app with a different icon so you know with is the test app.

**Comment by Supernoodles1990** [comment]
Hello I have this a try today but ok doesn't show up on the TV it just stays with a white screen and the debug box stays empty

**Comment by fgl27** [comment]
The app works?
When you play a stream don't logs show up?
some time the debug start lates buut the time you can play a stream it is enable, and on open a stream a lot of logs show, normal logs not error one...

can you see this in about

![Frame001_w1920h1080 (1)](https://user-images.githubusercontent.com/13755892/79011378-48ec8080-7b3a-11ea-9b29-7b9dabb4b4a0.png)

the red text indicating the test app was installed and not something else you have there/

**Comment by Supernoodles1990** [comment]
I don't even get that far the TV just sits on a white screen

**Comment by fgl27** [comment]
then you install the app wrong

you need to import the content of the app folder inside the **app_debug** folder...

simplifying import as a file system the folder that has files. make a new project and start over.

**Comment by Supernoodles1990** [comment]
I installed it the same way I installed the normal app the only thing I did differently was running it as a debug

**Comment by fgl27** [comment]
I don't thing so if you did you must see the about screen as my screen shot. try again

**Comment by Supernoodles1990** [comment]
I will give it another go tomorrow when I get time and get back to you

**Comment by Supernoodles1990** [comment]
well turns out i was actually doing it wrong lol instead of selecting the "app" folder i was selecting "app_debug" to import lol my bad i will test it for the day now and see what results i get

**Comment by Supernoodles1990** [comment]
So the issue i have where i switch from one stream to another and it shows the previous streams chat and the new stream doesn't play until i "refresh" using the quality option here is the log when that happens

Black = Watching Twitch.tv/Vader
Red = Watching Twitch.tv/Lirik

https://i.imgur.com/6C2PWWw.png

Also i made a video to show you what happens on the TV

https://www.youtube.com/watch?v=r-IcR-PgPr8

With reguards to the sound issue sadly the log didn't show anything happening when the sound started to cut out so i guess its an issue with my TV and not the app :(

**Comment by fgl27** [comment]
those logs are normal debug logs, problematic logs show in red text.

all the issue you have is yours TV issue, as I can't replicate anything here.

Did the audio problem has happen and not logs was there in red? 

I mean in red text or different text other then the normal ones that show when a stream start and or changes.

**Comment by Supernoodles1990** [comment]
No nothing changed in the log when the audio started cutting out that is why i think it must be an issue with my tv or something

**Comment by fgl27** [comment]
OK... if some day it stop let me know.

Let this open as may ocurrer to others.

**Comment by Supernoodles1990** [comment]
okay thank you

And the issue in my video? that is my tv aswell or ?

**Comment by Supernoodles1990** [comment]
![Capture](https://user-images.githubusercontent.com/28876700/79054019-9e5b8700-7c39-11ea-9cc8-42e9e02bf0cf.PNG)

the only difference i can see here is in red the stream tries to load but fails and the chat stays the same as the previous stream it says onbufferingprogress >98

Where as when it finally loads after hitting the quality button again that line isn't there as seen in black when it plays

**Comment by fgl27** [comment]
I introduce those logs myself that behavior is expected

https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Play.js#L924
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Play.js#L938

That is just a logic added to hide the buffer dialog or it hides on `onbufferingcomplete` or on `onbufferingprogress`

Som time the buffer ends `onbufferingcomplete` without ever passing a 98 or higher to `onbufferingprogress`, sometimes it doesn't call `onbufferingcomplete` but the buffer goes above 98 then on both case the buffer dialog need to be hidden.

There noting related with the issue you have, is just the logic I have created to address the buffer showing or not, I add those logs to be able to see the process of loading a stream in case it stops or takes too long somewhere I can easy analise that code is there for a long time.

**Comment by Supernoodles1990** [comment]
Strangely I haven't had the issue for about a week not sure whats different as I see you've made no changes your end and nothing has changed my end either

**Comment by fgl27** [comment]
Samsung can technical update they internal API that the app uses from they server as they are just simple javascript files, without making a FW update.

Maybe is that, or is just random.

**Comment by hallelujah** [comment]
Hello I have the same issue as OP.
Dunno what to add else just I have this TV Samsung QLED 4K 2020 65Q95T

**Comment by fgl27** [comment]
Not something I can fix, as I can't even reproduce

**Comment by fgl27** [comment]
inform to reopen if any news
