### ISSUE TITLE
Black screen after latest update pushed

### ISSUE THREAD

**Issue by bill4L** [fgl27/smarttv-twitch#107]
Presumably after a pushed update to the release from a few hours ago, I'm presented with a black screen with no controls when starting the app.

Rebooting the TV produces no change in behaviour.

TV is a UA32M5500 running the latest 1280 OS build.

**Comment by fgl27** [comment]
When I push a update to release doesn't change noting on a already installed app.

All fine here no one else has a issue, reinstall the app if after that you have a problem inform.

**Comment by fgl27** [comment]
Close do to inactivity.
