### ISSUE TITLE
Aplicativo travado após queda de conexão

### ISSUE THREAD

**Issue by gabrieluly** [fgl27/smarttv-twitch#108]
Estava assistindo normalmente até minha internet cair e ficar tentando carregar, coloquei para sair da transmissão, retornando para a página anterior (era a página do canal, aquela que mostra a transmissão online/offline e em cima as opções clips/videos). 

Reiniciei meu modem e quando a internet voltou coloquei para atualizar, nesse momento o meio da tela ficou preto e o aplicativo não responde mais. Já tentei forçar fechar (segurando o botão de retorno) e deixar a televisão fora da tomada por alguns minutos mas sempre que reabro o aplicativo ele volta pra essa tela travada da imagem. O relógio no canto superior direito continua atualizando mas nenhuma tecla pressionada muda a tela.

Tela: https://imgur.com/a/R5Xcv5J

Existe alguma combinação de teclas que resete o estado do aplicativo ou terei que reinstalar?

Obrigado pelo aplicativo, utilizo todos os dias.

**Comment by gabrieluly** [comment]
Tentei de tudo mas acabei reinstalando mesmo, obrigado.

**Comment by fgl27** [comment]
> Existe alguma combinação de teclas que resete o estado do aplicativo ou terei que reinstalar?

teoricamente uma boa idea porem se o app não responde ele não responder a teclas, quando tu segurar o botam de retorno não é arte do aplicativo e sim do sistema da TV.

Se algum dia eu conseguir reproduzir o problema eu evito ele de acontecer.

A minha recomendação seria reinstalar, pois a porcaria do sistema operacional não tem uma opção básica de limpar dados de aplicativo já instalado e também não tem como debugar um aplicativo instalado dificultando e muito o desenvolvimento nesta plataforma.
