### ISSUE TITLE
Feature request: Add USB/Bluetooth keyboard support for chat

### ISSUE THREAD

**Issue by jpalojarvi** [fgl27/smarttv-twitch#109]
Currently navigating the menus and streams works fine with a USB keyboard I'm using, but unfortunately the chat seems to be inaccessible. It would be very convenient to type into the chat on a keyboard, completely eliminating the need to use a mobile/PC version for chat while watching a stream on the TV. Perhaps there could be a dedicated key to open the chat window, like Enter?

Thanks for developing this great app!

**Comment by fgl27** [comment]
if you wanna to write to chat there is a  issue alredy
https://github.com/fgl27/smarttv-twitch/issues/90

if that is all close this as is duplicated.

**Comment by fgl27** [comment]
close because of the lack of communication.
