### ISSUE TITLE
Cannot connect the TV to Tizen Studio

### ISSUE THREAD

**Issue by goby89** [fgl27/smarttv-twitch#111]
Hello thank you for making this app first of all. I am trying for 2 days straight to connect to the tv without succes. I've tried from PC, VM Win 7, and another laptop with cable and wireless connection . I have installed JDK8, latest tizen plus packages from the links provided, Samsung TV UE40KU6092U in developer mode connected to the right host ip. I shall put up some screenshots , maybe  we can solve this, i don't have any more ideeas.
![IMG_20200427_235242](https://user-images.githubusercontent.com/3749507/80422551-08855480-88e7-11ea-86bc-dbc4cddea782.jpg)
![IMG_20200427_235344](https://user-images.githubusercontent.com/3749507/80422566-10dd8f80-88e7-11ea-856b-91eb38b1f173.jpg)
![IMG_20200427_235358](https://user-images.githubusercontent.com/3749507/80422581-18049d80-88e7-11ea-9d7e-b1feca9d5459.jpg)
![IMG_20200428_001913](https://user-images.githubusercontent.com/3749507/80422620-2ce13100-88e7-11ea-8569-e6dd0a28be51.jpg)
![IMG_20200428_001926](https://user-images.githubusercontent.com/3749507/80422669-43878800-88e7-11ea-94ae-ac00e17a1df3.jpg)
![IMG_20200428_001935](https://user-images.githubusercontent.com/3749507/80422732-5dc16600-88e7-11ea-9b38-31944da6250e.jpg)
![IMG_20200428_001945](https://user-images.githubusercontent.com/3749507/80422759-6e71dc00-88e7-11ea-8284-7419049d816e.jpg)

**Comment by fgl27** [comment]
here 
https://user-images.githubusercontent.com/3749507/80422566-10dd8f80-88e7-11ea-856b-91eb38b1f173.jpg

Must be the computer IP. Not the TV.

Here
https://user-images.githubusercontent.com/3749507/80422581-18049d80-88e7-11ea-9d7e-b1feca9d5459.jpg

The TV IP.

**Comment by fgl27** [comment]
check here

https://developer.samsung.com/smarttv/develop/getting-started/using-sdk/tv-device.html

**Comment by goby89** [comment]
So, i have changed the network IP settings in the TV to those on my PC, I have set host IP for developer to be the one from PC and rebooted, and in Tizen I am trying to connect to my PC IP. Something still wrong.

**Comment by fgl27** [comment]
Yes the wrong is that you don't seem to understand the tutorial, maybe you lost in translation maybe you didn't double check.

why on tizen you are trying to connect to yours PC IP?
you are on the PC trying to connect to the PC, I just posted before what is what...

Don't you see the problem, you don't need to add any IP on tizen just clean scan and the TV will be found, if not add the TV ip that you get from TV settings.

https://github.com/fgl27/smarttv-twitch#setting-up-the-build-environment

> On the device manager, click **Scan** and it will find your TV if it is set up is ok and on the same network. If it doesn't find it, try to add it manually by clicking on the  **+** option and add your TV IP address. Don't change the **Port**. To get the address, go to the main menu > network > Network status... wait a moment extra options will be loaded, click on **IP Settings** read your TV's IP Address

You can just read the tutorial is not needed me to read it for you and quote every single step you don't do correct.

**Comment by fgl27** [comment]
Close do to inactivity.
