### ISSUE TITLE
BTTV Emotes Stopped Working

### ISSUE THREAD

**Issue by dokbanks** [fgl27/smarttv-twitch#112]
The BetterTTV emotes seem to have stopped working in chat on the app. Is there a way of fixing this? Thanks in advance

**Comment by dokbanks** [comment]
Further note: The chat has now entirely stopped working.

**Comment by fgl27** [comment]
Can't reproduce all fine for me.

**Comment by dokbanks** [comment]
Can confirm all is fine now. I read news of certain people having twitch chat outages. Its strange as chat was fine on my PC and mobile devices, yet was not on my TV. Either way, all is working now. Thanks for the response.
