### ISSUE TITLE
Can it be used from USB stick?

### ISSUE THREAD

**Issue by cmorenoserrano** [fgl27/smarttv-twitch#113]
The original app from Nikita and the other one from BrunoN could both work by directly copying the github project into a USB stick and plugging it to the tv (mine is H series from 2013). When I try to do this with your much better project, the app does not appear in the Smart Apps when popping in the USB stick to the tv like with the other projects.

Do you know why is this? Is there a way to make it work?
I don't mind popping the USB stick in the TV whenever I want to watch Twitch.
The other ways of getting the app in the TV using the Apache web browser are far too complicated. The USB stick way is super easy and was working with the older Nikita and BrunoN versions until things changed (I believe it is Twitch not allowing http traffic any more, in favour of https traffic).

Many thanks!
Carlos

**Comment by fgl27** [comment]
> Can it be used from USB stick?

NO.
This project is not meat to work on older then 2015 devices.
I don't know how the USB process works or how to port this to older devices.

**Comment by fgl27** [comment]
Close do to inactivity.
