### ISSUE TITLE
Forever loading screen

### ISSUE THREAD

**Issue by weedminera** [fgl27/smarttv-twitch#114]
**Describe the bug**
When I select any live stream or video, I just get a forever loading screen. If I leave it for 2 mintues it just goes back to the list with streams and nothing happens.

**To Reproduce**
1. Go to any stream or video

**Expected behavior**
Stream or video should start playing

**Screenshots**
There's just a loading icon spinning.

**Operation system (if is a installation problem):**
 - OS: Windows 10 Education

**Device:**
 - TV Model: SAMSUNG 65Q85R
 - Os version Tizen 5.

**Additional context**
Initially, when I installed the app, I was able to watch videos, but after going to the quality option, which was currently at 1080p and pressed OK, I started getting this loading screen. Don't know if it's related.
I tried deleting and installing the app again. Same thing.

**Comment by fgl27** [comment]
The app is working fine for me but I for have that particularly device.

Check this maybe helps https://github.com/fgl27/smarttv-twitch/issues/15

**Comment by fgl27** [comment]
Close do to inactivity.
