### ISSUE TITLE
Channel Points

### ISSUE THREAD

**Issue by Altequer** [fgl27/smarttv-twitch#115]
it is possible to implement a way to earn points by watching the stream through this application. Watching through the browser we earn points where it is possible to gain benefits

**Comment by fgl27** [comment]
No, as if was it would be possible to anyone give anyone points that they don't deserve.

**Comment by Altequer** [comment]
When people watch a stream, they earn points from the channel, where they can exchange for emots and even sometimes the channel can have a store https://help.twitch.tv/s/article/channel-points-guide?language=en_US

**Comment by fgl27** [comment]
What do you wanna with that statement?
I know what it is. Don't you get my answer it was NO.
