### ISSUE TITLE
Chat side and position

### ISSUE THREAD

**Issue by eze92** [fgl27/smarttv-twitch#116]
The Option to change chat position and size doesn't seem to work like before

**Comment by fgl27** [comment]
What you wanna with this?

**Comment by eze92** [comment]
> What you wanna with this?

Sorry I had misspelled, I wanted to say that the option that the application has that allowed to change the position of the chat and the size of it, apparently would not be working. My smart tv is the mu6100

**Comment by fgl27** [comment]
You can't change position or size on smaller screen plus chatty (aka side by side mode)

That is it?

Because is working fine for me outside that mode.

**Comment by eze92** [comment]
> You can't change position or size on smaller screen plus chatt mode(aka side by side mode)
> 
> That is it?
> 
> Because is working fine for me outside that mode.

resize the screen if it works, but not the chat alone, before I remember that it was possible, I leave an image marking what it would be in case I am not implying myself well

![image](https://user-images.githubusercontent.com/8607217/84666790-e7f57600-aef7-11ea-98c3-9ebdedcfe361.png)

**Comment by fgl27** [comment]
You have video mode, small screen and chat enable, I just inform that on that mode you can't do what you wanna, don't you get it?

Change video mode and you will be able to move the chat

**Comment by eze92** [comment]
It is true, I tried and I had not realized that , you can close the thread sorry for the inconvenience

**Comment by fgl27** [comment]
OK don't worry is all good no inconvenience
