### ISSUE TITLE
Old Smart tv (2014) UE48H6670SL

### ISSUE THREAD

**Issue by Jappie3** [fgl27/smarttv-twitch#117]
I want to install this app on my smarttv, but since it is quite old the developer mode does not work the same as described in readme. I can log in with the username 'develop' and leave the password blank, then I can hold enter on the web browser to enter the IP of my computer (idk if this has the same effect as developer mode on newer tvs). But when I try to set up the build environment my computer can't connect to the TV. Is this because of the developer mode or are there workarounds I don't know about?

**Comment by fgl27** [comment]
On the readme we have this'd

`The application fully supports all 4k and 1080p Samsung TVs released in 2016 or later. The app also support TVs released in 2015 or earlier that have Tizen version 2.3 or newer, however for some old TV even running Tizen 2.3 may there be some minor FW issues that affect the app most of those have be fixed, so is expected that they all work if doesn't for you open a issue.`

If yours TV doesn't run tizen 2.3 or newer there is no support or I know how to support.

**Comment by fgl27** [comment]
Close do to inactivity.
