### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by AUCoronaVirus** [fgl27/smarttv-twitch#118]
![image](https://user-images.githubusercontent.com/67546671/85948340-bcf93080-b993-11ea-8b59-fe71ed4fa252.jpg)
![image](https://user-images.githubusercontent.com/67546671/85948347-c6829880-b993-11ea-9e80-6e3b375c6021.jpg)

Hey guys,

Followed instructions everything seem to work fine once getting to tv it’s loaded but stays on this white screen? 

Thanks 
Jason

**Comment by fgl27** [comment]
you have installed a empty app. you probably fail on the import part

start over from
https://github.com/fgl27/smarttv-twitch#setup-the-application

**Comment by AUCoronaVirus** [comment]
Thanks mate will give a go soon!

**Comment by AUCoronaVirus** [comment]
Update - works perfectly just added my twitch account all working great! You are a legend! Thank you very much!
