### ISSUE TITLE
Installed without issue, but only get black screen when I open app

### ISSUE THREAD

**Issue by PhilipOlivrHoles** [fgl27/smarttv-twitch#120]
I installed the app without any issues or error messages of any kind (thank you for the concise instructions) but once the app opens nothing loads I just get a black screen. I have tried the install process twice, restarting from scratch the 2nd time. Do you have any idea why this is happening or how I can resolve it?

**Device:**
 - TV Model: UN55KU6500
 - Software version: T-JZL6AKUC-1242.0. BT-S

**Comment by fgl27** [comment]
Fail to properly import redo this

https://github.com/fgl27/smarttv-twitch#setup-the-application

If no good show the result of the import... this:

![install_app9](https://fgl27.github.io/smarttv-twitch/screenshot/install/install_app9.png)

**Comment by PhilipOlivrHoles** [comment]
That worked. Thank you!
