### ISSUE TITLE
Stuck in a streamer's page.

### ISSUE THREAD

**Issue by Zatsando** [fgl27/smarttv-twitch#121]
I 'm having a weird issue that the app seems to work (upper right corner has updated clock/date) but I 'm stuck in a streamers page and no button is working. Is there anything I can do? Inform me if you need any kind of further info.

**Comment by Zatsando** [comment]
TV model : UE49NU7171
Software version: T-KTM2LDEUC-1294.0

**Comment by fgl27** [comment]
On the bug report I ask for steps to report the issue you share none as you probably didn't even read it. A issue that can't be reproduce can't be fixed, **do you get it?**

 "streamers page" is the bellow channel screen?

![Screenshot from 2020-07-29 14-47-34](https://user-images.githubusercontent.com/13755892/88834666-8db02c00-d1aa-11ea-9c05-5689b1fd4f1c.png)

if yes this was last time this issue has happens https://github.com/fgl27/smarttv-twitch/issues/108 no solution as a way to reproduce was never informed, the user install the app again to fix it.

Share everything that you did before causing the issue, that includes the channel name what you was watching from what screen you open the channel screen (from the player from the search from the user channels) etc etc.

**Comment by Zatsando** [comment]
I could identify the issue but its written in a language I dont understand. Anyhow this is the issue yes. Thnx a lot! 👍

**Comment by fgl27** [comment]
re install the app then...if you can't speck english or portuguese I can't help you.

**Comment by fgl27** [comment]
I have added a hidden reset function 

https://github.com/fgl27/smarttv-twitch/commit/84ef682ce70b0e546873f4b5ff3ef7421b990bea

**Force erase all app config: in case the app misbehave and stop working, hold key channel UP or Down for 20 seconds anywhere in the app, after it 10 seconds there is a confirmation**

When the app is "Stuck" it can be used to erase the app config and restore functionality, it will not erase user config just settings and related.
