### ISSUE TITLE
Cannot authorize user after installing lastest master

### ISSUE THREAD

**Issue by t3hz0rak** [fgl27/smarttv-twitch#123]
**Describe the bug**
I just pulled the latest master & installed it on my tv. When I go to authorize my user, it says "Fail authentication check with the provider key, please check and try again"

**To Reproduce**
Add user
Try to authorize user
Enter key from tiny.cc/twitchkeycode
Get error
Triple checked the code, refreshed to get 3 different keys, all failed.
I've authorized this 4 or 5 times before when I upgraded the app without issue, so I know I'm capable of copying the code correctly. Something's wrong

**Expected behavior**
-

**Screenshots**
-

**Operation system (if is a installation problem):**
OS: Windows
Version: Latest master. commit 844e5dec1d987ed00431dbf716e176988a49d757

**Device:**
 - TV Model: UN50MU6300
 - Tizen Studio v3.7

**Additional context**

**Comment by fgl27** [comment]
You installed the release or the master branch?

You supposed to use the release noting else a 14kb file.

In doubt read the about of the app it will tell if you install the wrong version, if the doubt remain screen shot the about and post here I'll explain.

**Comment by t3hz0rak** [comment]
Problem occurs in both latest (4 month old) release and master.

(Side note: it's strange to me that you don't expect  master to work. master should always be ready to release)

**Comment by fgl27** [comment]
I can only assume you don't understand the readme and aren't installing the correct release zip.

I make a release with is a very small zip, that when used will download the latest and correct JS code that will make everything work. if you install any other thing that will not work and isn't supported by me.

If you don't wanna use the correct zip just close the issue as that is not a issue is a user choice.

BTW the master branch works just fine after all that source is used to make the release and that is perfect working for me but the source will not work for what you wanna just the correct release will.

**Comment by fgl27** [comment]
Update my comment above and will close this as this issue makes no sense of be open as there is no issue.
