### ISSUE TITLE
how can I check the ping to the service servers?

### ISSUE THREAD

**Issue by RaTeNo** [fgl27/smarttv-twitch#124]
Hello, how can I check the ping to the service servers?

When the application is turned on, it takes a long time to load, and then a black screen, possibly due to the blocking of resources by the state

https://fgl27.github.io/smarttv-twitch/release/githubio/css/font-awesome.min.css

Timed out waiting for a response from fgl27.github.io.

**Comment by fgl27** [comment]
https://fgl27.github.io/smarttv-twitch/release/githubio/css/font-awesome.min.css is a 3kb file so even on a dial up connection of the last century it will download in a second.

Ping commands work like this:

`ping server`

example...

```
ping  fgl27.github.io
PING fgl27.github.io (185.199.110.153) 56(84) bytes of data.
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=1 ttl=50 time=14.7 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=2 ttl=50 time=14.6 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=3 ttl=50 time=14.6 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=4 ttl=50 time=14.6 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=5 ttl=50 time=14.8 ms

--- fgl27.github.io ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4007ms
rtt min/avg/max/mdev = 14.560/14.662/14.776/0.073 ms

```

**Comment by RaTeNo** [comment]
Thank you, the github.io service does not work completely in Belarus
