### ISSUE TITLE
Screen is black when running web application

### ISSUE THREAD

**Issue by annadayz** [fgl27/smarttv-twitch#127]
Hey,

Have used the app before and it's worked brilliantly but tonight it frozen up and stopped working. We decided it would be time to reinstall as we have been using it for over a year now.

I seem to be getting a black screen after I click to run the web application, it doesn't run at all. 

Thanks for your help

 - Tizen version 3.7 (have reinstalled and added all packages as per guide)

**Comment by fgl27** [comment]
install it on debug mode https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992
Show the result.

**Comment by annadayz** [comment]
Console is empty.

<img width="1177" alt="Screenshot 2020-08-27 at 08 24 40" src="https://user-images.githubusercontent.com/70298459/91410409-ce00d980-e83e-11ea-8db7-73953b23829c.png">

**Comment by fgl27** [comment]
That can be because of a internet issue or installation issue.

Open the bellow debug tab "Resources", there open just like bellow image, make sure to click on the `index.html` file and make sure `fonts` and `scripts` are open so the content of it folder can be see, before take a screen shot.

![Screenshot from 2020-08-27 15-16-35](https://user-images.githubusercontent.com/13755892/91479869-8008c780-e878-11ea-9d8c-52ebb6f670e7.png)

**Comment by annadayz** [comment]
Looks like i'm not seeing fonts at all, very. odd. However I do see one part under scripts. So you reckon this is an internet issue? Do you know of a guide that can help me amend this? 

<img width="1186" alt="Screenshot 2020-08-27 at 19 27 49" src="https://user-images.githubusercontent.com/70298459/91480942-91af9680-e89b-11ea-93b0-a8fb16646766.png">

**Comment by fgl27** [comment]
The `webapi.mim.js` is a file from the TV.

It seems you can reach `https://fgl27.github.io/` try to revise you local network, I don't know what you do there but something is blocking.

You can do a simple `ping` test as bellow to check if you have access, if you do have access on a computer (ping os OK) but not on the TV then the TV has local connection problem, but if you can't on the PC is something else as your provider or something you did to the network configuration (on a router or something like that), can also be a issue on yours internet provider. 

```
ping fgl27.github.io
PING fgl27.github.io (185.199.110.153) 56(84) bytes of data.
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=1 ttl=50 time=14.9 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=2 ttl=50 time=16.0 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=3 ttl=50 time=14.8 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=4 ttl=50 time=14.6 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=5 ttl=50 time=14.5 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=6 ttl=50 time=14.8 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=7 ttl=50 time=16.0 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=8 ttl=50 time=14.6 ms
64 bytes from 185.199.110.153 (185.199.110.153): icmp_seq=9 ttl=50 time=14.6 ms

--- fgl27.github.io ping statistics ---
9 packets transmitted, 9 received, 0% packet loss, time 8013ms
rtt min/avg/max/mdev = 14.526/14.984/16.046/0.561 ms
```

**Comment by annadayz** [comment]
Thanks Felipe!

I've tried restarting the installation again and it seems I received a logo error, which made me think I needed to change the logo. This is what was causing the console to show as empty, once I left the logo, it was fine.

I also port forwarded the https port (443) on my router settings and that seems to be working as well. 

All sorted now,  thanks again! Really great app, we've been using it for over a year and it's the best app!

**Comment by fgl27** [comment]
What is "logo" for you? What you did with it?

We may be a little lost in translation here, as I don't understand the use of that word.

So I can understand the solution and close this.

**Comment by annadayz** [comment]
So after creating a new project and following the import step, I would get to this point

<img width="359" alt="Screenshot 2020-08-28 at 08 40 36" src="https://user-images.githubusercontent.com/70298459/91534923-47193300-e90a-11ea-84c6-9d9f0ed6a617.png">
<img width="684" alt="Screenshot 2020-08-28 at 08 40 33" src="https://user-images.githubusercontent.com/70298459/91534933-4aacba00-e90a-11ea-8196-49fa71c7d850.png">

I thought as it is showing an error, and the icon name is incorrect, I needed to manually change it to the app_icon.png file. Turns out you can still run this even with the error showing and it sorts itself out.

**Comment by fgl27** [comment]
OK I get it now...

I never notice that, I usually just close the `config.xml` file, and import after that the tizen make all work....

Tizen installation is complicated... I will check to improve making the app icon the default used by tizen.

Thanks for the help. If need open a another.
