### ISSUE TITLE
September 2020 - Not working anymore

### ISSUE THREAD

**Issue by pedro-pinho** [fgl27/smarttv-twitch#128]
I've been using the app on my tv for some months now and I love it so much.
But yesterday it stopped working. It doesn't even open anymore.

I tried:
- Recompile the app
- Re-run from tizen studio,

**To Reproduce**
1. Open the app

**Expected behavior**
The app to work

It does look like Samsung took it down or something.
I'm a developer and I can help if needed. Please tell me, and I'll do it for free.

**Comment by fgl27** [comment]
Working fine for me. Must be a local problem on the TV or network...

Debug the app as explain here https://github.com/fgl27/smarttv-twitch/issues/127#issuecomment-681289984

If you can't find a solution debugging, share the `Console` and `Resources` screen as explain on that issue.

**Comment by pedro-pinho** [comment]
I restarted my router and launched it with debug move and it's working now!
I'm uploading the console image so if anyone has the same issue, they can compare.

![image](https://user-images.githubusercontent.com/32839552/92310818-39a61d80-ef88-11ea-96ff-1bef282944a7.png)

Thank you for this awesome app!
