### ISSUE TITLE
An internal error occurred during: "Launching Twitch2". org.tizen.web.editor.configuration.TizenConfiguratorImpl cannot be cast to org.tizen.web.editor.configuration.IMobileConfigurator

### ISSUE THREAD

**Issue by megalhaes** [fgl27/smarttv-twitch#13]
Hello, need some help please:

All the steps were done successfully. When I reached the final "Install the application" step I get the following error messag while trying to "Run as Tizen Web Application":

An internal error occurred during: "Launching Twitch2".
org.tizen.web.editor.configuration.TizenConfiguratorImpl cannot be cast to org.tizen.web.editor.configuration.IMobileConfigurator

Operation system (if is a installation problem):
Windows 10
Tizen Studio 3.2

**Comment by fgl27** [comment]
Did you install the extension sdk? that error is to missing TV extension 4.0 or 5.0 from the extension sdk tab and related files.

you need to check all of this
https://github.com/fgl27/smarttv-twitch#bellow-imgs-showing-the-installed-packages-the-one-with-a-delete-option-are-installed

my today are

![Screenshot from 2019-04-24 22-15-02](https://user-images.githubusercontent.com/13755892/56703366-d68f5000-66de-11e9-9e96-217e71c2d622.png)

![Screenshot from 2019-04-24 22-15-04](https://user-images.githubusercontent.com/13755892/56703368-da22d700-66de-11e9-8ca1-89dfcd6136c7.png)



and in main sdk I have

![Screenshot from 2019-04-24 22-15-20](https://user-images.githubusercontent.com/13755892/56703378-e7d85c80-66de-11e9-9669-7c7d302f4ae3.png)


![Screenshot from 2019-04-24 22-15-24](https://user-images.githubusercontent.com/13755892/56703380-ec9d1080-66de-11e9-94ba-2a2930b9de01.png)


check all of those and try again if it doesn't work uninstall Tizen studio and try again.

**Comment by fgl27** [comment]
With those everything install just fine here, and those packages are all available in Tizen studio 3.2 today.

**Comment by fgl27** [comment]
Is the issue resolved @megalhaes ?

**Comment by megalhaes** [comment]
Hi fgl27, 

Only had the chance to correct it today. Yes it was. I had TV extensions pre-installed and missed 5.0. Thank you for the explanation and what appears to be a great app.

**Comment by fgl27** [comment]
You welcome, if need open another issue.

**Comment by SWJ06** [comment]
Thanks for all your work. I overlooked extensions first time but this ticket helped me easily correct the situation. App looks great!
