### ISSUE TITLE
Block Ads

### ISSUE THREAD

**Issue by a-soll** [fgl27/smarttv-twitch#130]
Any possibility of blocking ads? I'm not sure if this is a new thing, as my Ublock on desktop has been inconsistent lately, but would be great if this could block pre and mid roll ads

**Comment by fgl27** [comment]
not possible.

**Comment by xianmiller** [comment]
Successfully logged in with my key,  But I'm getting pre-roll/mid-roll on subscribed channels.

**Comment by fgl27** [comment]
I post here
https://github.com/fgl27/SmartTwitchTV/issues/19

so I quote myself

> they are making ads part of the stream it self, that is it. the only know workaround is not show the ad, but that means a black screen until the add has ended with can be 15 to 60 seconds of noting, plus after something is show (the normal stream) there is a desincronizations because you didn't show the ad, the app freezes is very odd on some device the app can probably crash on that case, so is technically worst not to show the add and show a black screen.
> 
> the only way to inform you are a sub is by using the authorization key from the official app or website, the authorization key generate via third party apps can't be used to inform if you are a sub or a turbo or wherever that can prevent ads from showing , that is because if the app use it's third party authorization key the stream link will not be provided.
> 
> So only the official app or website can ṕrevent you from see ads when you really deserve that.
> 
> Use the website authorization key outside the website can get yours account banned, and if used on this app this app banned also, that includes my twitch account be banned too.
> 
> If they are crazy about ads like this, is possible that they do ban user and or me on that case.

**Comment by xian042** [comment]
Wow. Talk about ruining the user experience, thanks Amazon.

When I looked at the router logs and didnt see any new domains, I was afraid they were injecting the ads right into the stream instead of to another domain. 

Why are they restrictive of using the auth key outside the site? Is it just to drive people to use their app instead? Or is there a system/security issue from letting you use it?

Sorry for you my friend. I love your app, and all the work you've done.

**Comment by fgl27** [comment]
> Why are they restrictive of using the auth key outside the site? Is it just to drive people to use their app instead? Or is there a system/security issue from letting you use it?

they just disable it a year ago, they never documented that it could be used so they just one day prevent third party from use it, by not providing the stream link when using it, is believed so they can force you to use they official tools, mostly to prevent boots, but also for revenue ads and related.

**Comment by fgl27** [comment]
BTW DON'T POST ME TOO, AS WE ALREADY KNOW ABOUT THE ISSUE.

Only post something if is to add something new ask a question something like this, no span posts are needed.

**Comment by gitthrothro** [comment]
The smart tv app has more ads than the twitch app has and I do not have twitch turbo or sub to anyone.

If Ioad the twitch app on shield I can go to 10 streams i follow and one after another they load without any ads. If i go to smart tv app and go back and forth between streams i follow and guaranteed to get an ad every time.

So what is happening here that is making the smart tv app guaranteed to get ads but the twitch app isnt?

**Comment by fgl27** [comment]
> The smart tv app has more ads than the twitch app has and I do not have twitch turbo or sub to anyone.
> 
> If Ioad the twitch app on shield I can go to 10 streams i follow and one after another they load without any ads. If i go to smart tv app and go back and forth between streams i follow and guaranteed to get an ad every time.
> 
> So what is happening here that is making the smart tv app guaranteed to get ads but the twitch app isnt?

You are on the wrong place this is the samsung app not the android. android only here https://github.com/fgl27/SmartTwitchTV/issues/19

I don't know why I'm not twitch/amazon they are the one doing this. I personally didn't had adds today.

**Comment by gitthrothro** [comment]
Sorry about posting in the wrong section and I appreciate your click reply.

I guess im still wondering how the official app I can check a dozen streams with no preroll ad but the smart app has it guaranteed everytime? Shouldnt the amount of ads be equal regardless of what app im using if i dont have turbo or sub?

Are you sure there isnt something that may have been overlooked in the code that could fix some of this? I realize you cant completely overcome it but shouldnt it be the same?

**Comment by fgl27** [comment]
> Sorry about posting in the wrong section and I appreciate your quick reply.
> 
> I guess im still wondering how the official app I can check a dozen streams with no preroll ad but the smart app has it guaranteed everytime? Shouldnt the amount of ads be equal regardless of what app im using if i dont have turbo or sub?
> 
> Are you sure there isnt something that may have been overlooked in the code that could fix some of this? I realize you cant completely overcome it but shouldnt it be the same?

just look at this clip https://www.twitch.tv/garug/clip/BenevolentYawningHeronKippa
and the reason is all about the $$$$$$$$$$$ see https://www.twitch.tv/itshafu/clip/ChillyAbstemiousCarrotSSSsss

ads are all over not my fault do you get it?

answering 1000000 questions will not help on solving it is just a wast of my time answering them.

**Comment by gitthrothro** [comment]
I think you might be misunderstanding what i am asking. If no sub or turbo on twitch app i get less adds. On smart tv app guaranteed ads every timi switch or reload a channel

So what is causing smart app to have more ads?

**Comment by fgl27** [comment]
ads have stopped, maybe only in my region over 24h noting.

If you have let me know... how often and what region?

**Comment by fgl27** [comment]
As no one is informing a ting about ads, I can only assume no one is getting ads so close this
