### ISSUE TITLE
Separate @ Mentions from Chat Scroll

### ISSUE THREAD

**Issue by xianmiller** [fgl27/smarttv-twitch#131]
Move or Copy @ mentions to separate column that persists as a separate scroll from normal chat. Similar to how BTTV works to pin messages to the top of the scroll, this would be helpful to improve the user experience in larger channels

While the current implementation of highlighting @ mentions is good for slow chat, in higher velocity chat lobbies, @ mentions are not visible long enough to parse, or reply.

**Comment by fgl27** [comment]
Are you using this project?

this is only for Samsung TV, and here I didn't had time to add a highlighting mention sistem.

This is something that can be done, tag the message at the top, for some time.

What is the time that you think is recommended here?

**Comment by fgl27** [comment]
Added to the app TODO list.
