### ISSUE TITLE
Getting ADS in streams I am subbed to

### ISSUE THREAD

**Issue by hbashton** [fgl27/smarttv-twitch#132]
As of today (this didn’t happen yesterday), I’m now getting ads in streams I’m subbed to. I’ve added my key and logged into the app, which previously removed ads in streams to which I was subscribed

**Comment by xian042** [comment]
Another report of this. Both pre-roll and mid-roll ads on subscribed channels

**Comment by fgl27** [comment]
this is duplicated issue of https://github.com/fgl27/smarttv-twitch/issues/130 check there
