### ISSUE TITLE
Black loading screen

### ISSUE THREAD

**Issue by Morshed11218** [fgl27/smarttv-twitch#133]
**Describe the bug**
No matter what channel I'm trying to view, it's stuck on a black screen the loading spinner. It suddenly started doing this in the middle of a stream. 

If is a installation issue screenshot any error or wherever related that is generated during the installation.

If is something that causes a issue when using the app share a log bellow link informs how to log this app

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**To Reproduce**
1. Go to 'Any channel;
2. Click on 'view the stream'

**Expected behavior**
View the stream 
![A63885E9-3BE3-4051-8F17-04BDACEA0ADA](https://user-images.githubusercontent.com/2136499/94633459-50941300-029b-11eb-84c2-4ececa014850.jpeg)

**Comment by fgl27** [comment]
https://github.com/fgl27/smarttv-twitch/issues/130

**Comment by Morshed11218** [comment]
Yes, trying to view any channel will result in a black screen with the loading spinner.

**Comment by fgl27** [comment]
> Yes, trying to view any channel will result in a black screen with the loading spinner.

it seems all fine for me have you try to reset the TV, or reinstall the app?

**Comment by fgl27** [comment]
if that doesn't solve try to debug the app and show me the result

to debug see https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**Comment by Morshed11218** [comment]
plugging off the tv fixed it. Thank you.
