### ISSUE TITLE
List of followed channels not refreshing

### ISSUE THREAD

**Issue by plstxz** [fgl27/smarttv-twitch#134]
Yesterday, Sep 29, list of followed channels stopped refreshing correctly. Whenever I try to do so (by pressing UP button during stream or LEFT button in the main screen) the list is shown empty and the refresh amination goes on infinitely.

**Comment by fgl27** [comment]
Followed channels or channels live?
Username?
Do you have a active authorization key?

**Comment by plstxz** [comment]
Yes, I meant live channels.

My bad. I never added authorization key and app worked fine for me. Just now I've added the key and live channels list is refreshing fine again.

Thank you for the help and sorry for the hassle.

Really enjoying your app.

**Comment by fgl27** [comment]
I need the username

That screen works different with a key

**Comment by fgl27** [comment]
> I need the username
> 
> That screen works different with a key

@plstxz replay please.

**Comment by plstxz** [comment]
You mean actual user name on Twitch?

It's "plstx"

**Comment by FreeMaN2218** [comment]
Same issue. But first the app died (no response from any keys, tried to restart the app and TV - no result), so I reinstalled it, and everything worksexcept "Live" in my account. Added key - "Live" now works. Twitch username <FreeMaN2218>

**Comment by fgl27** [comment]
There was a change on the twitch API that is used when the user doesn't provide a key, causing this issue... the above fix it.

Close the app by holding return key, after open it again all must work

![Screenshot from 2020-09-30 18-40-47](https://user-images.githubusercontent.com/13755892/94742865-ce642700-034c-11eb-917b-7761759539d9.png)

![Screenshot from 2020-09-30 18-17-13](https://user-images.githubusercontent.com/13755892/94742878-d0c68100-034c-11eb-95e7-b7854f02c2c1.png)

**Comment by fgl27** [comment]
> Same issue. But first the app died (no response from any keys, tried to restart the app and TV - no result), so I reinstalled it, and everything worked except "Live" in my account. Added key - "Live" now works fine. Twitch username "FreeMaN2218". App version 4.0.1 V5

To avoid having to re-install the app, there is a building function that must work on that situation
 in controls we have this

**"Force erase all app config: in case the app misbehave and stop working, hold key channel UP or Down for 20 seconds anywhere in the app, after it 10 seconds there is a confirmation"**

It will have the same behave as re-installing the app, as reinstalling it will erase all the saved appconfig.

![image](https://user-images.githubusercontent.com/13755892/94743424-be007c00-034d-11eb-9b52-50edd1595115.png)
