### ISSUE TITLE
App is frozen

### ISSUE THREAD

**Issue by detile** [fgl27/smarttv-twitch#135]
Hello,
A few days ago this twitch app stop working.
I can see the menu on the left with my avatar, but there is a black screen in the middle. No livestreams, nothing. I can't naviguate in the menu, like the app is frozen.
I tried to forse close the app but it's the same after restart.
Should i reinstal it or is there a way to fix it ?

(By the way, when reinstalled it a few monthes ago on my new TV, the app icon was a yellow one with ''test only'' on it, twice large as other apps...)

**Comment by fgl27** [comment]
> (By the way, when reinstalled it a few monthes ago on my new TV, the app icon was a yellow one with ''test only'' on it, twice large as other apps...)

That is because you didn't download the proper installation file

**Comment by fgl27** [comment]
> Should i reinstal it or is there a way to fix it ?

To avoid having to re-install the app when it stops responding even ater reboots, there is a building function that must work on that situation...

In controls we have this:

**"Force erase all app config: in case the app misbehave and stop working, hold key channel UP or Down for 20 seconds anywhere in the app, after it 10 seconds there is a confirmation"**

It will have the same behave as re-installing the app, as reinstalling it will erase all the saved appconfig.

![image](https://user-images.githubusercontent.com/13755892/94743424-be007c00-034d-11eb-9b52-50edd1595115.png)

**Comment by fgl27** [comment]
If you don't have the proper app icon showing just install the app download the correct zip and install again so everything can properly work.
