### ISSUE TITLE
Select multiple languages

### ISSUE THREAD

**Issue by LordBoos** [fgl27/smarttv-twitch#136]
**Please describe the feature.**
I'd like to select more stream languages than 1 or all.

**Additional context or samples**
Eq. I want to see Czech, Slovak and English streams only. Right now I can only select "All languages" or 1 language.

**Comment by fgl27** [comment]
That how twitch api works, they allow one or none

**Comment by LordBoos** [comment]
Well you could call the API multiple times for each selected language and then merge the results to one list.

**Comment by LordBoos** [comment]
Also I'm sorry, but this issue was supposed to be for Android version of the app, not the SamsungTV one.
