### ISSUE TITLE
White screen after Twitchtv loading

### ISSUE THREAD

**Issue by TeodorEvtimov** [fgl27/smarttv-twitch#137]
Hey guys, I cannot load the app on Samsung 7 series. When I try to open the app I see twitchtv  loading and the spinner disappears and the only white screen is shown. Any suggestions on how can I fix it ?Thanks!

**Comment by fgl27** [comment]
If you just install the app you probably did it wrong.

If the app was already installed or If you are sure you install it the correct way, debug the app as is explain here https://github.com/fgl27/smarttv-twitch/issues/127#issuecomment-681289984

**Comment by TeodorEvtimov** [comment]
Thanks for the fast response. The app is working now, the problem was the project files was not in the root directory. Awesome than you dude.
