### ISSUE TITLE
fgl27.github.io returns 404, app launches to blackscreen

### ISSUE THREAD

**Issue by AtomicStryker** [fgl27/smarttv-twitch#138]
Is there something wrong with the github pages site? It opens to a 404 here. I can't reinstall or launch the app on my TV obviously, since it tries to pull something from that URL.

**Comment by fgl27** [comment]
You can test yourself https://fgl27.github.io/smarttv-twitch/release/index.html
Open just fine for me

https://www.githubstatus.com/ github status page also says that all is workung

Check yours local network and ISP

**Comment by AtomicStryker** [comment]
![image](https://user-images.githubusercontent.com/1858566/97109253-7235be00-16d2-11eb-864b-cba84bd11f3a.png)
This is what Tizen Studio "Run As Debug" Mode shows

OK i was initially trying to open fg127, not fgl27, stupid fonts.

TV during this:
![image](https://user-images.githubusercontent.com/1858566/97109344-056ef380-16d3-11eb-88f1-6579adb4f562.png)

Using Web App on TV to access https://fgl27.github.io/smarttv-twitch

![image](https://user-images.githubusercontent.com/1858566/97109359-220b2b80-16d3-11eb-998f-133cee013b89.png)

I get an https certificate error

![image](https://user-images.githubusercontent.com/1858566/97109383-35b69200-16d3-11eb-8493-31fd288d6c17.png)

When i click on "go to the site anyway" button the TV can resolve it

![image](https://user-images.githubusercontent.com/1858566/97109401-5252ca00-16d3-11eb-9040-a6a0c4b38869.png)

**Comment by AtomicStryker** [comment]
OK since you have nothing to do with githubs https certificates, and my browser says it should be good to 2022 easily, the problem is likely with my TV's firmware or software. Joy. Thank you

**Comment by fgl27** [comment]
That html file is already part of the release, that was just so you can test yours network on a computer not on the TV, if it works on a computer the TV is the problem.

The main file that the app needs to load is https://github.com/fgl27/smarttv-twitch/blob/master/release/index.html#L45

You need to find why that file doesn't load on the TV.

If you can't fix you may download the files manually 

https://github.com/fgl27/smarttv-twitch/blob/master/release/index.html#L25
https://github.com/fgl27/smarttv-twitch/blob/master/release/index.html#L26
https://github.com/fgl27/smarttv-twitch/blob/master/release/index.html#L45

Place them on the same path as the .html file, in the project folder and update those html lines basically remove all minus the file name

So ' https://fgl27.github.io/smarttv-twitch/release/githubio/js/master.js' becomes just 'master.js' 

The setback of that is if I make a change on those file you need to redownload them and reinstall the app.
There is a chace the app stops working as a update is needed but technically you can run it like that until it stops working, or you fix the local issue.

**Comment by AtomicStryker** [comment]
Thank you, i tried that. In normal execution it stops at the loading circle and a black screen.

Running in Debug, i get this in the console:

![image](https://user-images.githubusercontent.com/1858566/97114367-6953e500-16f0-11eb-8601-aaf399244232.png)

**Comment by fgl27** [comment]
Yes in forget about the fonts that those CSS use

**Comment by fgl27** [comment]
Download the repo and place this folder https://github.com/fgl27/smarttv-twitch/tree/master/release/githubio/css/fonts
On the root of the project folder....

I think will work.

**Comment by AtomicStryker** [comment]
After doing that:

![image](https://user-images.githubusercontent.com/1858566/97114919-ab325a80-16f3-11eb-9562-b34a084b4545.png)

I have a suspicion some kind of root cert on the TV timed out, and now it can't connect to any websites which use a cert chain verified by that one

**Comment by AtomicStryker** [comment]
I checked with the TV's browser ... both github.com and twitch.tv throw certificate errors. So this stupid thing won't build any ssl connections there by default. I highly doubt the app can be made to work...

**Comment by fgl27** [comment]
Try to reset the TV to factory default

That TV browser isn't a real browser is full of issues that may not be related to the app loading issue.

**Comment by AtomicStryker** [comment]
I reset the TV (it kept the Wifi). Right after going through initial setup and TV channel scan i tried the browser to github.com ... no cert error. The damn thing still had the history, so it wasnt reset either.

Did the other settings, switched TV back to dev mode again, installed (the nonmodified) smarttv-twitch again ... works first try.
I'm quite baffled.

I wish my TV wouldn't randomly kill the app every couple months. Thank you for your support.

**Comment by fgl27** [comment]
You welcome, tizen is just like that makes no sense sometimes.
