### ISSUE TITLE
Ads and or Commercial break issues

### ISSUE THREAD

**Issue by missiah** [fgl27/smarttv-twitch#139]
I'm a daily user and notice that since today.
Is it possible to fix this?

https://imgur.com/a/VXAKd3u

**Comment by fgl27** [comment]
I saw that on a stream, I wasn't watching just open for a second...

Isn't that trigger by the streamer?

I can't replicate that at will so I don't know how starts.

**Comment by missiah** [comment]
I had this on two Streams and it always appeared when i quickly switch between them and not let the countdown run to 0.
Only after i let run the countdown down to 0 it is gone for now,
I was able to reproduce that screen on https://www.twitch.tv/twitchmedia39 (side note: That Channel is kind of different to others and there are bunch of twitchmediaXX channels that behave in the same way, i can't tell exactly why but i know that some Adblock Developers use them as a reverence.)
My two Streams i mentioned before are of course not a twitchmediaXX Stream, just normal Streams.

**Comment by fgl27** [comment]
Yes the region affects, here where I'm the only adds that show are from Amazon...

When a app triggers there is that issue of you have to watch it to the end or it keep coming until you do.

I will take a look see if I can trigger it and see what can be done...

If others have the same issue and have more info to share will be great.

**Comment by fgl27** [comment]
I manage to find a channel that was constantly give me that "Comercial..." and manage to prevent...

Close the app by holding the return/back key after you reopen it must be updated, try a channel with that issue and let me know the result

**Comment by fgl27** [comment]
Now the commercial break is gone, but there is a add on it's place

They are changing things I will test and see

**Comment by missiah** [comment]
Can confirm, now real ads are playing.
In the worst case scenario if you can't get rid of it completely I would prefer the commercial break in progress thingy because it is quite.
The volume different between the real stream and the ads are humongous 😭

**Comment by fgl27** [comment]
If you let the 'commercial break" thing it never goes a way, the add go and it is less served.
I need more time to work on this. It may just go away just like the last time after a few days.

**Comment by missiah** [comment]
The commercial break thing did go away for me after I let the 15 seconds countdown run down and after that the stream automatically started for me.

**Comment by fgl27** [comment]
I'm not getting ads anymore, probably my region and or local time...
I test this tomorrow again, and if the issue persist I share a test app so you can test side by side, one with ads one with the break thing.

Let me know how is for you after 10+ hours or so.

**Comment by missiah** [comment]
Sure I will test everything and try to help as much as I can.

**Comment by walkintall15** [comment]
Can confirm. I think its happening every time a partnered streamer pressed the AD button (they have the option to roll ADs) in their streaming interface (up to 3 min) for all non subs. Seems Twitch changed the way those ADs are shown. Hope its fixable. Love the App :)

**Comment by missiah** [comment]
As far as I know, there are three types of ads on Twitch.

First one is the pre-roll Ad you can get when you start watching a stream, they are controlled by Twitch and the streamer cannot control them, you can only avoid them if you have Twitch Turbo or be a subscriber of that Channel.

Second one is the manual activated Ad, Streamer start them on the dashboard by hand or put a time frame in it when he wants Ads get automatically played.

Third one is if the streamer not play any Ads manually or have setup a time frame to play them automatically, twitch will play on a random behavior automatically Ads.

Important: I cannot confirm any of this by myself, it is only the information I gather on few platforms, apparently I have no real contact to a Twitch employee to confirm this.

**Comment by fgl27** [comment]
I push a update base on this:

> Update nope this fix doesn't work anymore bummer
> 
> from this link I am using ublock and this fix and it seems to be working [https://www.gamingscan.com/ublock-origin-not-blocking-twitch-ads/](url)
> can this help for a fix?

That seems to do it, at least regarding the constant "Commercial break' it prevents.

There is more then one combination of things that can be done when requesting an stream link I testing one, if that doesn't help let me know.

Close the app and reopen so it updates and test.

:+1:

**Comment by fgl27** [comment]
> Can confirm. I think its happening every time a partnered streamer pressed the AD button (they have the option to roll ADs) in their streaming interface (up to 3 min) for all non subs. Seems Twitch changed the way those ADs are shown. Hope its fixable. Love the App :)
> 
> @fgl27 Prolly the reason why you haven't seen much of those ADs. Not many (bigger) streamers press the AD button.

I was watching a stream when the streamer inform that was going to show ads and noting was show, so the only ads be hitting the app seems to be pre-roll for none sub/turbo...

About Turbo and sub ads...

I inform the reason why is this before... a few weeks when a flood of ads was hitting the app some users had the same problem.

Twitch remove the option to inform who is watching the stream via the player, preventing turbo and sub privilege from be used.

I explain that the only way to get the same result as Twitch app or website is faking be it, with may cause the app or the user some problem.

**Comment by missiah** [comment]
I test a while now on a lot on different channels that I know of they rolling ads constantly and so far I got absolutely zero pre or mid-roll ads, it seems you fix it. 

Even on twitchmedia channels zero ads, for sure I will test further the upcoming days and weeks, if something appears I will let you know.

Thanks again that you take the time to look into this and the quick response.

I will let it in your hands when you wanna close this issue thread.

@fgl27 you are a Hero ❤️

**Comment by fgl27** [comment]
OK thanks for all the help, I will let this open for a few days if all good I close it.

**Comment by fgl27** [comment]
ads are showing no matter what they update things to avoid any know workaround, if anyone has any new workaround let me know.

**Comment by fgl27** [comment]
I notice a odd behavior of twitch sites and apps, if you are logged in the ads are no logged spamming as before, technically I don't see any when logged, but if I go incognito I get the ads (with is very unfortunate to them as they don't really know how to proper advertise this or the way before is not the way).

If anyone is having ads let me know the region and frequency.

Using this app I particularly don't have any ad today.

**Comment by missiah** [comment]
Yesterday I got 5 pre-rolls behind each other in very low quality, in spanish and english on twitchmedia38 the first time I tested it.

On regular streams I got nothing, no pre or mid-rolls, can't tell if it was because I already saw so many on twitchmedia38.

Today, nothing so far on any stream, even twitchmedia38 nothing.

(Country: Germany)

**Comment by fgl27** [comment]
> Yesterday I got 5 pre-rolls behind each other in very low quality, in spanish and english on twitchmedia38 the first time I tested it.
> 
> On regular streams I got nothing, no pre or mid-rolls, can't tell if it was because I already saw so many on twitchmedia38.
> 
> Today, nothing so far on any stream, even twitchmedia38 nothing.
> 
> (Country: Germany)
> I was always logged in.

Things changed for me around 15 to 18h ago, so maybe the one you got yesterday was on the old situation before that change.

Lets keep monitoring.

**Comment by fgl27** [comment]
Reopen this or open a new one the day we have issues lie this again. :+1:

**Comment by cizaquita** [comment]
> I push a update base on this:
> 
> > Update nope this fix doesn't work anymore bummer
> > from this link I am using ublock and this fix and it seems to be working [https://www.gamingscan.com/ublock-origin-not-blocking-twitch-ads/](url)
> > can this help for a fix?
> 
> That seems to do it, at least regarding the constant "Commercial break' it prevents.
> 
> There is more then one combination of things that can be done when requesting an stream link I testing one, if that doesn't help let me know, we try another.
> 
> Close the app and reopen so it updates and test.



> Reopen this or open a new one the day we have issues lie this again.

Hi, 

I'm getting video ads in streams.

Maybe Twitch is avoiding the ublock script that you use for this fix :/

**Comment by fgl27** [comment]
> > I push a update base on this:
> > > Update nope this fix doesn't work anymore bummer
> > > from this link I am using ublock and this fix and it seems to be working [https://www.gamingscan.com/ublock-origin-not-blocking-twitch-ads/](url)
> > > can this help for a fix?
> > 
> > 
> > That seems to do it, at least regarding the constant "Commercial break' it prevents.
> > There is more then one combination of things that can be done when requesting an stream link I testing one, if that doesn't help let me know, we try another.
> > Close the app and reopen so it updates and test.
> 
> > Reopen this or open a new one the day we have issues lie this again.
> 
> Hi,
> 
> I'm getting video ads in streams.
> 
> Maybe Twitch is avoiding the ublock script that you use for this fix :/

I'm not using any.

What do you have? ads o the start, on middle on end?
on what stream?
on what frequency?

**Comment by missiah** [comment]
I would like to take the opportunity to report an update on my part.  

For almost 2 weeks after you installed the last update, I haven't had any ads, I checked several channels again today and also Twitchmedia38, nothing.  

Everything works fine for me.
