### ISSUE TITLE
Language selection problem.

### ISSUE THREAD

**Issue by gbmgbm** [fgl27/smarttv-twitch#14]
It only detects the channel language.
It can't detect broadcaster language.

I think broadcaster language should be given priority over channel language.

Thank you.

**Comment by fgl27** [comment]
That is how twitch sends the content the app just display it.

I can't change it, tell the streamer that they a

**Comment by fgl27** [comment]
https://dev.twitch.tv/docs/v5/reference/streams/#get-live-streams
"Constrains the language of the streams returned. Valid value: a locale ID string; for example, en, fi, es-mx. Only one language can be specified. Default: all languages."

**Comment by fgl27** [comment]
@gbmgbm I discover that one can request language by broadcast language, but that is a undocumented option that I manage to find by guessing. so the above change the live content that uses language to show "broadcaster_language".

Only works to show content only on Live and Agame screen as those are the only "live" content that accepts the filter.

Other changes there are related to the display of the language in the information panel and thumbnails

**Comment by Cabeza2000** [comment]
Hey Felipe, thanks for this app. Just installed and is working fine (still did not turn off the TV but hopefully will not have the bug described in 11/18).

About language selection I just have a problem, in the discontinued app I used to filter by more than one language (Spanish and English) but could not find a way to do it in your app? Is this something that you can add in the future?

**Comment by fgl27** [comment]
@Cabeza2000 yes of course, open a issue with a featuring request so I don't forget about it

**Comment by Cabeza2000** [comment]
Done. Thanks!

#20

**Comment by gbmgbm** [comment]
@fgl27 Many thanks. Everything is working fine.
