### ISSUE TITLE
black screen between maps

### ISSUE THREAD

**Issue by jodafi** [fgl27/smarttv-twitch#143]
I am mostly watching CS on Twitch... The last two days the stream will go black every time a map is finished and the stream pause or go to commercial. The only solution is to end the app and restart every time..
I hope you can help 
btw Thanks :)

**Comment by fgl27** [comment]
What steam?

**Comment by jodafi** [comment]
Anything stream i have watch the last two days on Twitch go Black at some point, and the only "fix" is to close the app and start it again.

**Comment by jodafi** [comment]
ESL, Flashpoint...

**Comment by jodafi** [comment]
I have mostly watch ESL Stream.. I will double check Flashpoint stream now... perhaps it just ESL stream??

**Comment by jodafi** [comment]
Have been watching Flashpoint for 2 hours now without any fault.. So maybe its just ESL stream.. weird I have not seen this problem before

**Comment by jodafi** [comment]
just turnt over too ESL stream. The map has just ended and a commercial comes on, it starts to stutter a little bit and after 2 min. black screen again??

**Comment by jodafi** [comment]
i have just checked my tv upstairs (top line Samsung from 2019) same problem. Starts to stutter when shifting from studio/game to break/commercial and the it goes Black.

**Comment by fgl27** [comment]
Noting I can do that is a device issue it can't for some reason deal with the add.change.

You probably can just change the qualify to the same by press enter over the player quality control to.resolve that.

This isn't something I can replicate so I can't find a solution

**Comment by jodafi** [comment]
i have seen many many hundred of hours without problem, so its wierd? 
Many thanks for trying :) 
Its on all 3 tv´s i have and they are all different. have you tried with this stream https://www.twitch.tv/esl_csgo? 
I will try to reinstall on one off the tv´s this weekend

**Comment by fgl27** [comment]
I have minute free a day I tryed for moment no issue.

Maybe yours network is blocking twitch ads some how, if the ads can play you will have no issue

**Comment by jodafi** [comment]
No ads blocking here in denmark.
when showing gameplaying no problem, only when game is over and switching to/and between adds and studio..

**Comment by fgl27** [comment]
No one has ever had that issue, I assume is a local issue on yours network or devices

**Comment by jodafi** [comment]
thanks

**Comment by jodafi** [comment]
it only started 2-3 day´s ago

**Comment by fgl27** [comment]
Twitch just change things this week...

**Comment by fgl27** [comment]
I send you a email, over the email I receved from yours donation, let me know what you think, please replay that only via email as is something that needs ti be private.

Thank you a lot.

**Comment by jodafi** [comment]
Thanks for all you help :)
