### ISSUE TITLE
Ads on Twitch app

### ISSUE THREAD

**Issue by KilledGiovy96** [fgl27/smarttv-twitch#144]
how to remove advertising from the twitch app

**Comment by fgl27** [comment]
Not possible for third party aps.

das must go away in a few days.

**Comment by KilledGiovy96** [comment]
Ok thanks

**Comment by fgl27** [comment]
I let you know when here I see a change.

**Comment by KilledGiovy96** [comment]
Ok thanks

**Comment by fgl27** [comment]
Shuld be good after this, if not test in 12hours or so and let me know

**Comment by fgl27** [comment]
If the problem return let me know thanks... Close in this.
