### ISSUE TITLE
Installing the app on a second TV

### ISSUE THREAD

**Issue by Diamond1337** [fgl27/smarttv-twitch#145]
Hi, i got a second TV and iam worried about how to install it on another TV. I have all setup with the first and it works perfectly. But wich step i had to do just to put the app on a new TV? Can you explain on wich step i join?

Do i have to change something in the tizen studio or Tizen manager? 

I thought i just connect the new TV with the PC and start installing the folder i created on the new TV. but whats about a newer tizen version or so? Should i be worried?

Thanx for your help.

**Comment by fgl27** [comment]
You don't need to change anything on the compute, the same computer the same project can be used on multiple TV.

What else you need to do on the seconds TV is...

Setup yours TV to be in developer mode this step https://github.com/fgl27/smarttv-twitch#set-your-tv-to-developer-mode

Use the same IP as before the computer didn't changed.

Now go to the step you search for the TV on the computer this https://github.com/fgl27/smarttv-twitch#setting-up-the-build-environment

Just click in scan and the new TV will show up...

Now just install as before be repiting this step https://github.com/fgl27/smarttv-twitch#install-the-application
