### ISSUE TITLE
Twitch not launch on TV (black screen)

### ISSUE THREAD

**Issue by tomo92s** [fgl27/smarttv-twitch#146]
After "Run as - Tizen Web Application" from Tizen Studio my Twitch App not working. Instead of this i have black screen and nothing happen.
I have installed all required packages, my TV is in developer mode and nothing helps. Twitch icon appears on my TV but after launch app i have only black screen. Even simulation not working.

**Operation system (if is a installation problem):**
 - OS: Windows
 - Version 10

**Device:**
 - TV Model: UE55TU8002K
 - Os version Tizen 5.5

**Comment by fgl27** [comment]
Delete the project and start over from https://github.com/fgl27/smarttv-twitch#setup-the-application

**Comment by tomo92s** [comment]
I tried many times and still the same problem

**Comment by fgl27** [comment]
Then is probably a network issue check this https://github.com/fgl27/smarttv-twitch/issues/127#issuecomment-681289984

**Comment by tomo92s** [comment]
Debug mode shows me [this](https://i.imgur.com/8mSFVeh.png)

**Comment by fgl27** [comment]
Not what I ask on that issue, share the same window that I did there

**Comment by tomo92s** [comment]
Now is working. I don't touch icon error and now everything works. Can I ask for support for the Polish language in the application?

**Comment by fgl27** [comment]
I don't add translation to languages I don't know. If you wanna you can translate it.

**Comment by tomo92s** [comment]
I must send you translated file or something?

**Comment by fgl27** [comment]
Yes but there is no translation file yet, as the app is going trow a update process, when I finishe there will be some day next year.
