### ISSUE TITLE
Stop Minimize due to Inactivity

### ISSUE THREAD

**Issue by thro86** [fgl27/smarttv-twitch#147]
Hello,

I have noticed in past couple weeks if I am watching a stream after a period of time it will minimise the app and my shield will go to the home screen. A message will pop up giving a 15 second timer is there any way to completely disable this so that I can just keep watching streams without a minimising

**Comment by fgl27** [comment]
Features like this are always informed on the changelog and come with a settings have you took a look at any of those?

![Screenshot from 2020-12-01 11-15-23](https://user-images.githubusercontent.com/13755892/100751882-a7ff4e00-33c6-11eb-94df-58a2b7a585ee.png)

**Comment by thro86** [comment]
> Features like this are always informed on the changelog and come with a settings have you took a look at any of those?
> 
> ![Screenshot from 2020-12-01 11-15-23](https://user-images.githubusercontent.com/13755892/100751882-a7ff4e00-33c6-11eb-94df-58a2b7a585ee.png)

Thank you. I did try and look through the settings before posting and asking for help but I must have missed this option. Thank you!
