### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by samukrdgs** [fgl27/smarttv-twitch#148]
Olá amigo! Obrigado pelo Post.

Estou tendo dificuldades na hora de rodar, apresentar o segundo erro:

Transferring the package... > Fail
Unexpected error occurred at the below step.
 `Transferring the package...`
unknown error

**Comment by fgl27** [comment]
Tens de mostrar um imagem do programa todo quando da este erro para que eu possa entender o que tu fez.

Antes disso tenta entender o processo pois tu deve ter feito algo errado... assim recomendo deletar o projeto e rever os seguintes passos

conectar na TV
https://github.com/fgl27/smarttv-twitch#setting-up-the-build-environment

Cirar o projeto
https://github.com/fgl27/smarttv-twitch#setup-the-application

E a instalação
https://github.com/fgl27/smarttv-twitch#install-the-application

Tenha certeza que as imagens nos processos estão iguais ao que tu tem no teu computador

Caso tu tenha problema com a lingua usa o google tradutor por exemplo este link traduz

https://translate.google.com/translate?sl=en&tl=pt&u=https://github.com/fgl27/smarttv-twitch

Não fica perfeito mas ajuda.

Ai depois de revisar tudo se der erro me mostra o erro mas mostra o aplicativo em tela cheia para ver tudo nele não somente o erro.
