### ISSUE TITLE
Can't load Hosts

### ISSUE THREAD

**Issue by drmaernardi** [fgl27/smarttv-twitch#149]
Every time I open the Hosts section of the User Menu I get the following error: Connection failed, unable to load content. Hit refresh to try again.

Everything else seems to works fine, any insight into what could be the issue?

Thanks you.

**Comment by fgl27** [comment]
Twitch no longer support that API, there is no replacement. Will remove it some day.

**Comment by fgl27** [comment]
The screen was removed, update the app to take effect

To update hold return key until the app closes then open it again.
