### ISSUE TITLE
View sub-only VODs

### ISSUE THREAD

**Issue by aggouris** [fgl27/smarttv-twitch#151]
Hello and thank you for taking the time to develop such an amazing app! 
So is there a way to view subscriber only vods?? I get an error saying that is not supported by third party apps. It would be cool if it could be added.

![IMG_20201228_094649](https://user-images.githubusercontent.com/76680637/103198973-5a590100-48f2-11eb-9088-f3eab9f6cf41.jpg)

**Comment by fgl27** [comment]
If there was do you think the app wild show that?

I'm not Twitch I can't chant what they choose block or not.
