### ISSUE TITLE
Fast Forward on VOD

### ISSUE THREAD

**Issue by KAR0TTENP0WER** [fgl27/smarttv-twitch#152]
Hello, 
would it be possible to use the fast forward feature? I can do that on PC (no idea if its BTTV or original Twitch actually)
Or maybe it's already a feature I'm missing?
Thank you

**Comment by fgl27** [comment]
what is "fast forward feature?" for you?

**Comment by KAR0TTENP0WER** [comment]
Double speed, or slowmo. 0.5x, 1,25x 1.5x 2x ....

**Comment by fgl27** [comment]
Isn't something Samsung TV support that well. Maybe someday I try it again last time was too bug to use.
