### ISSUE TITLE
connection failed after 02/01/2021

### ISSUE THREAD

**Issue by mrfhenix** [fgl27/smarttv-twitch#153]
**Describe the bug**

If is a installation issue screenshot any error or wherever related that is generated during the installation.

If is something that causes a issue when using the app share a log bellow link informs how to log this app

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**To Reproduce**
4. See error something doesn't work
5. Share the log file as image or as txt drag and (drop to the issue text box)

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.

**Operation system (if is a installation problem):**
 - OS: Windows, Linux or ...
 - Version [e.g. 10, 18.4, etc...]

**Device:**
 - TV Model: UN40KU6000H, EH5000 or ...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

connection failed after the automatic 02/01/2021 update
I was watching it without any issues until the update notification.. restarted the app and soft reset TV and nothing 
![16096204856035481507209027061585](https://user-images.githubusercontent.com/36233644/103466324-a7314300-4d09-11eb-8a6f-cda4d7c276a9.jpg)

UN50KU6000

**Comment by fgl27** [comment]
Twitch is the problem just church they website

**Comment by mrfhenix** [comment]
I removed the old user manually and added again and it worked .. You sir rock thanks for your work
