### ISSUE TITLE
Chat not working in version from January 2nd 2021

### ISSUE THREAD

**Issue by georgebvro** [fgl27/smarttv-twitch#154]
**Describe the bug**

After the January 2nd 2021 update, the chat doesn't work anymore.

It says "Connecting to Live Channel: <channel name>" and then "Websocket closed remotely". See attached image for details.

![Twitch chat error](https://user-images.githubusercontent.com/76898691/103474528-8ae6e200-4dad-11eb-8d99-e26dff57fbb1.jpg)

**Device:**
 - TV Model: Samsung 40JU7000
 - Os version: Tizen 2.3

**Additional context**
Chat was working fine until this version.
The stream itself is fine (video and audio).
I've tried adding a new authorization key and also I've tried removing the user and adding it again. Nothing helped.

Thank you for your time looking into it and let me know if I can be of any help.

**Comment by walkintall15** [comment]
Can confirm, since yesterday same issue here. Even tried to delete the connection in my twitch options. Tried twice with different keys, same stuff.

Thanks for looking into it.

**Comment by fgl27** [comment]
this has happened before, I change the chat link on the above it must make it work now.

Update the app to take effect.

To update hold return key until the app closes then open it again.

**Comment by georgebvro** [comment]
Chat is back and it's better than ever.

Thank you for the quick fix!
