### ISSUE TITLE
Missing TV extension on Package Manager

### ISSUE THREAD

**Issue by CustelaKing** [fgl27/smarttv-twitch#157]
Everything was alright except for the "Extension SDK" packages, there is none TV Extensions packages, only the Samsung Certificate Extension
![image](https://user-images.githubusercontent.com/33787950/104030905-da148480-51aa-11eb-98c4-67441580c1ae.png)
then when I try to import the project it shows that I don't have the selected profile, I can only choose between mobile and wearable using the combobox
![image](https://user-images.githubusercontent.com/33787950/104031376-68890600-51ab-11eb-97b7-4d6b6d2f5192.png)

**Comment by fgl27** [comment]
Show me all the options you have under "Extras"  In the extensions SDK

The TV extension is one of the first you are only screen shot the last options

**Comment by CustelaKing** [comment]
![image](https://user-images.githubusercontent.com/33787950/104049465-c6294c80-51c3-11eb-9fe9-d261767ab8e2.png)
![image](https://user-images.githubusercontent.com/33787950/104049509-d50fff00-51c3-11eb-9806-b4b51c2ff79e.png)
![image](https://user-images.githubusercontent.com/33787950/104049561-ec4eec80-51c3-11eb-8dca-f0202088378c.png)
there you go

**Comment by fgl27** [comment]
Try to install all in main SDK then reboot if that doesn't work you will have to try a different OS add tizen is bugged on that

**Comment by CustelaKing** [comment]
Just installed everything from Main SDK, rebooted my computer and still no signal of any Tv Extension.
Then I moved into settings of package manager and i've found the problem
![image](https://user-images.githubusercontent.com/33787950/104053152-85cccd00-51c9-11eb-83f7-5c1e3b8e8c73.png)
and when I try to activate it I get this error
![image](https://user-images.githubusercontent.com/33787950/104053279-b44aa800-51c9-11eb-8a7f-ac1759de5434.png)

**Comment by fgl27** [comment]
That link isn't the issue, if the manager is OK of shows no link are needs to be enabled.

Samsung does that they update they SDK and don't even use it.

They update to version 4.1 two weeks ago and there they have bug it out.

Use another OS on a virtual machine Ubuntu 16 or 18 must work don't user Ubuntu 19 or above

**Comment by samoralespu** [comment]
This happened same to me. I tried it on windows and on linux, and same error. I think it's samsung problem because I tried download it manually and I couldn't. Check this link: https://developer.samsung.com/smarttv/develop/tools/tv-extension/archive.html
If you try to download the version 6.0 it works and you can download a .zip, but if you choose version 5.5 it redirects to 403 error page. Maybe we have to find the .zip with the version 5.5 extension.

**Comment by borzaka** [comment]
Same problem:
The **Samsung Tizen TV SDK** is disabled in the settings due to that the extension repository URL is not available.
If I try to active:
![image](https://user-images.githubusercontent.com/1230402/104073513-2ba22b00-520e-11eb-814c-ea495699c65c.png)

**Comment by fgl27** [comment]
I don't think there is a 6.x but if there is must work.

I don't think the extension has any relation to the TV SDK, I have no idea what Samsung is doing or how they associated this extension.

Last time this happen the solution was to download a old version of the SDK something Samsung doesn't provide, check old issues related to missing extension to have more info in what was done before

**Comment by jopei1500** [comment]
I had the same issue, fixed it by manually downloading version 6.0  (5.5 seems to be gone?) from: https://developer.samsung.com/smarttv/develop/tools/tv-extension/archive.html

Then under settings in the package manager I added the locally stored file as an extension/repository.

![Screenshot from 2021-01-10 19-12-14](https://user-images.githubusercontent.com/20153318/104131650-ff0a2280-5377-11eb-84e2-ff209bdd406e.png)

**Comment by Drezus** [comment]
Thanks @jopei1500 ! That did the job.
@fgl27 it'd be useful if you could update the main page's tutorial to include the possibility of having to download the extension repo separatedly, and explain that you can add a local cached repo from Tizen Package Manager (because it makes it look like you can only use web URLs).

**Comment by fgl27** [comment]
I'm on vacation now update when I can thanks

**Comment by biltongza** [comment]
@jopei1500 could you explain how you did that? I downloaded the repo, when I added it to package manager it said it needed to uninstall and reinstall the entire SDK, but it hung halfway and just wound up uninstalling the whole IDE?

**Comment by fgl27** [comment]
Maybe this help, the extension 6.0 is now showing to me but I had to enable a option

On extension SDK tab, click on the configuration icon, then on Extension SDK (drop down on left borrow corner), on that enable samsung Tizen TV SDK press OK and it must show the necessari package of this tab (TV Extension-6.0 and TV Extension Tools), plus all others recommended on the main readme...

![Screenshot from 2021-05-17 07-26-42](https://user-images.githubusercontent.com/13755892/118475376-909cee80-b6e2-11eb-98e3-6cffe97aab39.png)

![Screenshot from 2021-05-17 07-26-47](https://user-images.githubusercontent.com/13755892/118475391-9561a280-b6e2-11eb-93d7-983d74fe39ec.png)

![Screenshot from 2021-05-17 07-27-01](https://user-images.githubusercontent.com/13755892/118475408-998dc000-b6e2-11eb-8b00-eba53ca7cfd7.png)

![Screenshot from 2021-05-17 07-35-17](https://user-images.githubusercontent.com/13755892/118475411-9a265680-b6e2-11eb-9189-a640377be81c.png)

**Comment by itsthe1-apps** [comment]
I downloaded Tizen Studio 5.0 and in the Package Manager, TV Icon missing in Main SDK Tab. 

<img width="645" alt="Screen Shot 2022-12-15 at 11 55 54" src="https://user-images.githubusercontent.com/52661130/207788188-719bf19f-9815-44bf-b9c2-5a6d04f4f7dd.png">

How to enable that? I did turn off auto update. But nothing works.

**Comment by fgl27** [comment]
> I downloaded Tizen Studio 5.0 and in the Package Manager, TV Icon missing in Main SDK Tab.
> 
> <img alt="Screen Shot 2022-12-15 at 11 55 54" width="645" src="https://user-images.githubusercontent.com/52661130/207788188-719bf19f-9815-44bf-b9c2-5a6d04f4f7dd.png">
> 
> How to enable that? I did turn off auto update. But nothing works.

missing, when did it ever was there?

TV is a extension of the sdk read the below again:

https://github.com/fgl27/smarttv-twitch#tizen-package-managerinstalling-the-tools
