### ISSUE TITLE
Feature request : Stream Latency Stat

### ISSUE THREAD

**Issue by U3b3** [fgl27/smarttv-twitch#158]
**Please describe the feature.**
I don't know if this is possible, but on Desktop with the FFZ App you can see the Latency To Broadcaster in seconds. Would be cool to see that on the TV App 

**Additional context or samples**

![Screenshot 2021-01-11 172928](https://user-images.githubusercontent.com/68308468/104209966-9cc22800-5432-11eb-8a87-535871023ecc.png)

**Comment by fgl27** [comment]
I don't konw of is possible on tizen, if is will add it some day.

**Comment by fgl27** [comment]
This is not possible on Tizen as there is no player API that can be used that provides it, FFZ pull this info from Twitch site player it self, that twitch player only works on Twitch site.
