### ISSUE TITLE
Low Latency Enable/Disable is switched around

### ISSUE THREAD

**Issue by Drezus** [fgl27/smarttv-twitch#159]
The english strings for the Low Latency options in the on-stream menu are switched around.

"Low Latency (Enable)" appears when Low Latency is already enabled.
"Low Latency (Disable)" is shown when the stream is not using low latency mode.

Strings should either read as "Low Latency **(Enabled)**" and "Low Latency **(Disabled)**" to indicate the correct mode the stream is currently using, or just switched around so "Enable" and "Disable" indicate the correct actions of turning Low Latency mode ON and OFF.

**Comment by fgl27** [comment]
Thanks I'll fox when I have the time

**Comment by fgl27** [comment]
This was changed, close the app and reopen so the changes takes effect
