### ISSUE TITLE
Watch the beginning of a live stream

### ISSUE THREAD

**Issue by gabrieluly** [fgl27/smarttv-twitch#16]
Hi there first of all congratulations on the app, it is awesome. I use it everyday and it's way better than Twitch's one.

Before this last update if a channel was live I could watch the beginning (kinda like rewinding) of the live stream just by going to the past broadcasts session, it was really handy but right now a broadcast will only appear there when it actually ends which sometimes takes hours. Is it possible to rewind the old behaviour? Or maybe even implementing a rewind function to live streams? Thank you.

**Comment by fgl27** [comment]
Twitch change some things, that prevent the app from show it, I will make a fix and then close this.

**Comment by fgl27** [comment]
Done, press the green (b) key from live screen to reload and update the app and the problem must be solved.

**Comment by gabrieluly** [comment]
Awesome, thanks!
