### ISSUE TITLE
Streams with 4:3 aspect ratio get force stretched to fill

### ISSUE THREAD

**Issue by Elapsed** [fgl27/smarttv-twitch#160]
Hey, I just set this awesome Twitch solution up, so delete my bug if I'm just being a total ditz and missing the setting/option. But when watching a stream that's in a 4:3 ratio like SaltyBet, the app stretches the stream to fill the screen, making everything super wide and distorted. 

I'm including images. One is a screenshot of SaltyBet from my phone app, the other is a photo I took while running this app on my Samsung tv.
![20210112_110547](https://user-images.githubusercontent.com/2513867/104360710-5918fe00-54c6-11eb-858b-814f95c7eba5.jpg)
![Screenshot_20210112-110537_Twitch](https://user-images.githubusercontent.com/2513867/104360712-59b19480-54c6-11eb-9d52-fa7a9749cdb0.jpg)

**Comment by fgl27** [comment]
I expect that the default behavior was keep the aspect ratio, but isn't.

I update it on the above change, close the app and reopen so it updates and it must show as expected.

**Comment by Elapsed** [comment]
That fixed it! Thank you!
