### ISSUE TITLE
Any channel is offline

### ISSUE THREAD

**Issue by KilledGiovy96** [fgl27/smarttv-twitch#161]
Any channel is offline

**Comment by endomorphine** [comment]
same here

**Comment by endomorphine** [comment]
I can browse categories click to open any stream, but it always says stream has ended

**Comment by KilledGiovy96** [comment]
@fgl27

**Comment by Juanjor3** [comment]
same here

**Comment by missiah** [comment]
Same problem, when I try open a stream it says immediately stream has ended.

**Comment by IceColdxx3** [comment]
Same Here

**Comment by Rikeard** [comment]
Same here, it was happening with some channels earlier this week but now all of they are gone

**Comment by Elapsed** [comment]
Just happened to me too

1) I've rebooted the TV
2) closed the app repeatedly
3) logged out and back in

Twitch is otherwise up in other apps

**Comment by KilledGiovy96** [comment]
> È successo anche a me
> 
> 1. Ho riavviato la TV
> 2. ha chiuso l'app ripetutamente
> 3. disconnesso e di nuovo in
> 
> Twitch è altrimenti attivo in altre app

Dont work

**Comment by GalaxyNET** [comment]
Twitch stopped working, stream has ended on live and last videos.

**Comment by detile** [comment]
Same. Works well in official android app atm

**Comment by jopei1500** [comment]
I just looked at it and from a first glance it looks like twitch shut down the API used for this implementation. Probably needs a bit more work to get this working again, could be wrong though.

**Comment by jreunavu** [comment]
My modded twitch apk had same problem. Author of the apk said that turning off "SureStream adblock" will get it working again, and it did indeed. Does this use similar adblock?

**Comment by Elapsed** [comment]
> > È successo anche a me
> > 
> > 1. Ho riavviato la TV
> > 2. ha chiuso l'app ripetutamente
> > 3. disconnesso e di nuovo in
> > 
> > Twitch è altrimenti attivo in altre app
> 
> Dont work

Sorry for the confusion, I was also saying that didn't work

**Comment by GalaxyNET** [comment]
> My modded twitch apk had same problem. Author of the apk said that turning off "SureStream adblock" will get it working again, and it did indeed. Does this use similar adblock?

It doesnt have that option in settings.

**Comment by Justinsan7** [comment]
I have the same problem, I see people are talking about disabling an addblocker, can anyone post a picture of where this option is ?

**Comment by fgl27** [comment]
close the app reone must work.
