### ISSUE TITLE
Online streams are seen as offline

### ISSUE THREAD

**Issue by TilonH** [fgl27/smarttv-twitch#162]
**Describe the bug**

I have installed the application succesfully, and have used it for several months. Now suddenly this issue has popped up (13.01.2021) whenever i go to my followed channels and klick on a stream which is online (it is for sure online i checked simultaneously on my phone) it shows the stream as offline and the timer that counts down and then goes back to the following page. This is the case for every stream not only the following. I also tried renewing the authentification key but it didnt make a diffrence, i havent tried a reinstall yet.

If is a installation issue screenshot any error or wherever related that is generated during the installation.

If is something that causes a issue when using the app share a log bellow link informs how to log this app

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**To Reproduce**
User menu - live - click on any online stream

**Expected behavior**
Stream should open normally and run

**Screenshots**
-

**Operation system (if is a installation problem):**
 - OS: Windows, Linux or ...
 - Version [e.g. 10, 18.4, etc...]

**Device:**
Samsung Tv (i dont know the model anymore) 

**Additional context**

**Comment by paulohpf** [comment]
Here the same, I cleared all data and cache and now i cant put the authentication key like the api is off

**Comment by fgl27** [comment]
close the app reone must work.
