### ISSUE TITLE
Github.io

### ISSUE THREAD

**Issue by RaTeNo** [fgl27/smarttv-twitch#167]
Hi, is it realistic to change the location of the plugin from github.io to a different domain? Github.io does not work in Belarus

**Comment by fgl27** [comment]
Ins't. Are you sure github.io is the issue and not the TV?

A simple test is to open a image file on any device that has a browser, this link https://fgl27.github.io/smarttv-twitch/screenshot/controler.png

I can add a backup if one that provides similar features to github, that are free, easy to use and free and unlimited downloads quotas.

I don't have another one that if I public enable the use it will not hit the problem of downloads quotas.

Also there is the issue of what will work Belarus, makes no sense to me to try to find a solution that I can't test, so if you that seems to be there has a viable solution let me know with.

**Comment by RaTeNo** [comment]
tracert fgl27.github.io
 
  1     *        *        *     Превышен интервал ожидания для запроса.
  2     3 ms     4 ms     9 ms  100.83.0.1
  3     4 ms     3 ms     3 ms  93.84.80.153
  4     6 ms     6 ms     7 ms  10.0.61.69 [10.0.61.69]
  5    10 ms    11 ms    11 ms  core1.net.belpak.by [93.85.253.193]
  6    12 ms     7 ms     7 ms  ie1.net.belpak.by [93.85.80.38]
  7    15 ms    14 ms    13 ms  asbr9.net.belpak.by [93.85.80.238]
  8     *        *        *     Превышен интервал ожидания для запроса.
  9     *        *        *     Превышен интервал ожидания для запроса.
 10     *        *        *     Превышен интервал ожидания для запроса.


The problem is not in the TV, it is one provider that is blocked

**Comment by fgl27** [comment]
Yes the government isn't allowing it.

If you have a hosting solution that you wanna share let me know.

**Comment by RaTeNo** [comment]
Cloudflare  DNS solved the problem

1.1.1.1
1.0.0.1
