### ISSUE TITLE
android-like chat

### ISSUE THREAD

**Issue by Ken-nya** [fgl27/smarttv-twitch#168]
Hello, this is my first message. In the android app, the chat is located to the right of the video. And in this application, the chat is located on top of the video in different positions. Is it possible to do as on Android, so that the video is on the left, and the chat is on the right?

**Comment by fgl27** [comment]
Yes click on the player control option "video mode"

**Comment by Ken-nya** [comment]
Thanks. It was stupid. I clicked on the video mod, but nothing changed during playback. And now I clicked and restarted the video, and everything became normal. Next time I'll be more careful, so as not to make a mistake. :)
