### ISSUE TITLE
I can't watch the stream

### ISSUE THREAD

**Issue by saltyga** [fgl27/smarttv-twitch#169]
does not play video. stream or clip. writes the ended channel. I enter the authorization code, always an error. help me please.

**Comment by saltyga** [comment]
43" Crystal UHD 4K Smart TV TU7097 Series 7

**Comment by fgl27** [comment]
App is working fine, you have s local issue.

Last person they had this fix it by using Google DNS in the device or router

**Comment by saltyga** [comment]
configured Google DNS. the problem did not go away ((if anyone had such a problem, please help

**Comment by fgl27** [comment]
Have you ever use the app before and it worked?

Have you try to power off the device? remove it from the wall

this device sometimes just have odd issues.

**Comment by saltyga** [comment]
the application immediately had such a problem. via fork twitch works well. but the design is really not to my liking. I tried to turn off the TV. the application was reinstalled. nothing helps.

**Comment by fgl27** [comment]
Show me the about about of the app. side panel about take a picture... drag the picture to a post here

I need to be sure you install the correct zip

**Comment by saltyga** [comment]
![IMG_20210328_200331](https://user-images.githubusercontent.com/51962543/112760854-211f5280-9001-11eb-81f7-7acbe2b6bf1f.jpg)
![IMG_20210328_200256](https://user-images.githubusercontent.com/51962543/112760856-22507f80-9001-11eb-9c19-e3c2697d7c5f.jpg)
![IMG_20210328_200312](https://user-images.githubusercontent.com/51962543/112760857-22507f80-9001-11eb-8965-37aaf937b94f.jpg)

**Comment by fgl27** [comment]
The version is OK.

Install the app in debug mode... with is a similar process as ou did in here https://github.com/fgl27/smarttv-twitch#install-the-application ... but now you click on "Dee" as you see on the bellow image

![image](https://user-images.githubusercontent.com/13755892/112761920-e05d1480-8fd3-11eb-809e-217c6d2c89c0.png)


When it finishes installing will open on the computer a window from the default browser click on the console tab as on bellow image

![image](https://user-images.githubusercontent.com/13755892/112762033-287c3700-8fd4-11eb-8cbe-bd484b4d79b2.png)

Now open a live, a vod and a clip after share the a screen shot of the console window

**Comment by saltyga** [comment]
I installed from a third party source. automatic widget installer. TheDarkSmartTV. I don't even have the SDK installed. Do I need to install the program through the SDK now? i will reinstall, write the result. thanks

**Comment by fgl27** [comment]
If you don't is not possible to see what is going on.

I only recommend installing the app via tizen as is wrote on the main page if you didn't that can be the problem on the first place.

> Do I need to install the program through the SDK now?

If you wanna any more support if not just close the issue.

**Comment by fgl27** [comment]
And looking back to the image you shared before

![112760857-22507f80-9001-11eb-8965-37aaf937b94f](https://user-images.githubusercontent.com/13755892/112763539-3b463a00-8fdb-11eb-9333-d350b560b0b1.jpg)

**You aren't running the correct app version**

I have no idea what you are running a modification of the project or something

So if you just follow the proper installation process from the main page the app must work and you don't even need to debug anything.

**Comment by fgl27** [comment]
This is the correct vesrion that must show in about

![image](https://user-images.githubusercontent.com/13755892/112763647-b3acfb00-8fdb-11eb-83c0-eb1f45df28a7.png)

**Comment by saltyga** [comment]
installed via SDK. it turned out to be not difficult, I did it for the first time. everything works, plays, logged in. thanks for the help and great app. the question can be closed)))

**Comment by saltyga** [comment]
I'm happy)))
