### ISSUE TITLE
App down? Getting redirected to a browser link instead

### ISSUE THREAD

**Issue by Stroopf** [fgl27/smarttv-twitch#170]
Hi, 

My app has worked for the past half-year on the Samsung QA75Q90RAWXXY, and now when booting it instead of the app loading, I'm getting a link to https://fgl27.github.io/stamttv-twitch/release/firebase/index.html which is a blank page in my samsung tv browser unless and a 404 when I'm on my computer. Is the app down or something?

**Comment by fgl27** [comment]
very odd I don't know way that happens.

there is an page in side the app is

https://fgl27.github.io/smarttv-twitch/release/firebase/index.html

with is not a 404 so you must have a tipo there... that page must not open as a app is just a analytics link inside a iframe on the app...

So I have no idea what is causing it...

Can you debug the app?

**Comment by fgl27** [comment]
Install the app in debug mode... with is a similar process as you did in here https://github.com/fgl27/smarttv-twitch#install-the-application ... but now you click on "Debug as" see on the below image

![image](https://user-images.githubusercontent.com/13755892/112761920-e05d1480-8fd3-11eb-809e-217c6d2c89c0.png)


When it finishes installing will open on the computer a window from the default browser click on the console tab as on bellow image

![image](https://user-images.githubusercontent.com/13755892/112762033-287c3700-8fd4-11eb-8cbe-bd484b4d79b2.png)

**Comment by bitteL3BN** [comment]
same problem here. a few hours ago it was working. really dont want to reinstall it. dont get whats wrong there.

**Comment by bitteL3BN** [comment]
okay debug shows an empty page. but reinstalling it has worked. maybe the selfupdatefunction has crashed the app? dont care because i can watch twitch again now. thanks.

**Comment by Stroopf** [comment]
I won't be able to debug in a while ( perhaps til Friday ) but I just wanted to put the issue out there in case other people like BitteL3BN were having the same issue. But once I debug I'll let you know. Big fan of the app btw, great work!

**Comment by bitteL3BN** [comment]
okay i had to update the tizen tv extension from 5.5 to 6 with the tizen package manger. after this i was able to reinstall the app and now its working properly again. hopefully this will help anyone whos got the same problem.

**Comment by fgl27** [comment]
Close the app if the problem persist by holding return key, if that doesn't help power ff the TV by unplugging it from the wall.

If that doesn't resolve let me know.

**Comment by bitteL3BN** [comment]
all done but "smaller screen and chat" is still weird. when i click it the chat is on 100% (position 1) and the fullscreenpicture is just a few centimeters lower than before so that its cut off on the lower side and i get a black bar on the upper side.

**Comment by fgl27** [comment]
I don't get it open a separated issue and show me a image of the issue

**Comment by fgl27** [comment]
Will close this as is resolved, if anyone has a issue just open a new issue.

Thanks for the help
