### ISSUE TITLE
change video mode

### ISSUE THREAD

**Issue by bitteL3BN** [fgl27/smarttv-twitch#171]
![photo_2021-03-29_20-49-55](https://user-images.githubusercontent.com/81565486/112885129-a6be0380-90d0-11eb-9b22-879d58c6036c.jpg)
![photo_2021-03-29_20-50-00](https://user-images.githubusercontent.com/81565486/112885134-a9b8f400-90d0-11eb-9042-cd2e2f48457a.jpg)
![photo_2021-03-29_20-50-03](https://user-images.githubusercontent.com/81565486/112885140-ab82b780-90d0-11eb-8f32-d2364bc742fe.jpg)

I don't get it @bitteL3BN open a separated issue and show me a image of the issue

_Originally posted by @fgl27 in https://github.com/fgl27/smarttv-twitch/issues/170#issuecomment-809615907_

sorry for my bad english ill post a few pictures

**Comment by bitteL3BN** [comment]
ha, it works after changing to another channel. at first i have to change the video mode from fullscreen to smaller screen and chat, then it will look like the pictures above. but when i change to another channel it loads properly because i think this is how it should look right:

![photo_2021-03-29_21-00-56](https://user-images.githubusercontent.com/81565486/112886180-df121180-90d1-11eb-828b-c2123cb5edfa.jpg)
  
right?

**Comment by fgl27** [comment]
In not able to reproduce it, dreamwastaken works fine no matter what video mode.

Seems the TV has a issue.

Can you do that in debug move to see if there is a error?

**Comment by RevENGE-code** [comment]
Hey, I’ve encountered the same exact issue on my Samsung Tv. Sadly I am not able to enter the debug menu since I only own the "smart" Remote that came with the Tv. The "fix" that the OP suggest works, though you will need to do it everytime you would want to change the video mode. I've added picture for reference. Thanks for keeping this great application running! 
![Uploading 1D23E082-FA25-40F1-8802-B26B690A8F48.jpeg…]()

**Comment by fgl27** [comment]
You don't need use the remote to access debug menu you need a computer the same you use to instal the app.

Here is the how to debug .....

Install the app in debug mode... with is a similar process as you did in here https://github.com/fgl27/smarttv-twitch#install-the-application ... but now you click on "Debug as" see on the below image

![image](https://user-images.githubusercontent.com/13755892/112761920-e05d1480-8fd3-11eb-809e-217c6d2c89c0.png)


When it finishes installing will open on the computer a window from the default browser click on the console tab as on bellow image, wait at least 60 seconds before taking the screenshot

![image](https://user-images.githubusercontent.com/13755892/112762033-287c3700-8fd4-11eb-8cbe-bd484b4d79b2.png)

_Originally posted by @fgl27 in https://github.com/fgl27/smarttv-twitch/issues/170#issuecomment-809040884_

**Comment by fgl27** [comment]
On this case take a ss after some changes of video mode....

Test on livevods and clip

If needed take more then one screen shot

**Comment by fgl27** [comment]
A solution for this was found... Was a related issue of https://github.com/fgl27/smarttv-twitch/issues/160
