### ISSUE TITLE
Live feed short bug ?

### ISSUE THREAD

**Issue by eze92** [fgl27/smarttv-twitch#172]
I tried to use the live feed sort function by game A-Z, but I don't see it change the sort mode in which it shows games or am I misunderstanding the function?

**Comment by fgl27** [comment]
This app live feed doesn't have a game section

this is the android project https://github.com/fgl27/SmartTwitchTV that has it...

Do you wanna support for what?

in's possible anymore to do any game section sorting.

**Comment by eze92** [comment]
I was referring to this option that appears, I wanted to change the order in which the list of games appear and I do not see that it does anything

![IMG_20210415_075227](https://user-images.githubusercontent.com/8607217/114858624-1960fb80-9dc0-11eb-9efc-85299e5e6a60.jpg)
![IMG_20210415_075306](https://user-images.githubusercontent.com/8607217/114858637-1d8d1900-9dc0-11eb-95c1-e7fc4b2d1240.jpg)

**Comment by fgl27** [comment]
That will sort the list base on the game be played and works fine for me. Maybe all the channel's you followed and are live are playing the same game...

Show me the side panel live list not sorted and give me the username so I can test

**Comment by eze92** [comment]
So, does the filter / option apply to the channels that I follow and not with the games tab? Right ?

**Comment by fgl27** [comment]
Says there "side panel" and "live feed" that are this two things:

![Screenshot from 2021-04-15 15-14-28](https://user-images.githubusercontent.com/13755892/114918296-4da6dd00-9dfd-11eb-9b23-3a94003f9db5.png)

![Screenshot from 2021-04-15 15-14-21](https://user-images.githubusercontent.com/13755892/114918302-4ed80a00-9dfd-11eb-8ae2-39e5b5496efd.png)


Applies to noting else;

**Comment by eze92** [comment]
ok so i misunderstood its function.  hopefully at some point you can add sorting by games like android has
