### ISSUE TITLE
User icons (subscriber, mod, ...) are not shown anymore

### ISSUE THREAD

**Issue by reconman** [fgl27/smarttv-twitch#174]
**Describe the bug**
Recently the user icons in the chat got broken, instead of subscription and mod icons, it only indents the chat messages by the imaginary width of the icons. There are 3 different kinds of indentations depending on how many icons the users have: none, 1 icon width, and 2 icons width.

**To Reproduce**
1. Go to a live channel (preferably to a popular one so lots of users are active in the chat)
2. Enable the chat
3. Wait until subscribers post a chat message

**Expected behavior**
Subscription and mod icons should be shown again.

**Screenshots**
<img src="https://dl3.pushbulletusercontent.com/H2MddY1BrmUDpsRE5KaisniMaS2RBZFN/IMG_20210508_190345.jpg" height="500px" />

**Device:**
 - TV Model: UE40MU6179UXZG
 - Os version: Tizen 3.0

**Comment by fgl27** [comment]
All is fine for me.

If not for you try to reboot the device as this is probably a connection issued on your end.

**Comment by reconman** [comment]
Found the cause, pihole had `bades.twitch.tv` in its blacklist so any requests to that domain were blocked.
