### ISSUE TITLE
 some channels video or live does not start.

### ISSUE THREAD

**Issue by oxer1** [fgl27/smarttv-twitch#175]
It doesn't buffer when I enter to watch some channels. it does not show any errors, but the video or live stream does not start.

Can you try to watch any live stream or video of this channel?
https://www.twitch.tv/jahrein

I installed it again.I turned off the chat, lowered the video quality. I can fast forward in time but it still won't play video.
 I only have this problem with the 1-2 channels I watch.

 - OS: Windows Version 10
 
**Device:**
 - TV Model: Samsung UE 50MU7000
 - Os version [e.g. , Tizen 5.5]

**Comment by fgl27** [comment]
Is.a codec.issue and isn't on all videos, 8 of may and. Allow.works.
Those that don't only don't work using the source quality, 720p60 and bellow.works just fine.

I don't think there is a solution, the steamer must use a proud codec.

Tomorrow when I'm on a computer I'll check with codec is be used, then I update here
