### ISSUE TITLE
Some channels video or lives don't play on Source quality

### ISSUE THREAD

**Issue by fgl27** [fgl27/smarttv-twitch#176]
this is a issue that was reported by user **oxer1**, but for some reason they account is no longer active, because of that I believed they issue disappear, because of that I reopen it.

The problematic channel is https://www.twitch.tv/jahrein

I check and can't find the reason...

VODs newer then may 8 2021 of that channel, will not play when using the source quality, 720p60 and bellow works.

The stream is using 936p60 resolution/fps but that isn't the problem as others also use it and it doesn't cause a issue.

When I open the problematic stream on VLC to check the codec this is the result

![Screenshot from 2021-05-19 07-10-22](https://user-images.githubusercontent.com/13755892/118805984-ead1b700-b87c-11eb-8280-5e6a82629f22.png)

And the bellow is from the channel https://www.twitch.tv/rogue that is also using 936p60

![Screenshot from 2021-05-19 07-14-58](https://user-images.githubusercontent.com/13755892/118806090-0c32a300-b87d-11eb-9d58-0a2697192729.png)

Both steams are using the same res/fs/codec, player error reported in tizen is "UNKNOWN_ERROR_EVENT_FROM_PLAYER", because of that and that the a solution can't be found.

This issue ins't present on all Samsung TV only on some, maybe they update the firmware of defetect TV and the problem is solved.

If you have a similar issue post what channel has the issue, add as many info as possible to help.

**Comment by Mershl** [comment]
Had exactly this issue with a custom DNS (tested with Google 8.8.8.8 and cloudflare 1.1.1.1). Setting DNS manually on the SamsungTV to my ISPs DNS immediately fixes the issue for me. (Tested twice)

**Comment by fgl27** [comment]
inform to reopen if any news
