### ISSUE TITLE
Stream stuck every 10 mins since today

### ISSUE THREAD

**Issue by kwizatz88** [fgl27/smarttv-twitch#178]
I don't know if Twitch changed their ads implementation or what, but since tonight, streams get stuck every 10 mins and I have to exit and reload stream for it to work. In same time ppl are complaining of too many ads in chat. So I guess they try to load, which freezes my stream (tested on 2 TVs, same issue since tonight)

**Comment by fgl27** [comment]
Which stream?

**Comment by kwizatz88** [comment]
oh it was this one, but now it's over :
https://www.twitch.tv/dogdog

currently watching kripp and there isn't the issue indeed. Gonna update issue the next time dog streams

**Comment by fgl27** [comment]
No more issues?

**Comment by kwizatz88** [comment]
had a freeze tonight on same stream, but no on others, so not sure
you should probably close the issue, thx for help and for this great app

**Comment by fgl27** [comment]
OK, sometimes is just an bad connection....

Open another issue on the future if you wanna to discuss this or something else.
