### ISSUE TITLE
Live content dont work loading screen

### ISSUE THREAD

**Issue by hunesco** [fgl27/smarttv-twitch#179]
App works fine till some days ago. Now is rare some channel open. As you can see in video below, after click in channel I get a loading screen and a timeout.
https://streamable.com/jq5hzh

Any help?

**Comment by fgl27** [comment]
There is something wrong on yours internet connection.

Do you use any use any ad block on the network? If yes try to disable all.
Try a different dns.

**Comment by hunesco** [comment]
> There is something wrong on yours internet connection.
> 
> Do you use any use any ad block on the network? If yes try to disable all.
> Try a different dns.

My connection are wired, from my router to TV. I use adblock only at browser PC, this can be The problem? I already try with Google DNS and dont work also.

**Comment by fgl27** [comment]
I don't know then, I have the same TV running the same FW and all just works.

Try to reinstall the app, if that doesn't solve, run the app in debug mode open lives, vods and clips, share to me the result what works what doesn't and share an screenshot of the console window.

here is how to debug https://github.com/fgl27/smarttv-twitch/issues/104#issuecomment-610563192

**Comment by hunesco** [comment]
> I don't know then, I have the same TV running the same FW and all just works.
> 
> Try to reinstall the app, if that doesn't solve, run the app in debug mode open lives, vods and clips, share to me the result what works what doesn't and share an screenshot of the console window.
> 
> here is how to debug [#180 (comment)](https://github.com/fgl27/smarttv-twitch/issues/180#issuecomment-848332147)

I try set Google DNS and Cloudfare DNS on my router, but with both I still with the same problems... I will try remove and re-install tomorrow or saturday.

**Comment by hunesco** [comment]
Ok, I remove app from my tv and try reinstall, I am stucked in this
https://i.imgur.com/qpsQcHT.png
Any help?

**Comment by hunesco** [comment]
> Holding the mouse above the red ! you can see the cause...
> 
> You probably don't have tv-samsung version 5.5 installed, so select the one you have then select the "Name" and the app name "smattv-twitch"
> 
> ![Screenshot from 2021-05-28 07-55-22](https://user-images.githubusercontent.com/13755892/119973866-5e18ae80-bf8a-11eb-83b8-340ab0a5765d.png)
> 
> If that inst't it, you may have a project with the same name already, so remove it before import.

Yeah, the problem is I need delete this project to another one works.
Now I install app without any problem.
But...
Now I get only loading screen when try any live channel...
![1622239824098](https://user-images.githubusercontent.com/20172324/120046497-a961aa00-bfe8-11eb-9599-115b6fc68f0b.jpg)

**Comment by fgl27** [comment]
What about the result of the debug mode?

**Comment by hunesco** [comment]
> What about the result of the debug mode?

What I need do in debug mode? Open live channels, clips and vods?
ps: só descobri agora que vc é br também kkkk

**Comment by fgl27** [comment]
Isso abre dois de cada, e coloca aqui o resultado do console

**Comment by hunesco** [comment]
> > What about the result of the debug mode?
> 
> What I need do in debug mode? Open live channels, clips and vods?
> ps: só descobri agora que vc é br também kkkk

A página gerada no debug aparece toda em branco, sem as opções de console e etc.
https://i.imgur.com/3bl5rIO.png
Me ajuda com mais essa por favor xD.

**Comment by fgl27** [comment]
O problema talvez seja o browser, o Tizen usa o browser default do computador para abrir esta janela, eu uso sempre o chrome outros eu não recomendo.

Também tu tem de confirmar na TV, apertando a tecla OK.

TU pode arrastar imagens para um comentário aqui no github que aparece direto no comentário

**Comment by hunesco** [comment]
O problema está no meu roteador, conectei a tv no wifi do vizinho e no 4g do celular e o programa rodou de boa os canais ao vivo, infelizmente tanto no meu desktop como em um notebook eu não consigo fazer a pagina de debug mostrar alguma coisa, sempre fica nessa tela em branco como na imagem acima.
Depois vou ver com o provedor de internet a possibilidade de fazer uma reinstalação do zero desse meu roteador.

Obrigado pela ajuda, se tiver mais alguma possível solução para mexer no roteador, me avisa.

**Comment by hunesco** [comment]
Um fato que lembrei e que talvez tire um pouco da culpa do roteador é que no navegador da tv o site da twitch funciona sem nenhum problema, pena que não da para fazer login na conta (acho).

**Comment by manfredlift** [comment]
Same issue here. This happens only on some channels and some other channels work fine. On my laptop, I noticed for the channel which has the issue issue plays ads when opening the live stream, so it might be related to ads?

**Comment by fgl27** [comment]
@manfredlift this issue is related to a specific problem on the user network or TV

Just open a new issue and share the proper info about it as...
what are the problematic channels names plus a screenshot of the about of the app.

**Comment by ortega1cba** [comment]
@fgl27 Felipe,

Estou tendo alguns problemas de conexão e não estou conseguindo debugar direito com as informações do log(na função de debug app do tizen studio)
![chrome_hGNyyrrOGY](https://user-images.githubusercontent.com/19917918/158272967-fdada6ec-ae8e-42e4-905d-f992919e24a1.png)

**Comment by fgl27** [comment]
API/V5 e kraken foram desligadas, mas estás não são usadas pra carregar a live.

Teu problema deve ser DNS ou algo relacionado bloqueando acesso aos servidores da live

**Comment by fgl27** [comment]
de nada, é assim aqui tmb não tenho acesso, por isso acabei colocando um roteador após o do provedor para que em casos assim de DNS e afins eu posso alterar no meu.

se precisar avisa.

**Comment by fgl27** [comment]
close do to inactivity
