### ISSUE TITLE
After restarting the TV, the app is gone/deleted

### ISSUE THREAD

**Issue by DerSani1988** [fgl27/smarttv-twitch#18]
I managed to install the app by following the guide. The application works fine no issues until this point.

**After restarting the TV (turn OFF via red button and turn ON again):**
The App will be deleted from the TV. I've reinstalled multiple times, every try same result. 
Do you have any idea?

**Comment by fgl27** [comment]
This was informed on #11, is happening to some TVs after Samsung remove all Twitch apps from they platform in request of Twitch.

![Screenshot from 2019-04-26 10-43-56](https://user-images.githubusercontent.com/13755892/56923088-1455f500-6aa0-11e9-9e94-01fb4153dae4.png)

After that it seems Samsung mess something up only for some TVs as my and most is fine.

**So @DerSani1988 and anyone else with this issue, need to share the TV information, that is shows in the about of the app (Red or A key then click in about)
Share the information, for Tizen  version, TV  and FW**

This way is possible to inform samsung about it, but they today aren't accepting any issue from none partners, to be a partner one must have a app released on they Tizen platform (A thing I don't have) and after the app is approved and released one can apply for partner (A thing I'm not).

As I can't do that (unless I make a dummy app and released there, a thing that I don't have the time to and may fail) I don't have any tool to inform Samsung about the issue.

But if some one has a way or in the future the status to inform things change, if we have the information of problematic TVs we can inform, so share the info and let's hope we can find a solution ir get help from samsung.

**Comment by cremvursti** [comment]
40JU6000, Tizen 2.3 FW 1530

**Comment by ashxvx** [comment]
This may be slightly off-topic. 

Before the old RU twitch app was deleted from my TV I was a running a DNS blocklist through my router on my network. Two days ago as soon as I disabled it the RU twitch app was locked with the deleted prompt. I also force my TV to use the routers DNS through iptables prerouting, since it's hardcoded to Google's DNS regardless of manual configuration in the TV. 

I was able to successfully install your app yesterday (thank you). Will continue to keep running the DNS blocklist as it appears one of the hosts is used to verify running apps and block them on the TV.

**Comment by DerSani1988** [comment]
Hey, would you share the blocklist you are using?

ashxvx <notifications@github.com> schrieb am Do., 2. Mai 2019, 09:05:

**Comment by cremvursti** [comment]
@ashxvx I tried [this](https://github.com/nikitakatchik/smarttv-twitch/issues/53#issuecomment-306070318) list but it didn't prevent the app from getting uninstalled

**Comment by DerSani1988** [comment]
@ashxvx  Thank you for the hint regarding DNS blocklist, the three lists i found do not prevent uninstalling, maybe you're able to share your blocklist?
@cremvursti used a different lists (specific for Samsung TVs) and not prevented uninstalling too.

**Comment by DerSani1988** [comment]
@fgl27 the delaits you're asking for:
SamartTV Twitch
Tizen Version: 2.3 | TV: UJ6200 | FW: T-HKMFDEUC-1530.1

**Comment by ashxvx** [comment]
https://raw.githubusercontent.com/ashxvx/SamsungTV/master/list2

Consider these points as this may not be effective for you: 
- My NU8000 spams google dns 8.8.8.8 (hardcoded) regardless of what your DNS is set to in your tv settings, I've blocked it in my firewall. Use quad 9 instead and DoT.
- My router forces all clients DNS requests to the router regardless of what it is set to in the DNS request packets. This prevents Samsung circumventing any filtering policies. 

Samsung can easily bypass your DNS blocking policies by using a hardcoded DNS, hence why I mentioned the methods above. 

I've had the app installed for 20 hours or so now, no removals/deletions during multiple power cycles in this time. 

Also, note the app store may not be fully functional; not a solution for everybody.

**Comment by fgl27** [comment]
This is the date Samsung terminate my app, but my was never released was plane to be released and never did, as they never allow me to change wherever twitch didn't like, I assume the "twitchtv" word in app name, and the twitch icon in about and app icon, things that can and was easily removed but they didn't care.

![Screenshot from 2019-05-02 08-39-13](https://user-images.githubusercontent.com/13755892/57072950-d92d0f00-6cb5-11e9-9ab8-23184c1d187b.png)

I thought that only old TV was affected by this bug, as previously only Tizen 2.3 tvs reported it.

Maybe this dns is a solution if works or not, anyone that tryes it let us know, so we can have more info about to help resolve this.

**Comment by ashxvx** [comment]
fgl27  Thank you for your development, time and contribution.

**Comment by DerSani1988** [comment]
@ashxvx If I'm using your list, the app will be installed (and it seems to stay after power cycles) but can't start the app only get blackscreen. Any solution?

**Comment by fgl27** [comment]
It seems you lost access to more then you try to.

When the app open it will load this file:
https://fgl27.github.io/smarttv-twitch/release/githubio/js/master.js

If that fail you get a black screen, so can you open that file on the network that the TV is?
If not try to fix it, 

After that file load you must access the Twitch api links as this:
https://clips.twitch.tv/api/v2/clips/TriumphantCulturedBatBuddhaBar/status

So test those if they work on the network they also must on the TV. 

There is more twitch links so if you get a loading error on the screen:
> Connection failed, unable to load content hit refresh to try again

You need to enable more things as https://api.twitch.tv/kraken/

**Comment by DerSani1988** [comment]
@fgl27 Maybe I found a workaround. I've tried the blocklist from @ashxvx in sets and if this set was added to my routers blocklist, the app right now after 10+ power cycles stay on TV and is working:

> samsungqbe.com
> samsungrm.net
> sca.samsung.com
> sso.internetat.tv
> syncplusconfig.s3.amazonaws.com
> syncplusconfig.s3.amazonaws.com
> syndicationfeeds.swm.digital
> targeted-config-test.samsungacr.com
> targeted-config-test.samsungacr.com
> test.samsungrm.net
> upu.samsungelectronics.com

Maybe this helps someone else. I've nearly the complete list in my router excepting the following (this might cause the blackscreen of doom):

> us-api.samsungyosemite.com
> vas.samsungapps.com
> vd.contents.prod.eu.s3.amazonaws.com
> vd.emp.prd.s3.amazonaws.com
> vdterms.samsungcloudsolution.com
> www.samsungotn.net
> www.samsungrm.net
> www.samsungrm.net
> xpu.samsungelectronics.com

@ashxvx  Thanks for sharing your list with us. Maybe, if more users can confirm, a little fix above can prevent further errors

@fgl27  Offtopic: First of all thank you for your nice work, I love your app. Second, the only thing that is irritating me is the font, is it possible to change to one font without a shadow? :). Last but not least, i'll add a translation soon :)

**Comment by fgl27** [comment]
@DerSani1988 I don't get it 

>  font without a shadow

Can you show me?
open a separated issue and paste a picture or a screenshot of the part you wanna to be different explain the reason why.

to take a screen shot install the repo
https://github.com/fgl27/smarttv-twitch/archive/master.zip
that version doesn't update it self but also will not erase the version you already have installed
So install it making a project, and don't install as says in the readme, install it by click on the ladybug icon in tizen, after the app open it will also open a page in the pc navigate to **"Rendering and debug"** and click on  **"Frame capture"** and save the frame as on the pc... you can click and take multiple screen shots and save one by one on the pc.

this
![Screenshot from 2019-05-02 19-46-25](https://user-images.githubusercontent.com/13755892/57111562-052aad80-6d13-11e9-9dc5-cfb0d5c9a2fc.png)

that is how the app looks on my tv may look different on yours for some reason and the screen shot can help to understand way.

**Comment by ashxvx** [comment]
@DerSani1988 Updated: removed the exceptions you suggested. Also, whitelisted hub.samsungapps.com, app store is fully functional for me now.

**Comment by DerSani1988** [comment]
@fgl27  I've tried as mentioned before and can't run debug mode, following error occurs every time:

> Launching the Tizen application...
>  If you want to see the detailed information,
> please set the logging level to DEBUG in Preferences and check the log file in 'C:\tizen-studio\data\ide\logs/ide-20190503_134651.log'.
> 
> [Initializing the launch environment...]
>     RDS: Off
>     Target information: UJ6200
>     Application information: Id(flbtxFhd64.SmartTV), Package Name(flbtxFhd64), Project Name(zBasicUI)
> [Transferring the package...]
>     Transferred the package: wgt stream -> /opt/usr/apps/tmp/zBasicUI.wgt
> [Uninstalling the package...]
>     An exception occurred
> (Uninstalling the package... > Fail)
> An exception occurred
> Unexpected stop progress...
> (2.842 sec)](url)

Regarding why I'm suggesting change of the font: It's hard to read from a mid range distance. I've added a photo maybe you see what i mean: 

![tv](https://user-images.githubusercontent.com/25698122/57136468-45d70500-6dad-11e9-9083-2ec4ef501866.jpg)

Kindly note: On your screenshot it looks like Arial, and on my TV it looks like a crazy font.

@ashxvx Thanks for your update. I appreciate your work :)

**Comment by Xynetha** [comment]
> 
> 
> @fgl27 Maybe I found a workaround. I've tried the blocklist from @ashxvx in sets and if this set was added to my routers blocklist, the app right now after 10+ power cycles stay on TV and is working:
> 
> > samsungqbe.com
> > samsungrm.net
> > sca.samsung.com
> > sso.internetat.tv
> > syncplusconfig.s3.amazonaws.com
> > syncplusconfig.s3.amazonaws.com
> > syndicationfeeds.swm.digital
> > targeted-config-test.samsungacr.com
> > targeted-config-test.samsungacr.com
> > test.samsungrm.net
> > upu.samsungelectronics.com
>

Thanks, using this first list with OpenDNS seems to be working for me.

**Comment by itspeaky** [comment]
Any way to work around this without using OpenDNS or having a blocklist on the router page?
My router is pretty shitty and doesnt seem to let me change DNS or make any blocklist. Tried blocking the urls with parental control on the router but doesnt work.

**Comment by ashxvx** [comment]
@Xynetha update: it's down to two domains If you prefer the minimum blocking possible. 

samsungrm.net
samsungacr.com

So far it's working for me after 20+ long power cycles. 

Other hosts that are blocked from my other inbuilt lists (not related to this samsung list directly) 

ads.samsungads.com


Side note: gpm.samsungqbe.com   appears to block out your authentication for the app store.

**Comment by Flooo1337** [comment]
I just added the sites to my blocklist in my router and the app works perfectly.
The only problem ist now, that i cant play any video from netflix. it reaches 25% and then it cancels.
How can i fix it?

**Comment by fgl27** [comment]
@Flooo1337 
that seems not related as there is only samsung domains on the list at least the last list on two tree post above, and no one before had a issue like that as you can read to the issue posts...

So try to see if allowing all domains back fixes it, then if yes go and remove one by one and find what is the bad one, and share here so we know.

Sometimes is a random issue that resolves after rebooting the router and or the TV.

**Comment by Flooo1337** [comment]
Ok, i think i fixed the problem. 
I just cant block "samsungrm.net" and "ads.samsungads.com"
I found the solution, that i only can block these sites:

> samsungacr.com
> samsungqbe.com
> sca.samsung.com
> sso.internetat.tv
> syncplusconfig.s3.amazonaws.com
> targeted-config-test.samsungacr.com
> test.samsungrm.net
> upu.samsungelectronics.com
> syndicationfeeds.swm.digital

Twitch doesnt delete after 10 reboots and Netflix works perfectly aswell.

My Setup was:
Samsung UE48JU6050
Fritzbox 7590

**Comment by ashxvx** [comment]
@Flooo1337  The minimum summarised domain entries that work are these two: 

samsungrm.net
samsungacr.com

Ash
