### ISSUE TITLE
Connection failed, unable to load content

### ISSUE THREAD

**Issue by Vladutu** [fgl27/smarttv-twitch#182]
Hello,

Starting this morning, I'm getting "Connection failed, unable to load content. Hit refresh to try again" for live, games, video,clips, etc. I tried restarting tv and reconnecting to the network, but I get the same error. I do have internet as youtube, for example, works fine. I'm connected to wifi

Something that changed this morning is that my internet provider came and upgraded my old ONT. The old ONT ran in bridge mode and i had a separate router for wifi and LAN. Now both are active and the router is in DHCP mode and I'm still connected to the router. The wifi signal doesn't reach from the ONT.

**Device:**
 - TV Model: UE55MU602
 - Os version: tizen 3.0
 - app version: 4.0.1 may 19 2021

**Comment by Ocramsretep** [comment]
For me it works again

**Comment by Vladutu** [comment]
It might be a twitch issue as I see that there is a maintenance on cloudflare (https://downdetector.com/)

**Comment by Vladutu** [comment]
Yes, it works now. I was a twitch issue. I will close this issue.
