### ISSUE TITLE
Can't send chat messages. Chat stops scrolling after a while

### ISSUE THREAD

**Issue by kyzumi** [fgl27/smarttv-twitch#183]
**Describe the bug**
The "write to chat" feature appears to work but the message will not show up in the chat. chat stops scrolling after a few seconds. this error appear on chat sometimes: "ChatSed: Websocket closed remotely... {"isTrusted":true} 

**To Reproduce**

I click "ok" on my controller. Bottom options appear. I click on "write to chat". chat writing options appear on top. I write message and click "send" and nothing happens

**Expected behavior**

I expect chat to scroll and my messages to appear upon sending a message.

**Device:**
 - TV Model: Samsung 55ru7100

**Additional context**

It appeared to be working the first few days I used it!

**Comment by fgl27** [comment]
My 7100 TV doesn't have this issue.

**Comment by kyzumi** [comment]
Ok, I've changed from video mode to full screen mode and the chat scrolling seems to be fixed. I still can't send messages in chat though. The message seems to go through fine (no error message) but it just won't appear in chat

**Comment by fgl27** [comment]
If you don't see it, and the chat is receiving new message yours message wasn't send.

Change from full to side by side changes noting to the chat working or not.

**Comment by fgl27** [comment]
You can open the app o a computer using this link https://fgl27.github.io/SmartTwitchTV/app/index.html

Add yours user and key so you can write to chat, and test to see if on the same network on a computer you have a issue

On a computer no video will be played, is just for testing the user interface.

Pressing F12 and clicking on the console tab show all the app logs

![Screenshot from 2021-06-12 15-21-47](https://user-images.githubusercontent.com/13755892/121785745-05543300-cb92-11eb-8c51-0d35ad45e51d.png)

**Comment by kyzumi** [comment]
você é brasileiro também né? vou escrever em português então. eu tentei abrir aqui no pc e depois de autorizar a key no site do twitch, aparece uma janela dizendo que você tá saindo do site do twitch e quando volto pro github tem um erro 404. vou colar ele aqui:

404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

**Comment by fgl27** [comment]
O site que gera a chave é este:

https://fgl27.github.io/smarttv-twitch/release/githubio/login/twitch.html

Se da algum problem pra ti tenta em outro browser desliga bloqueio de propagandas e anuncios coisas assim pois pra min funciona perfeito.

Eu gero a chave copio e colo no aplicativo de boa.

**Comment by kyzumi** [comment]
Ok, no https://fgl27.github.io/SmartTwitchTV/app/index.html o chat funciona! e agora? tanto a TV quanto o computador estão conectados por cabo na mesma rede.

**Comment by fgl27** [comment]
A TV tem algum problema. Eu não seu qual ou como resolver.

**Comment by kyzumi** [comment]
Ok, obrigado pela ajuda!

**Comment by fgl27** [comment]
OK, se tu achar uma solução posta aqui.

Vou deixar este aberto como refrerencia.
