### ISSUE TITLE
Feature request: 7tv.app emotes!

### ISSUE THREAD

**Issue by Zatsando** [fgl27/smarttv-twitch#184]
The 7tv emotes are new in the twitch chat meta and have a big variety of brand new emotes. Many big streamers are currently using it, so I though it would be a great addition for the smart tv app!

**Comment by fgl27** [comment]
Thanks I take a look

**Comment by fgl27** [comment]
this feature was added, if the app is open close the app and reopen it so it can update

![Screenshot from 2021-06-22 16-54-29](https://user-images.githubusercontent.com/13755892/122990696-a0ab8c00-d37a-11eb-9810-df5c7571096e.png)
