### ISSUE TITLE
Audio compressor on player

### ISSUE THREAD

**Issue by coin-be** [fgl27/smarttv-twitch#185]
Hey,

I'd like to suggest the audio compressor feature just like BTTV adds on the default twitch player, is it possible?

![image](https://user-images.githubusercontent.com/80531511/124159586-535da780-da69-11eb-8baf-43dd596380cf.png)

Thanks.

**Comment by fgl27** [comment]
Samsung OS is very limited this feature can't be added to it.

Thanks
