### ISSUE TITLE
https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V8/4.0.1_V9.zip not found

### ISSUE THREAD

**Issue by Tatuunka** [fgl27/smarttv-twitch#186]
https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V8/4.0.1_V9.zip 

is "not found"

**Comment by fgl27** [comment]
thanks the link is 

https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V9/4.0.1_V9.zip
