### ISSUE TITLE
Stream is not loading

### ISSUE THREAD

**Issue by Miishale** [fgl27/smarttv-twitch#187]
**Describe the bug**
I installed the App with Version 4.0.1V8 (first) and 4.0.1V9 (after V8 did not work, uninstalled V8 before installing V9) on my Samsung TV UE55MU6170 as described in the read me and the installation worked without problems. I also can authorise the app and all my followed channels are displayed correctly. But when I want to start a stream, there is just a black screen with an infinite loading symbol. With version V8 the loading screen stopped after a while with the message that the stream has ended (it hasn't really), with V9 it just loads eternally.
I also tried to debug it, but there was nothing shown in the debug window of the tizen studio. Some other user hat that problem too in 2016, and he got it running when he logged of the TV and logged in once more. I also tried that, but it did not work for me.

Unfortunately I can't debug the application, because the debug windows just stays white...

**To Reproduce**
1.  Install the app
2. start the app
3. klick on a stream

**Expected behavior**
stream starts

**Device:**
 - TV Model: UE55MU6170 
 - Os version 1290

**Comment by fgl27** [comment]
If you can't even debug properly your TV of network has a issue that has noting to do with the app.

Check other issues as there is a few like that to see if any help.

If find something or have a question let me know.
