### ISSUE TITLE
My own channel emotes are missing from the emotes menu

### ISSUE THREAD

**Issue by GForceWeb** [fgl27/smarttv-twitch#189]
**Describe the bug**
The Twitch emotes menu does not include twitch emotes from my own channel. It works fine for all the other channels I'm subbed to but as I'm also a streamer I have my own emotes that don't show up.

**To Reproduce**
Might be hard to reproduce if you're not a streamer with your own emotes but happy to help test and resolve. Hopefully it's a fairly simple fix to check for emotes from the users own channel

**Comment by fgl27** [comment]
Twitch api issue, they don't support the third party emote api anymore. I can't fixe it.
