### ISSUE TITLE
[Feedback] It can be installed from mac

### ISSUE THREAD

**Issue by Stanko** [fgl27/smarttv-twitch#19]
Hey there,
First I want to thank you for making and maintaining this app!

Also I want to let you that I successfully installed it using Tizen Studio for Mac. I just followed your instructions, and got it running in 20ish minutes. 

Version of my system
> macOS Mojave 10.14.4

I guess you can add it to the readme.

Cheers and tahnk you!

**Comment by fgl27** [comment]
Thank you, that is good to know, I'll update later.
