### ISSUE TITLE
HDMI ARC doesn't work

### ISSUE THREAD

**Issue by jfo84** [fgl27/smarttv-twitch#195]
**Describe the bug**

When running the app on a Samsung TU8300 with the latest version installed, audio via ARC HDMI does not work. It works on the home screen/in general and all first-party apps, but it does not with this setup. If I unplug the speaker, the audio starts to work.

**Expected behavior**

I expect the sound to work. I have HDMI ARC correctly configured on the settings page as an HDMI receiver with ARC on "Auto" mode.

**Device:**
 - UN65AU8000FXZA, 2021 Model
 - I'm not sure. It says version 1805

**Comment by jfo84** [comment]
The app is generally really great though. If you have any idea what could be causing the issue I would love to hear. Cheers

**Comment by fgl27** [comment]
I have no idea why this happens.

Can't test here I don't have any Arc enable devices.

**Comment by jfo84** [comment]
@fgl27 I've written a lot of JS, I can probably figure it out. Do you have any idea where to look in the code?

**Comment by fgl27** [comment]
No this is probably not fixeble a security thing against third party apps prevents the audio 

Try Samsung documentation for tizen see if they're is any thing about your issue
