### ISSUE TITLE
Black Screen after loading app.

### ISSUE THREAD

**Issue by kyzumi** [fgl27/smarttv-twitch#197]
App worked fine for a few months but suddenly stopped it. It loads for a few seconds then a very small part of the left menu blinks for a split second and then a blue e-mail appears on the center of the screen for 2 seconds (e-mail is similar to flgflg @ gmail.com). After that it is just Black Screen!

I recorded a video if you want

**Comment by fgl27** [comment]
No need a video, this is not something that can be replicated, is just a odd bug.

To fix just hold the channel key up for 10 seconds until you see a warning, let you know to hold key down for the same...

Then a confirmation that the app will be restarted... if after that the app doesn't work you will have to manually reinstall it.

**Comment by kyzumi** [comment]
What do you mean by holding the channel key? my TV is Samsung RU7100 55

**Comment by fgl27** [comment]
The channel key of the remote up or down. When the app is open and unresponsive

**Comment by fgl27** [comment]
![image](https://user-images.githubusercontent.com/13755892/142768878-f0c4ceaf-dd69-45e8-8a53-d4a079a06873.png)

**Comment by fgl27** [comment]
This is on there app controlled... Force erase all app config...

![image](https://user-images.githubusercontent.com/13755892/142769033-239c6cc0-5ebb-4fff-9699-502dfbf266d9.png)

**Comment by kyzumi** [comment]
I did it and it worked a few times but sometimes I can't get it to work. I just reinstalled the from scratch and I am getting the same problem : /

**Comment by fgl27** [comment]
I can't reproduce the black screen issue.

If you can share the exactly steps do to so.

This is probably related something you change how you use the app, share exactly what is that you do, so I can reproduce and fix.

**Comment by kyzumi** [comment]
Ok, I reinstalled and it seems to be working but I have to reset it using the channel key everytime.

**Comment by kyzumi** [comment]
Ok, I think I fixed it. Issue was my DNS. I had recently tried one of those ad blocking DNS on my router. Reverted it back to the google one and the app worked fine. Sorry about that!
