### ISSUE TITLE
Can't interact with User screen on NU8000

### ISSUE THREAD

**Issue by tjgeorgen** [fgl27/smarttv-twitch#2]
I'm using a 2018 Samsung NU8000. When I go to the "User" screen, I see the box asking me to "Type your user name..." but I cannot interact with it. The program also seems to freeze and none of the controls work except for hitting the return/back arrow.

Thank you so much for all of your hard work on this app! I look forward to using it.

**Comment by tjgeorgen** [comment]
I think it has the same issue on the Search page as well, so it may have to do with entering text.

**Comment by fgl27** [comment]
I going need you to install the application using the repo link and not the release
https://github.com/fgl27/smarttv-twitch/archive/master.zip

The process is the same you just create another app in Tizen, and use the repo as **File System**.
And to install the app you click in "Debug as" to install the app with debug enable...

It will open a new window from yours browser on the computer and in there the log will be showed...

After you press OK in the app screen to enable the logging don't change the screen stay in "Live", go to the console window in the computer, and press the key B or green, this will force the app to reload and show some information in the screen something like this

![screenshot from 2018-11-28 13-43-52](https://user-images.githubusercontent.com/13755892/49163275-dd728c00-f313-11e8-9105-f58a9cc2084d.png)

After you see those logs try to add a user.

I only update the add user section to

**Comment by tjgeorgen** [comment]
Looks like a problem with the addEventListener function on AddUser.js

`index.html:1 Failed to decode downloaded font: https://fgl27.github.io/smarttv-twitch/release/githubio/css/fonts/BabelStoneHan.woff
index.html:1 OTS parsing error: glyf: uncompressed length exceeds 30MB
Main.js:184 language is en_US
Screens.js:6 InitScreens place holder
VM224:1 Entering setDisplayRect
VM224:1 adding listener
VM224:1 Entered AVPlayManager.prepareAsync()
webapis.min.js:1 [productinfo.js] isUDPanelSupported  begin
webapis.min.js:1 [productinfo.js] isUDPanelSupported  end [object Object]
webapis.min.js:1 [productinfo.js] isUDPanelSupported message data true
webapis.min.js:1 [productinfo.js] getFirmware  begin
webapis.min.js:1 [productinfo.js] getFirmware  end [object Object]
webapis.min.js:1 [productinfo.js] getFirmware message data T-KTM2AKUC-1153.1
webapis.min.js:1 [productinfo.js] getModel  begin
webapis.min.js:1 [productinfo.js] getModel  end [object Object]
webapis.min.js:1 [productinfo.js] getModel message data UNU8000
Main.js:728 Tizen Version: 4.0 | TV: UNU8000 | FW: T-KTM2AKUC-1153.1
webapis.min.js:1 [network.js] addNetworkStateChangeListener  success
webapis.min.js:1 [network.js] listenerId 0
AddUser.js:12 AddUser_init
AddUser.js:80 AddUser_inputFocus
AddUser.js:96 AddUser_addEventListener
AddUser.js:84 Uncaught TypeError: Failed to execute 'addEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at AddUser_inputFocus (AddUser.js:84)
    at AddUser_init (AddUser.js:18)
    at Main_SwitchScreen (Main.js:559)
    at HTMLBodyElement.Live_handleKeyDown (Live.js:471)
AddUser_inputFocus @ AddUser.js:84
AddUser_init @ AddUser.js:18
Main_SwitchScreen @ Main.js:559
Live_handleKeyDown @ Live.js:471
SmartHub.js:40 Cannot read property 'setPreviewData' of undefined`

**Comment by fgl27** [comment]
OK I understand.

Try the release app again and tell me the result, it must remaining installed if you didn't remove it.

The version in about (key A or red, and click in about) must show **4.0.1.120218**.

**Comment by fgl27** [comment]
You welcome, enjoy it.

If needed open another issue...
