### ISSUE TITLE
Avoid delay when loading a live stream

### ISSUE THREAD

**Issue by reconman** [fgl27/smarttv-twitch#200]
**Is your feature request related to a problem? Please describe.**
If I watch a stream with low latency, I always see 4 seconds of a loading icon while the video stands still on the first frame.

After that, the stream will resume from the buffered frane, not from the current one, so the stream is 4 seconds behind.

I could be wrong with my analysis.

**Describe the solution you'd like**
You should be able to watch the live stream without that delay or a way to synchronize the stream.

**Describe alternatives you've considered**

**Additional context**

**Comment by fgl27** [comment]
Samsung tvs are very limited and don't support what you wanna, low latency on Samsung tv is a workaround not something the player supports. 

If you enable low latency you will be 2 to 5 seconds behind, if you don't 10 to 20.

The delay at start isn't possible to prevent, unless someday they add three proper low latency support.

**Comment by reconman** [comment]
I installed the app on my fire stick and can use lowest latency, will use that in the future.
