### ISSUE TITLE
Following no longer works

### ISSUE THREAD

**Issue by Hellhound316** [fgl27/smarttv-twitch#201]
App Version :4.0.1 May 19,2021
Tizen Version: 5.5
TV: Samsung QTQ60
FW:T-NKLAKUC-2101.0

Not sure if this is fixable or not?

The app gives an error message 
Third-party Apps can no longer Follow/unfollow channels.

**Comment by fgl27** [comment]
That is it. There is no support, Twitch doesn't allow
