### ISSUE TITLE
Issue when "Running as Tizen Web Application" - Samsung TV Twitch app

### ISSUE THREAD

**Issue by Flaw98** [fgl27/smarttv-twitch#205]
Hello guys, 

Recently got my Twitch app erased (by accident) and tried to reinstall it using the same method, all is smooth until I try to run as Tizen Web App and install the extracted files:

Mentioning that I've both used Tizen and Samsung Certificate, any ideas?

TIA!

![image](https://user-images.githubusercontent.com/15834737/151787493-33f25795-9d56-4675-a065-8741ba67b06d.png)

**Comment by fgl27** [comment]
Have you checked this https://github.com/fgl27/smarttv-twitch/blob/master/release/githubio/etc/README.md ?

If the Tizen certificate doesn't work, the Samsung one may need extra steps.

If all doesn't work try a full reinstall of Tizen, by uninstalling it and reinstalling plus app extensions and etc related.

**Comment by Flaw98** [comment]
@fgl27 thanks a lot, worked finally.
