### ISSUE TITLE
The app on TV no longer loads video streams.

### ISSUE THREAD

**Issue by sonEdi** [fgl27/smarttv-twitch#206]
It's been a few days now that streaming video doesn't work on my **Samsung TV**.
I haven't made any changes to the TV, I haven't installed a VPN or changed DNS or anything else.
I think the software version is the latest and also opening the .index file in the source code on PC gives me the same problem.
Is this a known problem?

PS: I installed the APK on Fire TV Stick and there are no problems. The streams load perfectly.

Thanks.

**Operation system**
 - Version [4.0.1.May 19 2021]

**Device:**
 - TV Model: UMU6100
 - Os version [Tizen 3]

**Comment by fgl27** [comment]
You can't play streams on an PC using this app.

This is a network issues, maybe yours ISP change something a simple DNS change may cause this.

If the APK works on the same network the issues is on the TV what I don't know, both APK and Samsung app use the same links to load content.

**Comment by sonEdi** [comment]
You were right. The TV had custom DNSs that I didn't remember setting up.
Now it works again.

Thanks for your help!
