### ISSUE TITLE
Obfuscated code

### ISSUE THREAD

**Issue by ymebrugts** [fgl27/smarttv-twitch#21]
**Please Ignore this post. See the answer of the developer below.** 
<s>Hi Fgl27,

I was going through the project since I wanted to contribute to this project. Fix some bugs add some styling. That kind of thing. I'm enjoying it a lot, but I am very disturbed by the code I found. 

The code in master.js looks and is VERY obfuscated it is unreadable without weeks of study. I would like to know why it is this way. It does not make me comfortable at all that this code exists in this form. 

Obfuscating so much source code violates the GPL licence. It states: "The source code for a work means the preferred form of the work for making modifications to it."

So this certainly violates the intention of the GPL licence. Unless, I'm jumping the gun here?

Greetings,
MK</s>

**Comment by fgl27** [comment]
Do you know javascript? did you read the radme this part?
https://github.com/fgl27/smarttv-twitch#project-dependencies

> UglifyJS - is a JavaScript parser, minifier, compressor and beautifier toolkit

the code is in the [app folder](https://github.com/fgl27/smarttv-twitch/tree/master/app), and is compressed to the master.js file, all the js code from app folder and the html is compressed there

this does the preparation/compression and a lot more
https://github.com/fgl27/smarttv-twitch/blob/master/release/release_maker.sh

I know is not very bad documented repo, but is a personal repo I did my self alone didn't expect anyone to really engage on it, rigth now I don't have time to documente.

So if you have any doubt please ask don't assume.

In web is usually like this, a source with a lot of files and in the end all is compressed to a one line file, this is how is done, just search the web about it and way it is done.

**Comment by ymebrugts** [comment]
Sorry for my tone in the original post. It was actually meant as a question but since it was late (4AM) I was not aware of the way it was phrased.

I do know how to program but I hadn't seen you use a compressor. Normally I see those kind of files in frameworks like Angular and such. So your answer makes sense to me.

In any case. I love the app! It's actually amazing that you continued to develop this for free since the original Twitch app was suddenly removed from the store last month.

**Comment by fgl27** [comment]
OK if you wanna to make changes to it, and wanna know how is very basic, just fork the rep, clone to local machine, import the repo as a file system, the same process you did to install the release.zip

And after you manage to install the app using the repo, you can make changes to the this [index.html](https://github.com/fgl27/smarttv-twitch/blob/master/index.html) the one from main folder, and to the js files in the app/ folder, it time you install the changes will be there, so when you have something good you can make a pull request, I check and if all ok merge and update the master.js file.

If you are in doubt about this process reopen the issue and post you doubt.
