### ISSUE TITLE
Key Authentication Issue

### ISSUE THREAD

**Issue by Ioakeimis** [fgl27/smarttv-twitch#210]
So today the following happened:

I start the app and everything worked fine except from my subscription page. That's the place where you are being showed the channels you follow that are currently online. It would say that it failed to load them. Refreshing the page showed the same message and would not fix the problem.
Since everything else worked fine I assumed that it had to do something with my account. 
I tried many things. 
In the end I just uninstalled the App, restarted the TV (by long pressing the power button) and then reinstalled the App.
Now my subscription page loads just like it did before but now there is a new problem. The authentication key does not work anymore. It just doesn't. I literally tried 10 times or even more, double checking that the key entered was correct. 
I suspect twitch has changed something in their API or something along those lines. Now I can use the App just like I did before but I can no longer follow/unfollow channels. So basically I can not authenticate my Account using the key. I tried generating new keys and reinstalling the app and restarting the TV. I have the decided to finally give up.

One last thing.  There is a bug when the authentication fails. If the authentication fails then it keeps popping up in front or behind the App after a few seconds, no matter where you currently are in the App. The easy fix is of course to just exit the App and start it again, then it goes away, untill you of course try to authenticte yourself again and it fails. Then you have to restart the app yet again.

I hope this helps and I really thank you and appreciate you for the time and effort you put into this project. God bless you!

**Comment by soapergem** [comment]
I came here to report the exact same problem. It seems something has changed with the way this app handles OAuth? What I ended up doing was not as drastic as uninstalling/reinstalling the app, but instead just removing my user from the settings page and adding it back (and generating a new authentication key). No matter how many times I try, the authentication key does not seem to be working.

I tried digging into the source code to see if I could try and recreate the precise web requests that this app makes under the hood, to see if I could reproduce things in Postman. However I must confess I am truly confused. It seems the call to authenticate is triggered [here](https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/AddCode.js#L142-L145). However, that references [two variables](https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/AddCode.js#L673-L674) (`AddCode_clientId` and `AddCode_client_secret`) representing the client ID and client secret - but the second variable doesn't even have a value, while the first one is decorated with a code comment telling you to get your own. While I clearly do remember generating an authentication key when I first installed this app, I most certainly do not recall ever needing to set up a Twitch client ID and client secret. So in other words, that's my long-winded way of saying, "WTF is this code doing? How does it even work?"

I'd like to help out but I find that code branch puzzling. So instead I just have to join the chorus here saying, "help, someone please fix this!"

**Comment by Cryptical1** [comment]
Absolutely love this app. Use it daily. I noticed the same issue for the first time tonight.

**Comment by fgl27** [comment]
This is another issue the app is now working for adding keys, I just added one

![Screenshot from 2022-02-10 23-48-08](https://user-images.githubusercontent.com/13755892/153530655-70d678e2-eb3b-4637-ad24-f11df3e66516.png)

I'll check that issue when the key fails to be added and the app loops in the future to prevent that issue.

**Comment by Ioakeimis** [comment]
These are great news to hear. Do we now need to download the project with the newly applied changes to the code and reinstall the app? Or do these changes take place automatically? In other words does the app update itself?

**Comment by fgl27** [comment]
Yes it does, no need to update unless the app shows a warning asking to update manualy.
