### ISSUE TITLE
"connection failed"

### ISSUE THREAD

**Issue by AngusGhoul** [fgl27/smarttv-twitch#214]
**Describe the bug**
Hey! I have this app 4 months ago without any problem. Today I can't use the app because i have this message "connection failed, unable to load content. Hit refresh to try again". My internet it's good, and with the problem, i put my stream in another app on my tv.

If is a installation issue screenshot any error or wherever related that is generated during the installation.

If is something that causes a issue when using the app share a log bellow link informs how to log this app

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

**To Reproduce**
4. See error something doesn't work
5. Share the log file as image or as txt drag and (drop to the issue text box)

**Expected behavior**

**Screenshots**
Whenever you can add screenshots/picture to help explain/show your problem.

**Operation system (if is a installation problem):**
 - OS: Windows, Linux or ...
 - Version [e.g. 10, 18.4, etc...]

**Device:**
 - TV Model: UN40KU6000H, EH5000 or ...
 - Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]

**Additional context**

**Comment by pi0ne3r** [comment]
I have the same problem, tried to re-install from branch up_api didn't help

**Comment by clemsonwaterski** [comment]
Same issue here. Tried erasing app config without success.

**Comment by PedroMRP** [comment]
probably is connected with #209

**Comment by clemsonwaterski** [comment]
@PedroMRP is correct. The v5 Twitch API that this application was using is going through a phased shutdown according to the following schedule.  #209 will be the thread you want to watch for updates.

`February 7, 2022 – 1-hour shutdown starting at 11:00am PDT
February 9, 2022 – 2-hour shutdown starting at 11:00am PDT
February 14, 2022 – 4-hour shutdown starting at 11:00am PDT
February 16, 2022 – 6-hour shutdown starting at 11:00am PDT
February 22, 2022 – 24-hour shutdown starting at 11:00am PDT
February 28, 2022 – v5 permanent shutdown`

@fgl27 Thanks for all you're doing for the community!

**Comment by NormalBear** [comment]
There is a link in #209 with details on when the old API is getting shutdown. It is currently down for 6 hours from 11amPDT. There will be another longer shutdown on the 22nd followed by it's permanent shutdown.

**Comment by AngusGhoul** [comment]
> @PedroMRP is correct. The v5 Twitch API that this application was using is going through a phased shutdown according to the following schedule. #209 will be the thread you want to watch for updates.
> 
> February 7, 2022 – 1-hour shutdown starting at 11:00am PDT February 9, 2022 – 2-hour shutdown starting at 11:00am PDT February 14, 2022 – 4-hour shutdown starting at 11:00am PDT February 16, 2022 – 6-hour shutdown starting at 11:00am PDT February 22, 2022 – 24-hour shutdown starting at 11:00am PDT February 28, 2022 – v5 permanent shutdown`
> 
> @fgl27 Thanks for all you're doing for the community!

So it's normal right? We should to wait? Thanks!!!

**Comment by AngusGhoul** [comment]
I don't understand so much, please explain me, i don't understand the post 209 :( the problem will be solved automatically or I need to do something? Thanks
 :(

**Comment by PedroMRP** [comment]
You just need to have patience and wait for @fgl27 to handle the situation! A new version of the app will be available when its ready!

**Comment by AngusGhoul** [comment]
> You just need to have patience and wait for @fgl27 to handle the situation! A new version of the app will be available when its ready!

Perfecttly, that k u so much <3 we will need to reinstall the app with Tizen right? Thanks for your job!!
