### ISSUE TITLE
Wrong link in "Twitch.TV authentication key" Image

### ISSUE THREAD

**Issue by pimverkerk** [fgl27/smarttv-twitch#215]
This [image](https://camo.githubusercontent.com/12eae32a1f4cb0e9e39edcc1b59cede870a876b83bbf9feb878e0ddd0b0e564b/68747470733a2f2f66676c32372e6769746875622e696f2f736d61727474762d7477697463682f73637265656e73686f742f4164645f6b6579322e706e67) in the "Twitch.TV authentication key" manual references to tiny.cc/twitchkeycode instead of tiny.cc/twitchkey.  It seems that not only is this link outdated, but is also highjacked by someone. 

So i would suggest recreating the image with the correct link and updating the manual.

Thanks.

**Comment by fgl27** [comment]
Thanks, I would suggest next time update the image via pull request, open source repo I'm not here to please anyone or everyone.

BTW the link is just not be used and tiny send to ads not highjacked.

**Comment by pimverkerk** [comment]
Thanks for fixing, I can make a PR next time.
