### ISSUE TITLE
Changing font of the app

### ISSUE THREAD

**Issue by DerSani1988** [fgl27/smarttv-twitch#22]
@fgl27  I've tried as mentioned before [here](https://github.com/fgl27/smarttv-twitch/issues/18#issuecomment-488859854) and can't run debug mode, following error occurs every time:

> Launching the Tizen application...
>  If you want to see the detailed information,
> please set the logging level to DEBUG in Preferences and check the log file in 'C:\tizen-studio\data\ide\logs/ide-20190503_134651.log'.
> 
> [Initializing the launch environment...]
>     RDS: Off
>     Target information: UJ6200
>     Application information: Id(flbtxFhd64.SmartTV), Package Name(flbtxFhd64), Project Name(zBasicUI)
> [Transferring the package...]
>     Transferred the package: wgt stream -> /opt/usr/apps/tmp/zBasicUI.wgt
> [Uninstalling the package...]
>     An exception occurred
> (Uninstalling the package... > Fail)
> An exception occurred
> Unexpected stop progress...
> (2.842 sec)](url)

Regarding why I'm suggesting change of the font: It's hard to read from a mid range distance. I've added a photo maybe you see what i mean: 

![tv](https://user-images.githubusercontent.com/25698122/57136468-45d70500-6dad-11e9-9083-2ec4ef501866.jpg)

Kindly note: On your screenshot it looks like Arial, and on my TV it looks like a crazy font.

**Comment by fgl27** [comment]
I change the app name, open "apps" app -> My apps navigate all to the right and uninstall the app manually.

The error 

> An exception occurred
> (Uninstalling the package... > Fail)

Will disappears after.

That apps looks terrible, that is the default font of the TV

As you can see what I see is very different.

![All](https://user-images.githubusercontent.com/13755892/57139743-6f336900-6d8c-11e9-8dc4-77ccf2200862.png)

The default font is "sans-serif" normal size, but it may look odd like that I will try to find a good font that looks OK here and override the default. 

I share a zip with a new font when I have it.

**Comment by fgl27** [comment]
Here is the change that allows you for example to test a font
https://github.com/fgl27/smarttv-twitch/commit/163ecf50180ad530baff81cedb43566602862ae6

Need to copy the folder from **/release/githubio/css** to **css_t**
change this line
https://github.com/fgl27/smarttv-twitch/commit/163ecf50180ad530baff81cedb43566602862ae6#diff-eacf331f0ffc35d4b482f1d15a887d3bL7
 to
https://github.com/fgl27/smarttv-twitch/commit/163ecf50180ad530baff81cedb43566602862ae6#diff-eacf331f0ffc35d4b482f1d15a887d3bR7

after open the file
css_t/font-awesome.css 
and change the font file for the default font
https://github.com/fgl27/smarttv-twitch/commit/163ecf50180ad530baff81cedb43566602862ae6#diff-ae0ac8eae57c7d39798a48b5c436935aR5

and included the font file
https://github.com/fgl27/smarttv-twitch/commit/163ecf50180ad530baff81cedb43566602862ae6#diff-60bf770f7b503380f03d2f12c90206d1

I know may seems a little complicated but is all there

**Comment by fgl27** [comment]
I found this font "Roboto-Regular.woff" that looks very good here, and in theory must look the same for you 

looks like this

![Frame002_w1920h1080](https://user-images.githubusercontent.com/13755892/57142361-b3c20300-6d92-11e9-982f-c338c0c72eee.png)


I made a test zip here
[new.zip](https://github.com/fgl27/smarttv-twitch/files/3142203/new.zip)

To the manually uninstall process I described before, and if that doesn't look good let me see.

**Comment by DerSani1988** [comment]
Thanks, the hint with deinstalling the app manually works
Here is the screenshot  :) - waiting for your update, thanks for your hard work.

![Frame001_w1280h720](https://user-images.githubusercontent.com/25698122/57148354-bab83800-6dc9-11e9-928f-6eb9901f54fd.png)

**Comment by fgl27** [comment]
Is that picture from the "new.zip"? that I share before?

If yes I don't see a change, do you?

I need to see the log window, to see if there is errors loading the fonts.
Can you show me the log? before print the log press the key "B" or green so the app reloads this way it may show the font be loading and falling some how.

**Comment by DerSani1988** [comment]
@fgl27 the screenshot above was the old (master.zip) after uninstalling worked. I just saw 2 minutes ago, your messages above, i missed it 3 hours ago, sorry for that. 

This screenshot is from new.zip and looks fine for me :)

![Frame001_w1280h720 (1)](https://user-images.githubusercontent.com/25698122/57154086-4769f280-6dd8-11e9-8f94-21b673c23b48.png)

**Comment by fgl27** [comment]
Ok looks great to me.

I update the release version to have that same font. The new app version is 4.0.1.**050319**.

Let me know if the app looks like that after the new version shows up in about. To the app updated you may needed to close it, by chossing close in the exit dialog (click return key from live screen to see it).

**Comment by DerSani1988** [comment]
@fgl27 After restarting the App, the auto update worked and the font is as in my last screenshot, thanks a lot :)

**Comment by fgl27** [comment]
Thank you.
