### ISSUE TITLE
Connection failed, unable to load content.

### ISSUE THREAD

**Issue by amgmdz** [fgl27/smarttv-twitch#221]
Hi! Since February the application stopped loading the channels I follow in my account, as well as the games category if I'm on user menu (when I switch to main menu it loads the games categories) but not the channels I follow.

![image](https://user-images.githubusercontent.com/68931406/159377379-ecf2c86f-1089-46d3-967c-d0a762150486.jpg)

**Device:**
 - TV Model: UMU6303
 - Os version: Tizen 3.0
 - SmartTV Client for Twitch: 4.0.1.Feb.19.2022

**Comment by fgl27** [comment]
Know issue

https://github.com/fgl27/smarttv-twitch/issues/209

**Comment by amgmdz** [comment]
Thanks!!

**Comment by fgl27** [comment]
Thank you follow that issue for updates.
