### ISSUE TITLE
connection failed for all app options

### ISSUE THREAD

**Issue by cvalenciaec** [fgl27/smarttv-twitch#224]
hi, seems that all menus (even Main Menu) are failing with "connection failed" issue, it was working fine till today but now no video strean can be reproduced, I already restarted/rebooted TV without success, is there any issue with twitch api?

**Comment by fmjnax** [comment]
Same issue here. App v 4.0.1.Feb 19 2022

**Comment by fgl27** [comment]
Twitch changed something and caused a issue, close the app and reopen all must work OK, you may need to re add a authentication key

**Comment by fmjnax** [comment]
Above worked for me. Thanks!

**Comment by 0Gentleman** [comment]
Same issue.
Close and open didn't work but I rebooted the TV and all is ok ! It asks to add a key and all I fine
Thank you so much for this app.
