### ISSUE TITLE
Games not showing up

### ISSUE THREAD

**Issue by negitivesinx** [fgl27/smarttv-twitch#225]
I have a Chromecast and your app since the update doesn't show anything in the Games section.

I tried to remove my account and add it back, but the issue is still there. The official Twitch APP shows this section just fine but youres does not.

**Comment by fgl27** [comment]
This isn't the Android version of the app

This is

https://github.com/fgl27/SmartTwitchTV/issues/94

The user game section is down, but the general game section is ok, that link explains the problem.
