### ISSUE TITLE
Channel search not possible

### ISSUE THREAD

**Issue by IP-Fan** [fgl27/smarttv-twitch#226]
Hello,
first of all thank you for this project.
I have the problem that I can't search for a channel.
Is this a known issue or is it me?
I use a TV ue40j.

I would appreciate an answer.

Thanks a lot.

best regards
IP-Fan

**Comment by TheMY3** [comment]
Same for me, I can see only live streams

**Comment by reconman** [comment]
See #209

**Comment by fgl27** [comment]
close do to inactivity
