### ISSUE TITLE
Does'nt work anymore on orsay H-Series

### ISSUE THREAD

**Issue by kukoc63** [fgl27/smarttv-twitch#227]
Hi,

I'm using this app since a long time on my H series. I make a mistake and i deleted all my apps... so i reinstall all my apps. But twitch does'nt work anymore ( "unable to load stream data")

A fix is still possible for this old platform?

Thanks a lot =)

**Comment by fgl27** [comment]
Unknow...

Show the error, the frase "unable to load stream data" doesn´t exist on the app strings.

Also show the about of the app, side panel About.

**Comment by kukoc63** [comment]
My bad it was on the nikitakatchik version.

Sorry about that

**Comment by fgl27** [comment]
is all good, that project stop working when twitch shutdown they old API.

If this does't work for you I don't know another option

**Comment by kukoc63** [comment]
Sad to hear that :/

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fgl27** [comment]
close do to inactivity
