### ISSUE TITLE
User problem

### ISSUE THREAD

**Issue by Vinrys** [fgl27/smarttv-twitch#228]
Hello! I just installed the app for the first time, but I can make it run as expected. I keep getting the error message "Connection failed, unable to load content" for all options available. Also, every time I try to log in, it says that my username does not exist. Any help to solve this issue would be greatly appreciated!

**Comment by fgl27** [comment]
the app is ok for me, seems yours TV has a conection issue.
check yours network settings and related.

Share the username so I can show you that works.

**Comment by fgl27** [comment]
you can test the app using the browser with this link:

https://fgl27.github.io/smarttv-twitch/release/

you can only test the load of the screen there is no player on that link

**Comment by Vinrys** [comment]
Sorry for the late reply. I changed to another wifi / tried using ethernet and still receiving this message. Any chance I messed something up during the installation process?

**Comment by fgl27** [comment]
I can only tell if you share the about of the app, you can access it n the app side pannel.

https://fgl27.github.io/smarttv-twitch/release/

You can also test if you can open the above link and if content shows as bellow, on yours network.

<img width="3018" alt="image (3)-min" src="https://user-images.githubusercontent.com/13755892/165758883-5de715aa-1e4e-4c2f-9f53-e1aed8ca437d.png">

**Comment by CannonWest** [comment]
I'm also getting this issue! The live channels show up and stream just fine, but the "games", "channels", and "videos" tabs all give me a connection failed message.

**Comment by dmitittt** [comment]
same problem here, i recently moved houses and ISP, but most of the time my app will say Connection failed on every other screen besides the Live Page

**Comment by krlvo** [comment]
I can load the web app on my laptop, but after authenticating my user account it gives the same error message: "Connection failed, unable to load content. Hit refresh to try again." Search isn't working. Pretty much the only thing that does is the LIVE panel.

**Comment by faker-ino** [comment]
Same issue for me, I can just use my favorite streams and the live category. Nothing else is working, error message like above.
Pretty bummer, I really like the app - now using s0und app, but its buffering too often. I think it’s something with their adblocker.
Anyway, do you plan an update for the app? Seems many have this issue, so it cant be just an isp problem

**Comment by bainuus** [comment]
I am having the same issue. Whenever I want to load anything tab from the main menu or use menu/my channel than the live tab, or game tab I get the message "Connection failed, unable to load content. Hit refresh to try again." I reinstalled, re authorized, nothing seems to work. I can only watch the general live tab, and the live tabs from my channel.

**Comment by fgl27** [comment]
This issue is not to inform connection issues i only replied here because the user was unable to add a user with is short issue not related to screens not loading.

Screens not loading is be deal here:
https://github.com/fgl27/smarttv-twitch/issues/209

Don't span me too me every, this isn't a discussion of how many have a issue.
