### ISSUE TITLE
Can't resize chat after new update

### ISSUE THREAD

**Issue by gabrieluly** [fgl27/smarttv-twitch#23]
Hi there, my app updated and the key I used to make the chat bigger (up) is now used to bring the feed thing on screen, is there any new shortcut to resize the chat? It's locked in 12.5% here. This is my remote controller: 

![](https://http2.mlstatic.com/controle-remoto-tv-samsung-k6500-ku6000-ku6300-original-D_NQ_NP_785654-MLB26678755725_012018-F.jpg)

**Comment by fgl27** [comment]
Read the control, by pressing the key "C" or yellow.
to change chat size is key D pad down

**Comment by gabrieluly** [comment]
I read the instructions but key D actually opens the search box

**Comment by gabrieluly** [comment]
Ok I think I figured it out, it is actually a bug, while playing streams it cycles the sizes but while playing VODs the chat gets stuck at 12.5%

**Comment by fgl27** [comment]
De nada.
Sim eu conferi e já arrumei o problema era so nos videos mesmo travo no update.

valeu,
