### ISSUE TITLE
Audio and image out of sync after some minutes of playback

### ISSUE THREAD

**Issue by NSMMANZANO** [fgl27/smarttv-twitch#232]
Hi, first of all thank you very much for your effort providing this app for samsung smart TVs

I'm facing an error in which the sound goes out of sync every stream I watch. It starts just ok but as time goes the image starts to fall behind the sound I'm hearing

**To Reproduce**
1. Go to any stream
2. Wait for 5 minutes or so
3. The audio would be more and more out of sync

**Expected behavior**

Sound should keep the image state.

**Operation system (if is a installation problem):**
 - App Version: 4.0.1
 - Tizen Version: 6.5
 - TV: samsung QN93B (2022 model)
 - FW: T-PTMDEUC-1204.2

**Comment by fgl27** [comment]
The app uses tizen building player and Samsung doesn't provide support for unofficial apps 

Add those issue is probably not affecting others and there is no support from Samsung I don't have a solution...

In future TV firmware update it may get fixed.

**Comment by fgl27** [comment]
close do to inactivity
