### ISSUE TITLE
Stream not loading

### ISSUE THREAD

**Issue by leeolage** [fgl27/smarttv-twitch#233]
Hi, I was using the app in my Samsung 4K 43" UA43NU7100KXXA, was working normally, but then it stopped to work, it is not loading the stream anymore, I just get the spinner and then saying that the streamer is offline. I installed on an emulator with Tizen Studio, and it is working normal on my network, tried debugging on my TV using the release app, but the console is white and debugging on the emulator is working. Is there any other way to debug it?

**Comment by fgl27** [comment]
No debug isn't enable on the release.

This seems a DNS issue.

Can you check if the TV has a different network configuration?
