### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by Justin092** [fgl27/smarttv-twitch#234]
Hello, I followed all of the instructions, but when i get to the part where I need to import the project it doesn't do anything. All that happens is, as shown in the attached screenshot, a exclamation mark appears beside the name and the check box is greyed out. Any idea as to what is causing this? Thanks.

![Screenshot 2022-06-02 101533](https://user-images.githubusercontent.com/12641962/171650339-584652d9-d248-4cb2-8380-56f142786279.png)

**Comment by fgl27** [comment]
Screenshot tizen window it self, that small part makes no sense to where the error is.

**Comment by fgl27** [comment]
Also Hoover the mouse above the red warning and write here the error
