### ISSUE TITLE
Conecting to the "The Frame"

### ISSUE THREAD

**Issue by jodafi** [fgl27/smarttv-twitch#235]
Anyone know the reason... I have no problem connecting to any of my Samsung tvs but my 32 "frame" tv keep on "Not connecting" Any ideas? Hope someone can help :
<img width="960" alt="Uden titel" src="https://user-images.githubusercontent.com/58475771/171954906-c83705eb-d05a-4bd4-b71d-08ae8f29f9ff.png">
)

**Comment by fgl27** [comment]
close do to inactivity
