### ISSUE TITLE
there is a way to change the app logo for the twitch official one? 

### ISSUE THREAD

**Issue by fefucho** [fgl27/smarttv-twitch#237]
maybe its a stupid question, but can i do that before installing?

**Comment by toniocarbonio11** [comment]
I've changed the app logo with Photoshop and then i have installed the app and It works. If you have the Square icon in your TV i think the right dimension are 435px x 435px or a Little larger. Its pretty easy to do, i've Just modified the older logo that you can find in the app folder.
