### ISSUE TITLE
Changing resolution in the middle of a VOD restarts it from 0

### ISSUE THREAD

**Issue by ancho85** [fgl27/smarttv-twitch#239]
**Describe the bug**
Watching a VOD at 1080p and let's say it's been 10 minutes and manually changing it to 720p or any other the video is restarted to minute 0
**To Reproduce**
1. Go to any streamer page
2. Click past broadcasts
3. Select any video to start playback
4. Watch for a couple of minutes
5. Reduce resolution using the remote by clicking to the related symbol on screen
6. Video is restarted

**Expected behavior**
After changing resolution keep last minute/second and resume from that timestamp.

**Screenshots**

**Operation system (if is a installation problem):**

**Device:**
 - TV Model: UN50NU7095
 - Os version Tizen 4.0 (To be confirmed)

**Additional context**

**Comment by fgl27** [comment]
The above must fixe it but I can't test as I don't have a Samsung TV

Test and let me know.

If the app is open hold return so it closes so it receives a update next time you reopen it.

**Comment by ancho85** [comment]
Testing and so far so good! I believe it is fixed!
Thanks!
