### ISSUE TITLE
Option to turn off cc (Closed Captions)

### ISSUE THREAD

**Issue by TedCassirer** [fgl27/smarttv-twitch#243]
Certain streams feature closed captions. This app enabled this by default with no way to turn them off. The text is displayed over the stream making it very annoying to watch. There is an api to turn it off found here https://dev.twitch.tv/docs/embed/video-and-clips#synchronous-javascript-playback-api

Here's a streamer that have CC turned on https://www.twitch.tv/tgh_sr

**Comment by fgl27** [comment]
this app doesn't uses twitch player api from that link  https://dev.twitch.tv/docs/embed/video-and-clips#synchronous-javascript-playback-api

the app also doesn't enable anything related to cc, so I don't know how it is been displayed for you.

can you see it on VODs?

Show me how they look on yours TV running this app.

**Comment by TedCassirer** [comment]
They show up in VODs. 
![20220815_143250](https://user-images.githubusercontent.com/12045584/184635854-b58fc3cf-9b19-4fc4-a65b-c9877fdcb130.jpg)

Screenshot is from this [vod and time](https://www.twitch.tv/videos/1561514980?t=03h21m29s)

**Comment by TedCassirer** [comment]
They show up in VODs. 
![20220815_143250](https://user-images.githubusercontent.com/12045584/184635854-b58fc3cf-9b19-4fc4-a65b-c9877fdcb130.jpg)

Screenshot is from this [vod and time](https://www.twitch.tv/videos/1561514980?t=03h21m29s) 
If the text doesn't show up for you when you open it up in your browser you might need to click the [CC] button in the bottom right corner. I've noticed that it sometimes takes a couple of seconds for it to appear.

**Comment by fgl27** [comment]
I push the above to the app, that is the only reference on anything related to [subtitle or CC on the API](https://developer.samsung.com/smarttv/develop/api-references/samsung-product-api-references/avplay-api.html#AVPlayManager-setSilentSubtitle).

Test and let me know the result, to test just force close the app by holding return key when it open again will be updated with that change.

**Comment by TedCassirer** [comment]
That worked! Good stuff. I did not expect it to because I made sure all the subtitles settings were turned off on my TV before I created this issue.

Feel free to close this ticket unless you want to keep this issue around if you plan on adding this as a toggleable option

**Comment by fgl27** [comment]
Thank you.

For now I will just close as turning this in to a feature isn't simple.

The player API support differs from TV to TV, I can't know for sure with TV support or with stream have CC, with makes very difficult to properly add a enable/disable option.

If that changes on the future I'll add a proper feature.

**Comment by k3vink3vin** [comment]
Seeing closed captions in gibberish on the official twitch con stream.

![PXL_20221007_223139044](https://user-images.githubusercontent.com/5555353/194671578-df812c6c-bd26-4bf1-b993-0d140f18fb19.jpg)
