### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by leandrocharlier** [fgl27/smarttv-twitch#248]
Hello, I have a bug on my tv. I left the app in the background with a twitch channel that no longer exists and now when I open it I can't use it because it is trying to load that channel and there is an infinite loading I tried to touch all the buttons, restart the tv, restart the app but always when I open it, it's on the same screen.

**Comment by fgl27** [comment]
hold ch up key until a message show, then hold ch down the app will reset and fix it self.

**Comment by leandrocharlier** [comment]
It's works! thank you so much
