### ISSUE TITLE
Streams flagged as Mature do not render

### ISSUE THREAD

**Issue by Backiotomy** [fgl27/smarttv-twitch#249]
**Describe the bug**
Any streams with a mature content flag are not viewable through the app. The stream "loads", displaying Chat, Title, Play Time, but  only displays a black screen without audio or video. After accepting the "I agree" to the mature stream warning through a browser, it will still not play through this Tizen application linked to the same Twitch account.

**To Reproduce**
1. View to a stream flagged as mature content through the smarttv-twitch application.

**Expected behavior**
Streams with mature flag should render.

**Screenshots**
![screen_bug](https://user-images.githubusercontent.com/99847668/200728609-02cf7259-0f38-43f0-a8d2-a77dbd6fc3c5.jpg)

**Operation system (if is a installation problem):**
 - OS: Tizen - T-KTMAKUC-1310.1, BT-S

**Device:**
 - TV Model: UN55MU6500
 - OS: Tizen - T-KTMAKUC-1310.1, BT-S
 
**Additional context**
Troubleshooting: 
Power Cycle TV, Reinstall smarttv-twitch, disable proxy, change bitrate, toggle low latency, accept mature stream terms via Browser.

**Comment by fgl27** [comment]
that seems to see the **proxy** you have enable, as the app will not block any content.

have you tried disable it?

**Comment by Backiotomy** [comment]
Hello fgl27, thanks for your reply. I have disabled the Proxy and still get the same result. I noticed on these streams it always says Watch time 00:00. Pressing play or pause has no result.

![proxy_disabled](https://user-images.githubusercontent.com/99847668/200930534-d954a407-5895-4775-91f5-f510faf4f262.jpg)

![ismature](https://user-images.githubusercontent.com/99847668/200932977-e8a2d394-cadf-46aa-89ef-afebb45defdc.png)

Perhaps the API is blocking the response because it didn't detect the mature agreement has been agreed? That is the only difference between these streams and others when viewing them from twitch.com in a browser. 

I will try to get the application set up in Tizen studio so I can debug.

**Comment by Backiotomy** [comment]
Hey fgl27, I've done some debugging and determined this was not related to the mature stream at all and that was just a coincidence that the streams not working were flagged as mature. 

The actual problem is the "avc1.6404032" codec specific to the 1008p (1792x1008) resolution. All others that use the "avc1.4D02A" codec (936p and below) are working. The stream does display with this codec/resolution in the emulator, so perhaps it is some limitation of transcoding on the TV itself. Do you think there would be any way to resolve this?

Not working: 
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="1008p60 (source)",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=9275023,RESOLUTION=1792x1008,CODECS="avc1.640032,mp4a.40.2",VIDEO="chunked",FRAME-RATE=60.000

Working: 
#EXT-X-MEDIA:TYPE=VIDEO,GROUP-ID="chunked",NAME="936p60 (source)",AUTOSELECT=YES,DEFAULT=YES
#EXT-X-STREAM-INF:BANDWIDTH=8983405,RESOLUTION=1664x936,CODECS="avc1.4D402A,mp4a.40.2",VIDEO="chunked",FRAME-RATE=60.000

**Comment by fgl27** [comment]
Resolve this from the app side no, as this is an TV issue, check if there is any firmware update, Samsung sends silent updates so even if you don't have any firmware up pd as te or receive one in the future the stream may just go back to work.

Fire now the only workaround is to set the quality to 720p once you set to one stream any other you open will start playing using the same.

Did changing to 720p on those with issue resolve?

**Comment by Backiotomy** [comment]
Yes, changing to 720p does resolve the issue, as well as 936p since it still uses the generic codec. Thank you very much for the app and your assistance with this, I'm glad we were able to figure out what is happening.

**Comment by fgl27** [comment]
you welcome.
