### ISSUE TITLE
VOD chat replay no longer works

### ISSUE THREAD

**Issue by InvincibleDudu** [fgl27/smarttv-twitch#251]
VOD chat replay no longer works since a few days ago. Tried multiple VODs and none of them worked. The vod itself works fine and chat for livestreams works fine too. Restarting the app or tv didn't help. Maybe the twitch api changed again? I watch vod 99% of the time so it's kind of a big issue. 

 - OS: Android SDK29
 - TV Model: Sony Bravia VH1 (9000H)
-  App: 3.0.344, Web: Nov 15, 2022

A quick side note: The app was great (until this bug came) and I wanted to donate, but the paypal link says "Donations to this recipient aren't supported in this country" (I'm in China).

**Comment by georgebvro** [comment]
Same problem on Samsung 40JU7000, Tizen 2.3

**Comment by SimNico** [comment]
Can confirm the issue. Thanks for the great work !

**Comment by fgl27** [comment]
Fix, close the app and reopen to receive the updated
