### ISSUE TITLE
Live streams and VOD don't work

### ISSUE THREAD

**Issue by georgebvro** [fgl27/smarttv-twitch#252]
After the update from December 17, the live streams and the VODs don't load up anymore.

APP Version: 4.0.1.December 17 2022
Tizen Version: 2.3
TV: UJU7000

**Comment by Thebest35** [comment]
Same here! UE43JU6050 in Germany.. Pls pls make it work again! Running the pc all the time is to expensive these days

**Comment by Thebest35** [comment]
Or please make it possible to easily downgrade the app version in the app

**Comment by fgl27** [comment]
No relation to the de update the update only fixed chat.

You have a network issue, caused by the device or the network 

reference

https://github.com/fgl27/smarttv-twitch/issues/250

**Comment by Thebest35** [comment]
its not my network and not specific my device.. Its the same problem as in that thread https://github.com/fgl27/smarttv-twitch/issues/250 from 2 weeks ago that solved itself within a week and is now back again.. hope it'll work again soon

**Comment by fgl27** [comment]
> its not my network and not specific my device.. Its the same problem as in that thread #250 from 2 weeks ago that solved itself within a week and is now back again.. hope it'll work again soon

Nice that i works on this project for years, have deal with this and other types of issue, but you are so quickly to dismiss what I have to say.

Makes me what to help solve this do much
