### ISSUE TITLE
" Live has ended Problem again "

### ISSUE THREAD

**Issue by DeneXX1** [fgl27/smarttv-twitch#253]
Hello, since about 3 days I have the problem with the live has ended problem again, the streams don't load anymore.

App Version 4.0.1
Tizen Version 2.3
TV: UJU6400

**Comment by Ultraking040** [comment]
I'm having the same issue since few days..

**Comment by MarkdeJong** [comment]
So the issue with the app is that the SSL handshake fails:
![image](https://user-images.githubusercontent.com/25245940/209820201-c91f81b9-e08f-4801-98eb-55befd9d260f.png)

As you can see the certificate on the website changes on the 3rd of december, this is why the stream is unable to be opened
![image](https://user-images.githubusercontent.com/25245940/209820114-5a9027e9-6a3a-48c3-85db-9b1d7446b417.png)

Question is, why is the SSL handshake failing, hard to figure this out from the chrome debugging

On the other hand, HTTP is also working for this particular end, so maybe make it toggled or if SSL fails, switch back to HTTP

**Comment by fgl27** [comment]
We can try that, but the issue may remain, as the reason it fails is because of Cross-domain.

**Comment by ShameMate** [comment]
I'm having the same issue, every stream I click on says "the stream has ended" when they haven't. 

Anyone have an idea on how to fix it??

**Comment by fgl27** [comment]
This is not twitch chat stop the me too movement

**Comment by YassineKz** [comment]
I have same problem, only Twitch clips can work. all live streams does not :(

**Comment by Ultraking040** [comment]
Hey, did u already try that switching back to http or what that other user said? Don't want to hurry u, I just want to know if this app is dead for me now and I need to look for a new TV or stick or if it's worth to still wait for that try.. Thx anyways for that app all the time

**Comment by YassineKz** [comment]
Hello, I dont know where to switch to http instead of https, i cant find any option to do it from the app, someone can explain how? Thanks.

**Comment by Ultraking040** [comment]
Not you. The question was supposed to reach @fgl27. I think only he can set it.

**Comment by muchnik** [comment]
@fgl27 Friendly reminder. Any updates or workaround on this?

**Comment by DrJozin** [comment]
I'm sorry, but when???

**Comment by fgl27** [comment]
Open source project why no one makes changes to this?

WHY??????????????????????????

BTW I'm not a slave, I have a life if you don't do the changes yours self

**Comment by fgl27** [comment]
I push a workaround to solve this, if that doesn't work open an new issue with logs  please.
