### ISSUE TITLE
Cannot play past broadcasts.

### ISSUE THREAD

**Issue by GalaxyNET** [fgl27/smarttv-twitch#254]
It says video has ended. Exiting… when i started. Problem is from a day ago.

**Comment by fgl27** [comment]
Any channel vod? does that

anything else works clips and live?

**Comment by GalaxyNET** [comment]
Strange, other channels works with Clips, Broadcasts and Live, only ryukahr channel past broadcasts doesnt work.

**Comment by GalaxyNET** [comment]
Well i think i figure it out, streamer made all videos subscribers only. You can close this thread.

**Comment by fgl27** [comment]
OK, do you see the proper message? informing is sub only?

**Comment by GalaxyNET** [comment]
After i log on phone or pc, the message (sub only) appear on tv too, before that it just says video ended exiting…

**Comment by fgl27** [comment]
OK got it, thank you!

I'll revise and update so the message shows all the time.
