### ISSUE TITLE
Its over now? (meme review issue)

### ISSUE THREAD

**Issue by DeneXX1** [fgl27/smarttv-twitch#255]
Hi, No more Changes to Work again now?

**Comment by fgl27** [comment]
What? No more life for you to live on?

**Comment by DeneXX1** [comment]
Why are you being so cheeky? Then delete your post if you don't feel like
it you idiot

Am Di., 24. Jan. 2023 um 19:48 Uhr schrieb Felipe Leon <
***@***.***>:

**Comment by fgl27** [comment]
Why are you being so amusing? Then add more posts if u feel ok.

At you beautiful!

Am ti, 77 bun 2057 in 89:99 huh chshshshh Juca ramos ><
###@####;;;;!!!&&&

**Comment by fgl27** [comment]
> Hi, No more Changes to Work again now?

DOG there was changes!

**Comment by fgl27** [comment]
> Hi, No more Changes to Work again now?



> > Hi, No more Changes to Work again now?
> 
> DOG there was changes!

Hey DOG @DeneXX1 Changes

**Comment by fgl27** [comment]
Hey ooooooooooooo what Changes was @DeneXX1 

Help hey u

**Comment by fgl27** [comment]
I FOUND IT!!!! @DeneXX1 

[![CHANGES](https://img.youtube.com/vi/xi49yirJiEA/0.jpg)](https://www.youtube.com/watch?v=xi49yirJiEA)

**Comment by kleozzy** [comment]
Hey man , first of all thanks so much for this , i know you dont make anything out of it and you just devote time from your free hours.
I wanted to ask i just installed latest release today, but i get the stream has ended issue i restarted a few times but it doesn't seem to get the latest patch you did couple days ago, is there a way to force it ?

**Comment by baldisos** [comment]
It's indeed over. This dev is a joke, and so is this app.
