### ISSUE TITLE
Fresh install, stream has ended issue

### ISSUE THREAD

**Issue by kleozzy** [fgl27/smarttv-twitch#257]
**Describe the bug**
Hey man , first of all thanks so much for this , i know you dont make anything out of it and you just devote time from your free hours.
I wanted to ask i just installed latest release today([4.0.1_V9](https://github.com/fgl27/smarttv-twitch/releases/tag/4.0.1_V9)), but i get the "Stream has ended" issue, so i restarted it a few times but it doesn't seem to get the latest patch you did couple days ago, is there a way to force it ?

**To Reproduce**
1. Perform fresh install of latest release 4.0.1_V9
2. Run app on TV
3. All streams and menus working fine
4. Open a stream
5. Always get "Stream has ended error"

Thanks for any help in advance.

**Comment by fgl27** [comment]
same issue as https://github.com/fgl27/smarttv-twitch/issues/253

**Comment by fgl27** [comment]
> doesn't seem to get the latest patch

The zip is a empty shell has no code, every time the app open it downloads the latest version from git. So if the app open and you can see it all is OK.

the problem regarding not opening streams has no relation as if you go to the clip section all will work.
