### ISSUE TITLE
Streamlink might solve the issue not fetching m3u playlists

### ISSUE THREAD

**Issue by kleozzy** [fgl27/smarttv-twitch#258]
Hey man,

I just checked https://github.com/streamlink/streamlink/releases/tag/5.3.1 and https://pwn.sh/tools/getstream.html which uses stream link and they are able to fetch the m3u playlists for streaming, and works fine.

Might be worth checking it out in case something changed in the api and fix the stream fetch issue.

All the best,
K

**Comment by fgl27** [comment]
the stream fetch issue is a device issue, so this API may also be affected.

I don't have the issue on my devices, so I can test.

thanks for sharing this tool/API.

**Comment by kleozzy** [comment]
i guess an mu3 player is our best bet for now.

**Comment by fgl27** [comment]
If you can't access the playlist the player the not makw a difference

**Comment by fgl27** [comment]
The has proxy, purple proxy no longer works.

If someone wants to replace it withb this be my guess.

Today ttv lol proxy is working, the last time someone with a defected device tested, the proxy also fail.

That indicates that is an device issue, doesn't matter the tool it may all fail.
