### ISSUE TITLE
Can't get the chat to work

### ISSUE THREAD

**Issue by itspeaky** [fgl27/smarttv-twitch#26]
Hello, I've followed the guide installing everything and it all works fine but chat doesnt. It doesnt show anything on the chat frame. I saw the other issues threads about chat and got this log.

[log.txt](https://github.com/fgl27/smarttv-twitch/files/3168349/log.txt)

Thanks!

**Comment by fgl27** [comment]
If you see the other [issue](https://github.com/fgl27/smarttv-twitch/issues/11) way open a new one?
post there share tv info from about of the app, tv model version etc
