### ISSUE TITLE
"Live has ended" from a couple of cases

### ISSUE THREAD

**Issue by georgebvro** [fgl27/smarttv-twitch#260]
First of all, thanks a lot for fixing the "Live has ended" problem, now it works to view live streams and videos from User Menu.

There are still a couple of situations where the message is displayed, maybe the fix is similar and you can do it if you have the time.

When you are viewing a video (VoD) or when you are viewing a Clip if you press ↑ Up Arrow on remote, a list of thumbnails for the live channels that the user is following appears on the bottom of the screen (correct). But when selecting one of the live streams in the list, the "Live has ended" message is displayed.

If you do the same when already viewing a live stream, the newly selected live channel is loaded and the stream plays correctly.

Device: Samsung 40JU7000
OS: Tizen 2.3
App: 4.0.1.March 06 2022 (by the way, in the About Page, the APP Version shows the year wrong, 2022 instead of 2023)

Thanks for looking into it!

**Comment by kleozzy** [comment]
Can confirm streaming is fixed, thanks a lot brother !

**Comment by fgl27** [comment]
yes, I miss one check that affects when you press up to select something else.

I did a change please test and let me know the result.

**Comment by georgebvro** [comment]
I've tested and now it works from Videos and Clips too.

Thanks for the quick fix!

**Comment by kleozzy** [comment]
Awesome work brother!
