### ISSUE TITLE
Emotes not showing in player

### ISSUE THREAD

**Issue by RevENGE-code** [fgl27/smarttv-twitch#261]
**Describe the bug**
All emotes besides twitch-native and subscriber ones don't show in smarttv-twitch player

**To Reproduce**
1. Go to any channel
2. activate "Chat Show"
3. no emotes besides twitch natives and channel ones appear in the chat

**Expected behavior**
Show bttv/7tv/animated emotes in chat

**Device:**
 - TV Model: GQ43Q60RGTXZG
 - Os version: 2.3 (I think, not sure at all)

**Comment by RevENGE-code** [comment]
Fixed by closing the application multiples times, restarting the tv and force refreshing the chat.

**Comment by fgl27** [comment]
bttv was probably off for a few minutes
