### ISSUE TITLE
Chat window header no longer shows quantity of people

### ISSUE THREAD

**Issue by ancho85** [fgl27/smarttv-twitch#262]
**Describe the bug**
Chat window header no longer shows quantity of people. Now it only shows "... In chat" when previously there was the number of people actually in chat/watching. 

**To Reproduce**
1. Open a stream
2. Open chat in screen
3. Wait for it to show quantity of chatters
4. People are chatting but header stays in "... in chat" and it doesn't change

**Expected behavior**
It should show an aproximation of chatters. Or perhaps be removed if api no longer gives that info

**Screenshots**
![20230507_100302](https://user-images.githubusercontent.com/3135981/236682324-571ed9fc-deab-4045-8551-32857a3a6cf4.jpg)

**Device:**
 - TV Model: UNU709D
 - Os version Tizen 4.0

**App Version**
4.0.1.May 05 2023

**Comment by fgl27** [comment]
Twitch kill the api

https://discuss.dev.twitch.tv/t/legacy-chatters-endpoint-shutdown-details-and-timeline-april-2023/43161

**Comment by fgl27** [comment]
new api added.
