### ISSUE TITLE
Seeing Ads with Twitch Turbo

### ISSUE THREAD

**Issue by MMMXXXZZZ** [fgl27/smarttv-twitch#264]
My account is subbed to Turbo, the key is added OK in the menu yet I get ads while watching streams. I get no ads on official Twitch apps on desktop or mobile app.

**Comment by fgl27** [comment]
Third party apps don't have access to your turbo or sub privilege.

Adding a key only gives access to what is described in below IMG, better explanation on the link

https://github.com/fgl27/smarttv-twitch#when-accessing-twitch-authorization-site-after-adding-yours-credential-user-and-password-you-will-see-the-bellow-information

![image](https://github.com/fgl27/smarttv-twitch/assets/13755892/eafdfe42-5b86-4add-83ef-cbb59886797c)

**Comment by MMMXXXZZZ** [comment]
Devastating. Thank you for your work
