### ISSUE TITLE
Livestreams won't load.

### ISSUE THREAD

**Issue by Keula** [fgl27/smarttv-twitch#265]
**Describe the bug**
Livestreams just won't open at all, just says the stream has ended, was working about ~5ish hours ago, vods do work perfectly fine though.

**To Reproduce**
Open any livestream, and it won't load

**Device:**
 - TV Model: UMU6103
 - Os version: Tizen 3.0

Not much else to say about it

**Comment by fgl27** [comment]
Just update the app, close reopen must work, please test and let me know.

**Comment by Keula** [comment]
Yea okay works now, had to force close and re open a couple of times, but it fine now!

Thanks! <3
