### ISSUE TITLE
VOD replay "'jump to'' instead just restarts the VOD 

### ISSUE THREAD

**Issue by zjcheah** [fgl27/smarttv-twitch#269]
**Describe the bug**

**To Reproduce**
1. Go to any channel's past broadcasts/VODs
2. Move cursor to jump to certain time in stream
3. VOD doesn't jump to selected time but restarts from  beginning

**Expected behavior**
VOD continues playing from selected time

**Device:**
 - TV Model: UA65NU8000
 - Os version T-KTM2UABC-1334.0/Tizen (sorry don't know what exact # version beyond the version string provided here)

**Additional context**

**Comment by fgl27** [comment]
I push the changes to fix the issue that happens when you change apps as I described before.

If that isn't the problem let me know what it then.

**Comment by zjcheah** [comment]
hey Felipe thanks for the quick response but no that's not my issue, i do not switch apps when doing the steps above. 
Would it help if i capture a video of what I'm doing on my TV?

**Comment by fgl27** [comment]
no that will not help, if that is the case the device has a player issue, you need to capture the logs and share them.

install the app on debug mode and share the result of the console window here after reproducing those steps a few times.
also, try to jump on a clip to see what happens.

https://github.com/fgl27/smarttv-twitch/issues/250#issuecomment-1328306442

**Comment by fgl27** [comment]
I assume this is resolved, there was some updates regarding jump.

If not open a new one and share the logs
