### ISSUE TITLE
Feature Request: Vod Timestamps

### ISSUE THREAD

**Issue by SilverK29** [fgl27/smarttv-twitch#272]
Currently, the Twitch vod system makes it incredibly difficult to find VODs from specific dates. The verbiage used when navigating the Twitch VOD system is "yesterday, 2 days ago, a month ago" etc. All of these time indicators are very non-specific, and get increasingly non-specific once the VOD is 25 days or older, referring only to the month in which the VOD was created. Ideally, there is a way via the data obtainable from the "Schedule" section of Twitch channels to provide more specific timestamps in either UTC, or the user's native timezone. 

Example of current timestamps:

![](https://i.imgur.com/AitwGJR.jpeg)

![](https://i.imgur.com/whGcIZf.jpeg)

**Comment by fgl27** [comment]
what do you wanna? I don't get it.

this app doesn't use Twitch semantics for displaying the vod time stap. Those screenshots are from Twitch site, this isn't Twitch support.

and honestly, I don't see a point in changing anything, unless you make a proper point.
