### ISSUE TITLE
Lots of ads since a few days

### ISSUE THREAD

**Issue by detile** [fgl27/smarttv-twitch#279]
Hello, 
Long time user here. Watched on old tizen and new tizen tv too. I never saw ads in any stream since day one.
But since a few days on some streams the amount of ads is pretty insane and it's barely watchable, like 5 minutes of stream then 2 or 3 minutes of ads. On others streams it looks like there are a few ads from time to time.
Is this a normal behaviour till the next update where you could resolve the ''issue'', or should i expect to start seeing ads more and more due to twitch rules and/or website design ?
Notice that i don't complain about your app, it is my main chanel since maybe 6 or 7 years - i even made a donation to support you - but  i'm just wondering what is happening and if i maybe need to switch to an android tv or another OS where i could bypass those annoying ads.

**Comment by justingel** [comment]
I experience the same issue, i'm currently mainly watching a streamer which i'm subscribed to - but i'm getting random ads. Never had the problem before. Also when the ads are over, the stream isn't loading properly anymore, i have to restart the whole tv (holding the power button for a few seconds) and reopen the app to continue watching.

**Comment by fgl27** [comment]
> should i expect to start seeing ads more and more due to twitch rules and/or website design ?

yes unfortunately third-party apps are targeted and for now there is no solution.

Twitch doesn't allow third-party access to most of the user features including turbo or sub.

More about it here

https://github.com/fgl27/smarttv-twitch#twitchtv-app-for-samsung-tv-authorization-request-page

**Comment by fgl27** [comment]
> I experience the same issue, i'm currently mainly watching a streamer which i'm subscribed to - but i'm getting random ads. Never had the problem before. Also when the ads are over, the stream isn't loading properly anymore, i have to restart the whole tv (holding the power button for a few seconds) and reopen the app to continue watching.

for crashes you can go here

https://github.com/fgl27/smarttv-twitch/issues/277

no solution yet

**Comment by fgl27** [comment]
closing follow here

https://github.com/fgl27/smarttv-twitch/issues/280

and for crashes 

https://github.com/fgl27/smarttv-twitch/issues/277
