### ISSUE TITLE
Unable to install via "Run as" -> "Tizen Web Application"

### ISSUE THREAD

**Issue by marciii** [fgl27/smarttv-twitch#281]
Hi,

first of all: thanks for the great app I used for several years!
I had to reset my tv a few days ago and now I cannot reinstall the app.

I'm facing the same issue that was already mentioned in #13 

I checked the replies as well as the steps described in #157 and in the readme (including this part: "report a issue if the application doesn't install but make sure you go to all steps at least once again after a problem just revise it all before reporting"). However, I still didnt manage to fix it.

My current configuration in the package manager:

![extension tab](https://github.com/fgl27/smarttv-twitch/assets/17595789/cd5f37c8-b6bd-4ed5-9f29-03ef7f46d939)

![extension tab2](https://github.com/fgl27/smarttv-twitch/assets/17595789/452510de-6e29-4bb6-b38b-6feeadcb6ba8)

And the main tab:
![main tab](https://github.com/fgl27/smarttv-twitch/assets/17595789/fce9a3ae-ff26-4b5c-8d44-c252d288d04d)

The error message in Tizen Studio:
![error message](https://github.com/fgl27/smarttv-twitch/assets/17595789/1a2c1603-85ba-4546-9397-7718b5090f05)

So I installed 

- **Tizen SDK tools** in the "main" tab
- **TV-Extensions (7.0)** including **Web app.development**
- **Samsung Certificate Extension**
- **TV Extension Tools** including **Web app.tools**

Did I still miss something out or is this some new issue, maybe because of some updated versions or something like that?

Cheers

**Comment by fgl27** [comment]
What is the OS?

I successfully install from win 11 a few months ago and Ubuntu a few weeks...

So this maybe some incompatibility. Knowing the OS I can try on my side to see if I catch the error.

**Comment by marciii** [comment]
Sorry, forgot the version:

- Windows 11
- Tizen Studio 5.1
- Package Manager 0.5.39 (Repo URL https://download.tizen.org/sdk/tizenstudio with "official" as distribution)

**Comment by marciii** [comment]
In the meantime I successfully installed it on ubuntu 22. So in case someone else experiences that issue on windows, just switch to ubuntu, it works flawlessly =)

**Comment by fgl27** [comment]
Closed due to

https://github.com/fgl27/smarttv-twitch/issues/16
