### ISSUE TITLE
Infinite loading when opening the app

### ISSUE THREAD

**Issue by fsalata** [fgl27/smarttv-twitch#282]
**Describe the bug**
Infinite loading when I open the app, after some time the loading disappears from the screen but the app won't open.

**To Reproduce**
1. Open hub
2. Click on smarttv-twitch

**Expected behavior**
App opens.

**Screenshots**
![IMG_8663](https://github.com/fgl27/smarttv-twitch/assets/7861088/24eeb350-85c5-4c9c-b3eb-b3763a73fbd5)

**Device:**
Samsung UN43MU61000.

**Comment by fgl27** [comment]
I see it now I understand.

only a reinstall can fix it.

**Comment by fsalata** [comment]
Fixed by reinstalling.
