### ISSUE TITLE
7tv emotes

### ISSUE THREAD

**Issue by JonnyE80** [fgl27/smarttv-twitch#284]
**Describe the bug**
A few days ago I noticed that all 7TV emotes is gone. 
Have tried to reinstall the app it is still not working. 

**To Reproduce**
Enter the 7tv global or 7tv streamer and there will be a message saying that there are no emotes. Tried a bunch of channels that have 7tv enabled. 

**Expected behavior**
Well, it should show the emotes from 7tv. 

**Device:**
Google TV dongle. 

**Additional context**

**Comment by fgl27** [comment]
thank you for the report will update when possible.

**Comment by thantoscat** [comment]
any news on this issue? pls emotes still down

**Comment by fgl27** [comment]
Open source repo help yourself, I'm busy

**Comment by JonnyE80** [comment]
7tv emotes works for me again, so I guess this can be closed for now. 

Dont know if you updated the app but thanks for all the work you do on this app.
