### ISSUE TITLE
Captions are forced on since last update. 

### ISSUE THREAD

**Issue by EtRnitY** [fgl27/smarttv-twitch#287]
**Is your feature request related to a problem? Please describe.**
Captions are auto enabled for streams who have them in their broadcast settings. Problem is I don't find a way to disable them in the settings or player.
It wasn't happening before, I think it's since the last update, and only for streamers who have caption setting enabled, but not sure.
App version : 4.0.1 December 01 2023

**Describe the solution you'd like**
Perhaps adding a CC button to simply turn captions ON / OFF (like in the twitch app).

**Describe alternatives you've considered**
I tried to hold UP button to reset config / settings, but it didn't change anything. My current settings are default and this still happens.

**Additional context**
![20231213_140951](https://github.com/fgl27/smarttv-twitch/assets/37551568/b7c8805e-8aca-4134-a3e9-a7a54bde8233)

I don't know how to disable the captions at the top.

**Comment by fgl27** [comment]
Seems a TV issue the app didn't change anything regarding that

You can set here

https://github.com/fgl27/smarttv-twitch/blob/d797bcfbc7f6b1acc8f2f8cc71904c8186f47247/app/specific/Play.js#L1258

Is is by default reason described there.

Is that a live or vod?

Can you produce logs?

Here is the how to log

https://github.com/fgl27/smarttv-twitch/issues/250#issuecomment-1328306442

**Comment by EtRnitY** [comment]
It happens on LIVE or VOD, but only on some channels (depends if the streamer has captions activated in their settings I guess).
Only streamer voice have captions, no other sound / voice.
It doesn't happens on other apps, even official twitch app. Accessibility features are all OFF in my TV settings. 

I tried to plug in my old usb fireTV to test the android smarttv app on my samsung TV, and eveything is fine. Problem only occur with the tizen version of smarttv-twitch.

I completely uninstalled and reinstalled with tizen studio, captions are still there.

Logs : I did a search for one of the streamer with caption ON, and started to watch a VOD

![log2](https://github.com/fgl27/smarttv-twitch/assets/37551568/9afdba81-f610-40bf-bf5d-f90772514550)
![log3](https://github.com/fgl27/smarttv-twitch/assets/37551568/ee60dcd3-fcea-45d0-b158-7f12e62f1873)
![log5](https://github.com/fgl27/smarttv-twitch/assets/37551568/00e34779-244c-4cc5-bbff-61670482c1f4)
![log6](https://github.com/fgl27/smarttv-twitch/assets/37551568/bbc5709e-6efb-464f-a56b-45201f9abb37)
![20231214_193739](https://github.com/fgl27/smarttv-twitch/assets/37551568/8389166d-1449-45ac-81c7-6a526f408a1c)
