### ISSUE TITLE
About + Controls pages causing (little) trouble

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#293]
1. Go to a videos or clips list
2. Go to User -> My Channel page (happens also on some other non-list pages)
3. Open About or Controls and close it
4. You're back at the channels main page but notice the video or clip number on the bottom right which shouldn't be there
5. When you Press OK now you should be taken to the selected section or live stream of the channel but instead a video or clip from the list of step 1 opens

There's a worse scenario when it seems like the text of two pages is laid over each other and you can't read anything anymore. But I haven't figured out how to reproduce this yet.

**Comment by fgl27** [comment]
I will check this

Thanks for the detailed description.

**Comment by fgl27** [comment]
Done
