### ISSUE TITLE
App permanently stuck in infinte loading menu (Sidemenu -> Videos)

### ISSUE THREAD

**Issue by MMMXXXZZZ** [fgl27/smarttv-twitch#294]
I happened to explore the sidebar and clicked on Videos, the app is now stuck loading forever even after unplugging and plugging the TV back on. Mind you I've used the VODs feature for many channels before by going into the channel profile and clicking Videos there, but this sidebar menu version of "Videos" just got it stuck forever.

![IMG_9235](https://github.com/fgl27/smarttv-twitch/assets/2080985/18aa1a2e-1542-4f17-8825-8bfef9cc5194)

MN : UN55NU8000
PD : --/--/----
SN : 079S3CDK600045M
FW : T-KTM2UABC-1341.2
FC : SWU-OU_T-KTM2UABC_1341_240112
MI : T-KTM2UABC
LS : CHILE_DTV
DI : 7XCLTSRQUC4RE
MA : C048E695959D
VS : 1341.240112

**Comment by fgl27** [comment]
Hold channel up key until see msg then hold it down the app will restart to the live screen. 

Let me know if works.

**Comment by fgl27** [comment]
the issue is now resolved.
