### ISSUE TITLE
Animated Thumbnails not working with newer VODs

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#295]
Animated thumbnails stopped working with VODs created after May 16th. Known issue?

**Comment by fgl27** [comment]
No, I see it working on today's VODs and older.

The issue is gone or it affects some specific channel?

**Comment by fgl27** [comment]
This

![image](https://github.com/fgl27/smarttv-twitch/assets/13755892/91f2b15b-14db-4219-8ef7-bc4f95bbb327)

isn't showing on newer vods

is that the issue?

**Comment by fgl27** [comment]
are you referring to this feature?

![image](https://github.com/fgl27/smarttv-twitch/assets/13755892/f0f97f7f-807a-4873-8ba6-194cd250d45b)

From the Android app?

As this repo is for the Samsung version.

I fixed the Android issue related to seeking preview imgs

**Comment by fgl27** [comment]
Was a random bug in the API that sometimes it fails sometimes works, I fixed it on the app side

just close the app and reopen so it updates;

**Comment by someone30** [comment]
Yes, it seems to be fixed, thank you! (It affected every channel during the last two weeks)
