### ISSUE TITLE
Back function in Search screen not working correctly

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#296]
When pressing BACK in the Search screen you always land in the Live section instead of the previously selected section.

**Comment by fgl27** [comment]
no, it doesn't.

default is Live but only if the screen you are can't go back to from a search.

so what are you doing exactly?

**Comment by someone30** [comment]
For example:

1. Go to a channels VOD section
2. Select Search
3. Cancel the search and press BACK (you should be taken to the screen of 1., right?)
4. You suddenly are in the Live section

Maybe the closing of the on-screen keyboard is interpreted as a "back" already so when you press BACK again there's nothing to go back to?

**Comment by fgl27** [comment]
this is an odd scenario...

if you do a search and then use the side panel to navigate the app, you can look thinking is doing a search, and then the default behavior to exit the search screen if doing a search is to go Live.

The above change fixes that scenario, if you find the issue again let me know.

**Comment by someone30** [comment]
It works now in a lot of scenarios 👍 but still doesn't in e. g. the following:

1. Select Games
2. Exit the app (these first two steps just to have a defined starting point)
3. Reopen the app (you should be in the Games section)
4. Select Search, actually search for a channel and open it
5. Go to its VOD section
6. Select Search and go back (you should be taken back to the channels VOD screen)
7. You falsely land in the Games section

Interestingly the "Search / BACK" seems to work perfectly if you initially call the channel via e. g. the Channel Content button in a live stream and then select its VOD section, i. e. no previous real search is involved...

**Comment by fgl27** [comment]
Yes, that was by design to avoid "looping", as the app could in the past go back to the screen and then to the search over and over if you press back then back then back again.

Now it works, but the app can only go back to one level, meaning if you do two searches go to do another search, and then press back it will only go back to the last search and then will go back to the screen that started the search.

test let me know if anything can be improved

thanks for the help.

**Comment by someone30** [comment]
Works like a charm now, thank you!

One back sequence makes totally sense in that situation. So it's indeed an improvement, not only a workaround.
