### ISSUE TITLE
Failure installing app on Tizen 2.3 TV with TV Extensions-8.0

### ISSUE THREAD

**Issue by georgebvro** [fgl27/smarttv-twitch#299]
I've installed the latest version of Tizen Studio on Windows 10 and I can't install the app on the TV by using it.

After following all the steps from the installation guide for the app, when I get to importing the app project, I notice that the only version I can pick is "8.0". That "7.0" in the drop-down can't be selected, only "8.0" can be. So I pick "8.0" and I import the project.
![Import project](https://github.com/user-attachments/assets/7a4d379b-597a-4b25-880b-3003c887c526)

Then, when I right-click the project, Run As -> Tizen Application I get a message stating the device (I assume my Tizen 2.3 TV) doesn't support the project's platform (I assume TV extension 8.0).
![Platform Not Supported](https://github.com/user-attachments/assets/42b5311a-1614-43d2-b5da-f6e7bef16fb9)

I answer "Yes" to "Proceed with launch?" but after it tries to install the app, it gives an error and stops.
![Install fail](https://github.com/user-attachments/assets/1d9ce08f-72bf-4f8a-9a3b-a9b6c30b9173)

So, my guess is that my Tizen 2.3 TV is not compatible with version 8.0 of the TV Extensions. Correct me if I'm wrong.

I looked into Tizen Package Manager but the only TV Extension version available is 8.0. So, I downloaded version 7.0 of the TV Extension for Tizen SDK from https://developer.samsung.com/smarttv/develop/tools/tv-extension/archive.html and manually configured the local repository in Package Manager but after successfully configuring the local repository, no option for TV Extensions-7.0 appear in Package Manager so I can install it.

So, I can't install the app on the TV using this latest version of Tizen Studio with TV Extensions-8.0. Do I understand the problem correctly and is anything I could do to solve it?

Thank you!

Device: Samsung 40JU7000
OS: Tizen 2.3
Tizen Studio 5.6

**Comment by fgl27** [comment]
There is a pined issue: https://github.com/fgl27/smarttv-twitch/issues/16

use that, please.

TV 8.0 is fine. I installed the app a few times. You just need to change it as you did; the problem is elsewhere.

Please check to see if the problem is related to the last post I made on that issue. And please post anything else there.
