### ISSUE TITLE
Support for FFZ emotes

### ISSUE THREAD

**Issue by Shaddox** [fgl27/smarttv-twitch#30]
Hey,

Thank you for building and maintaining this app. It works really nicely.

I want to ask though, any chance for FFZ emotes? KapChat seems to support them so that's not an impediment. If you could tell me where to look I'd try making a PR for this myself when I find the time.

**Comment by fgl27** [comment]
I didn't had the time to port that part yet.

I most of kapchat code to the app but adapting and improving, using they code as base but removing the things I don't like, as they use jquery I don't wanna use it as tizen is already slow with jquery it gets even slower.

the implementation of frankerfacez is similar to the betterttv

on betterttv you pull globals

https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/ChatVod.js#L88

the frankerfacez link is
https://api.frankerfacez.com/v1/set/global

and for it channel 

on betterttv
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/ChatLive.js#L89

the frankerfacez link is
https://api.frankerfacez.com/v1/room/ninja
aks 

`var theUrl = 'https://api.frankerfacez.com/v1/room/' + encodeURIComponent(Main_values.Play_selectedChannel);`

but frankerfacez is needed a different implementation of
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/ChatLive.js#L128

something as change this 
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/ChatLive.js#L133
to
`'3x': 'https:' + (data.sets.emoticon.urls[4] || data.sets.emoticon.urls[2] || data.sets.emoticon.urls[1])`

in case a emote doesn't have the option 4 we use 2 and so on so on.

something like that

Some day i add if you wanna to try is something like that.

**Comment by fgl27** [comment]
Done app version **051719** and up has the featuring, check version in about if not that close and re open the app so it can update it self..

**Comment by Shaddonius** [comment]
Excellent and really fast work! I was actually planning on jumping on this but it seems you got ahead really fast. So, thank you.
