### ISSUE TITLE
Can't play any stream in 60fps

### ISSUE THREAD

**Issue by hu553in** [fgl27/smarttv-twitch#301]
Seems I can't play any stream in 60fps.

Quality automatically drops to nearest one with non-60fps.

TV model is 55" Crystal UHD DU7100 4K Smart TV.

Do you know anything about this issue?

**Comment by fgl27** [comment]
No.

There is a check method, if the player tries to play and fails it lowers the quality until it finds something it can play.

your device is unable to play 60 frames of Twitch content.

can you play 60 on YouTube?

**Comment by hu553in** [comment]
Seems yes, I can - playing 2160p60 on YouTube right now. Then ok, surely nothing to do from ur side, thank you. BTW app is really great :)

**Comment by fgl27** [comment]
TV bug can't play twitch content

**Comment by hu553in** [comment]
@fgl27 Sorry, I can't check, because I even can't use YouTube on my TV right now.

And I think it's irrelevant ATM, so let's just forget.

Thanks a lot for your replies :)
