### ISSUE TITLE
Password Issues

### ISSUE THREAD

**Issue by shhhhhk** [fgl27/smarttv-twitch#31]
Hi,

I've gone through all the steps and get to the installation stage and it asks for 2 passwords, Author and Distributor passwords.

I use the one i've entered in the certificate twice but get an invalid password error.

Cheers
Sam

**Comment by fgl27** [comment]
I think you are doing something different as it never pops up to anyone.
Maybe is how you setup the certificate, have you add a certificate as I recomende? what is the Tizen sdk version?

- back to Tizen Studio > Tools > Certificate Manager > + > select/click Tizen > create a new author.. next > setup name password etc... next > Use the default Tizen... Finish > Success click OK
- Select the certificate it must have a "V" on the front of it (that means you have selected it) close the Certificate Manager

![certificate](https://fgl27.github.io/smarttv-twitch/screenshot/install/certificate.png)

Here there is a help about that, but as I wrote that is not the expected behavior when fallowing the readme steps

https://github.com/fgl27/smarttv-twitch/issues/16#issuecomment-489253873

**Comment by shhhhhk** [comment]
Hi Felipe,

Thanks for taking the time to reply. I’ve followed the instrustrions closely so I can’t figure out where I’ve gone wrong.

[cid:image001.png@01D50B71.78F48B40]

[cid:image002.png@01D50B74.114D2D00]




[cid:image003.png@01D50B74.114D2D00]

[cid:image004.png@01D50B74.114D2D00]

**Comment by shhhhhk** [comment]
Hi Felipe,

Sorry, version below.

[cid:image005.png@01D50B74.6D5D2370]

Cheers
Sam

From: Sam holz
Sent: Wednesday, 15 May 2019 11:16 PM
To: fgl27/smarttv-twitch <reply@reply.github.com>; fgl27/smarttv-twitch <smarttv-twitch@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [fgl27/smarttv-twitch] Password Issues (#31)

Hi Felipe,

Thanks for taking the time to reply. I’ve followed the instrustrions closely so I can’t figure out where I’ve gone wrong.

[cid:image006.png@01D50B74.6D5D2370]

[cid:image001.jpg@01D50B74.6D78E8D0]




[cid:image008.png@01D50B74.6D5D2370]

[cid:image009.png@01D50B74.6D5D2370]

**Comment by fgl27** [comment]
@shhhhhk I don't get what you are trying to write try again please, I edit yours post to remove text that makes no sense.

Try the help from the link I share if that doesn't help, try to uninstall tizen and start over, the tizen sdk is a little bugged.

**Comment by shhhhhk** [comment]
Hi Felipe,

I uninstalled everything and started over. Same result asking for 2 passwords and an error.

Is the below Signing Dialog normal? i.e 2 passwords required
[cid:image001.jpg@01D50C90.76BBA2D0]

I followed all the steps exactly as outlined and still get the below error at the very end. Is this a Java issue? I have Java SDK 8u211 installed.
[cid:image004.png@01D50C90.76B6C0D0]

Cheers
Sam

**Comment by shhhhhk** [comment]
Hi Felipe,

It was Tizen SDK playing with the distributor passwords. I found others having the same issue.

The distributor password is tizenpkcs12passfordsigner

It has worked and great app thankyou.

Cheers
Sam

From: Sam holz
Sent: Friday, 17 May 2019 9:11 AM
To: fgl27/smarttv-twitch <reply@reply.github.com>; fgl27/smarttv-twitch <smarttv-twitch@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [fgl27/smarttv-twitch] Password Issues (#31)

Hi Felipe,

I uninstalled everything and started over. Same result asking for 2 passwords and an error.

Is the below Signing Dialog normal? i.e 2 passwords required
[cid:image002.jpg@01D50C92.62210F70]

I followed all the steps exactly as outlined and still get the below error at the very end. Is this a Java issue? I have Java SDK 8u211 installed.
[cid:image003.png@01D50C92.62210F70]

Cheers
Sam

**Comment by fgl27** [comment]
I know I already give you the passowrd, but for some reason you didn't get as I share the link with you that has the password this link https://github.com/fgl27/smarttv-twitch/issues/16#issuecomment-489253873  that I alredy share 3 times here.
