### ISSUE TITLE
Black screen with audio on every stream

### ISSUE THREAD

**Issue by yalpski** [fgl27/smarttv-twitch#32]
Hello,

I've successfully installed this app on my new Samsung Q70 (2019) following your instructions (which were great). However, every stream I load only comes up with a black screen. The stream's audio and chat work perfectly, but there is no video at all. Changing the stream quality has no impact on this. This is also the case for all VODs as well.

**Comment by fgl27** [comment]
Hi.

This may be a issue related to setting up the screen size or something related. But as I can't reproduce here you will need to install the debug version of the app from this link

https://github.com/fgl27/smarttv-twitch/archive/master.zip

Install as a new project the instruction to log are here

https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

After you manage to install that app and see the log, press the key green or B from the live content screen and after the app reload play some live, vods and clips after that save all the log output to a txt file, zip it and drag it to a new post here.

Also share the complete TV info that you see on about of the app in case it doesn't show in the log, tizen version, tv model and FW.

**Comment by yalpski** [comment]
Thanks for the quick reply! Same issue on the debug version, I'm attaching the logs here.

Tizen Version: 5.0 | TV: QRQ70 | FW: T-MSMAKUC-1065.0

[Tizen Debug.txt.zip](https://github.com/fgl27/smarttv-twitch/files/3195386/Tizen.Debug.txt.zip)

**Comment by fgl27** [comment]
can you try to play a clip? and log it
what happen when you press the red A key when a  live stream playing?
press more then once.

**Comment by yalpski** [comment]
Well, I feel silly. Pressing the A key immediately brought up the video. Sorry for wasting your time!

**Comment by fgl27** [comment]
OK, but there still a issue.
As is not demanding to do anything to watch a stream, you just open and it plays.

The A key is used to change from full screen to side by side video + chat.

So I need to fix it for you.

After you press A what happens it just shows or goes to  side by side video + chat?
And after that another press what happens?
can you enable the side by side video + chat? at all?

And one more thing important after you use the workaround to make it to show, you exit the stream and the next stream works without any A key press?

Answer me that so I can work on a proper fix...

**Comment by fgl27** [comment]
@yalpski can you confirm, I push a change to prevent the need to press A after pressing play.

Does that work for you , just open the release version that you must have instaled and try it.

**Comment by yalpski** [comment]
Sorry for my lack of response, I've been on the road for the past few days. To answer your questions:

The initial A press does display side by side video+chat, then when I press A again it shows fullscreen video. I can toggle between the two without issue. Once I have pressed A on one stream, I do not need to do it again for any other stream unless I do a hard reset of the TV itself. 

I will give the updated release version a shot today and report back. Thanks so much for your help!

**Comment by yalpski** [comment]
Everything works perfectly! Thanks again!

**Comment by fgl27** [comment]
Thank you, if need open a new one.
