### ISSUE TITLE
Some minor questions about the process

### ISSUE THREAD

**Issue by TheRealDannyyy** [fgl27/smarttv-twitch#35]
**Describe what you need.**
Hi. I'm interested in installing this since both Samsung and Twitch don't seem to give a damn but I'd like to ask some questions before doing so:

1. Will this work on a Samsung UE49MU6179 TV?
2. Does the app remain installed like other apps or do I have to keep repeating the installation process?
3. If the app remains installed, can I disable developer mode and run it just fine?

**Comment by fgl27** [comment]
can you just find out all of that by trying?
If the result is not OK, open a issue if the issue you have isn't already listed.

I'm not sharing a nuclear bomb.

1. If is a 2015+ TV I can only assume yes as I don't have it, if is older will not work.
2. For most TV yes, if not refer to #18
3. Never try I assume yes, let us know.

**Comment by TheRealDannyyy** [comment]
I'm currently trying it out but it fails to connect to my TV in the remove device manager.
Is this a common issue?
