### ISSUE TITLE
CSGO Videos buffering on all resolutions[30mbps connection]

### ISSUE THREAD

**Issue by pandareen** [fgl27/smarttv-twitch#36]
**Describe the bug**
CSGO streams buffering even on 30 mbps connection

**To Reproduce**
1. Watch any csgo stream on any video settings.

**Expected behavior**
Streaming should happen without buffering as I'm on 30 mpbs connection

**Operation system (if is a installation problem):**
 - OS: Tizen
 - Samsung 4k tv 43 inch

**Comment by pandareen** [comment]
Does my geographical location affect the streaming capability? I'm in India and if I can set the location of streaming servers closer to my location, that would be cool. If you can point me out in the code I can do it myself.

Thanks

**Comment by fgl27** [comment]
what is the problematic stream/vod link? from twitch site

If the site doesn't provide a server option for viewer that doesn't exist, does the site has a option choose view server to you?

**Comment by pandareen** [comment]
Problem lies with all links, in-fact I've tried other games too.

**Comment by fgl27** [comment]
Informe yours internet provider then.
