### ISSUE TITLE
Twitch Turbo - Still Receiving Advertisements

### ISSUE THREAD

**Issue by ef001730** [fgl27/smarttv-twitch#37]
**Is your feature request related to a problem? Please describe.**
I am subscribed to Twitch Turbo which means I should receive no ads while watching any twitch channel, however I am receiving them when using the app. Would putting an authentication key in solve this issue?

**Describe the solution you'd like**
I'd like to receive no ads.

**Describe alternatives you've considered**
I have input my twitch username into the "User" section, but I have not put an authentication key in yet as I don't require it at the moment, unless it solves this issue.

**Additional context**
N/A

**Comment by fgl27** [comment]
I have zero adds here and I don't have turbo.

Are you confusing a streamer add with a twitch add? what stream is that? is the add as part of the VOD also?

I mean that the streamer it self plays the add as part of the stream, so if you can see it as part of the VOD is a streamer add and not a twitch one.

In this case if you are shore is a twitch add you must add the key as that is the only way that the app has to inform twitch that you are watch it, just by adding a user doesn't do a thing regarding informing twitch.

But I think you are watching a stream that the steamer is adding the add it self not a add by twitch, as I never see a add on my end ever.

So answer me those questions... and try the key and after let us know.

**Comment by ef001730** [comment]
Yes, I am getting twitch add, not in the VOD, just in live watching. I will try to add the key and see if it changes things. Thank you.

**Comment by ef001730** [comment]
So far looks like the advertisements have stopped after adding an authentication key. Thanks so much for this wonderful app.

**Comment by fgl27** [comment]
Are you sure about the VOD.

you didn't share the stream, or the vod or the time that the add shows in the live so one can see on the VOD, so are you sure that in the exactly same time of the live that you get the add the add is not there in the VOD?

the time of the live is in the top left corner when you press the select key it show a red dot and "Live since XX:XX:XX", that is the time you must go and look on the VOD, preferably what the vod from at least 3 minutes before the time from the live where there was a add.

**Comment by ef001730** [comment]
I assure you that the ads are not being broadcasted by the streamers, it is an advertisement played by twitch on request by the streamers to generate revenue. Anyways, those same advertisements have now stopped completely since I put the authentication key in, even though the streamer is still running them as normal.

**Comment by fgl27** [comment]
OK, thanks for the info.
