### ISSUE TITLE
Channel category

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#38]
I'm often switching between the general Live category and a certain channel (mainly its past broadcasts). Switching to the latter is quite comlicated: Press blue/D key (search) --> Type in <channel name> --> Select Channel box  --> Navigate to channel --> Select Live/Past broadcast/Clips. There doesn't seem to be an easier way - maybe I'm doing somthing wrong?

Yes, there's the User category, but the content shown there (mostly useless) is different from the above mentioned "Channel content" view.

Therefore I'm suggesting an own Channel category, which remembers the last selected channel or - even better - where you can add and save channels like in the User category. An alternative would be to integrate the functions of the "Channel content" view (Live/Past broadcast/Clips) in the User category.

**Comment by fgl27** [comment]
don't you see the **fallowed channel** section of the user section?

fallow a channel will be there no need to search.

**Comment by someone30** [comment]
Do you mean the "Followed channels" function in the User category? This is only showing channels the selected streamer follows. It's not showing his broadcasts.

![grafik](https://user-images.githubusercontent.com/52448191/60543150-d67e8280-9d15-11e9-8e58-2f1dbe8e7782.png)
None of these sections will show the streamers broadcasts, only those of others. Or do I have to add an authentication key first? I thought this is only necessary for sub-only content.

But more likely you mean I have to follow a channel first to reach its content straight away, right? Again, to do that I would have to create authentication key, which I don't really need tbh.

The only sections I'm using are these (taken from your screenshots):
![grafik](https://user-images.githubusercontent.com/52448191/60532670-205b6e80-9cfe-11e9-8aca-3da007a03a05.png)
If this channel content view alone could be reached easier and quicker there would be no need to take a detour via an authentication key.

**Comment by fgl27** [comment]
can you read my previously post again? please, I wrote...

> fallow a channel will be there no need to search, **opening a channel in the fallowed channel section goes to that channel content section.**

Don't you understand that the channel can be open from **fallowed channel** section.

**Comment by someone30** [comment]
I understood what you meant but I misunderstood the meaning of the User category. I thought it's for adding users/streamers that you want to follow. I falsely did that and wondered why you mentioned the "followed channels" section which only showed channels the added streamer followed (and not his own of course). Now I get it, sorry. ;-)

**Comment by fgl27** [comment]
yes I was confused too with yours confusion.

Not a problem glad can help. if needed open another issue.
