### ISSUE TITLE
Small control optimizations

### ISSUE THREAD

**Issue by someone30** [fgl27/smarttv-twitch#40]
- Fast Forward/Rewind and Stop keys on the bottom rows of the classic remote should be mapped

- Pressing Play key on the classic remote during a playback should only show the infomation panel instead of pausing playback; Requirement: the Play/Pause combo key on the smart remote equals a different function or the Pause key on the classic remote; Pressing Play during a pause should still resume playback

- Control windows should be openable AND closable with the same key (toggle function), e.g. yellow/C key during playback

**Comment by fgl27** [comment]
OK.

**Comment by someone30** [comment]
Thanks a lot!

**Comment by someone30** [comment]
Added Stop key to the original post.

**Comment by fgl27** [comment]
Done, update pushed to use the update make shore to close the app so the app updates on next start.
