### ISSUE TITLE
Invalid password errors, installation issue

### ISSUE THREAD

**Issue by Lutzy** [fgl27/smarttv-twitch#41]
After wasting hours getting "Invalid password" errors every time I tried to build this project (or any project for that matter), I finally figured out what was going on. I'm leaving this info here so that you can either add it to the Readme or at least someone can find this Issue via Github search.

Basically, if you follow the Readme to a T using the latest Tizen Studio, your <tizen-studio-data>/profiles/profiles.xml will look like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles active="strong" version="3.1">
<profile name="strong">
<profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/developer/tizen-developer-ca.cer" distributor="0" key="/home/ryan/tizen-studio-data/keystore/author/strong.p12" password="/home/ryan/tizen-studio-data/keystore/author/strong.pwd rootca=""/>
<profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-ca.cer" distributor="1" key="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12" password="/home/ryan/tizen-studio-data/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.pwd" rootca=""/>
<profileitem ca="" distributor="2" key="" password="" rootca=""/>
</profile>
</profiles>
```

But those .pwd files aren't ever created by the certificate manager and attempting to just put the correct passwords in plaintext in files with those names doesn't work. Instead, what you need to do is edit your profiles.xml accordingly:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles active="strong" version="3.1">
<profile name="strong">
<profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/developer/tizen-developer-ca.cer" distributor="0" key="/home/ryan/tizen-studio-data/keystore/author/strong.p12" password="<yourStrongPasswordHere>" rootca=""/>
<profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-ca.cer" distributor="1" key="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12" password="tizenpkcs12passfordsigner" rootca=""/>
<profileitem ca="" distributor="2" key="" password="" rootca=""/>
</profile>
</profiles>
```

Finally, the stupid IDE will constantly attempt to overwrite these correct settings with its *.pwd garbage, so you'll need to do a `chmod a-w <tizen-studio-data>/profiles/profiles.xml`

Anyway, beautiful app, thanks so much for your work, but I'm hoping this will be helpful to anyone else that gets stuck using the latest Tizen Studio in Ubuntu.

**Comment by fgl27** [comment]
Yes tizen is far from be something OK to use.

On the past there was a similar problem after a tizen update, so I create this help
[How to create a Samsung developer certificate and send to the TV](https://github.com/fgl27/smarttv-twitch/tree/master/release/githubio/etc)

The odd thing is here I'm on latest version of tizen and here it just works, and yes there is no .pwm file

![Screenshot from 2019-07-05 11-52-41](https://user-images.githubusercontent.com/13755892/60730533-c59f5e00-9f1b-11e9-97c3-8de6060dfdb6.png)

![Screenshot from 2019-07-05 11-53-43](https://user-images.githubusercontent.com/13755892/60730541-c9cb7b80-9f1b-11e9-9252-59720d43f13b.png)

![Screenshot from 2019-07-05 11-54-18](https://user-images.githubusercontent.com/13755892/60730551-cf28c600-9f1b-11e9-80c2-9db8fcb13052.png)

![Screenshot from 2019-07-05 11-54-31](https://user-images.githubusercontent.com/13755892/60730560-d4861080-9f1b-11e9-8e7e-f220cdaef538.png)

this issue can be also related to https://github.com/fgl27/smarttv-twitch/issues/16

Thanks.

**Comment by Lutzy** [comment]
Sure, could absolutely be something that doesn't affect everyone, but for me this was a fresh install of Ubuntu in a VM (so no previous installs or likely conflicting dependencies) and then I followed the readme. I thought maybe I messed something up, so I blew away all Tizen things and the same thing happened again.

Anyway, I imagine it won't affect everyone, but hey, one more workaround to add to the

**Comment by scotttag** [comment]
This is completely broken in Tizen IDE Studio 5.0 now and not fixable with the above fix - it doesn't seem to be possible to build this any more, at least on Ubuntu IDE Studio

You get the invalid password error above on the certificate, and if you change the password in profile.xml and set chmod a-w - Tizen Studio refuses to build saying it cannot write to the profile file. If you create the (missing) .pwd files that the certificate manager creates with the correct passwords, it still errors out with the incorrect password error

Used to build fine on previous IDE versions. Unfortunately Tizen Studio also auto-updates itself once installed on Ubuntu - so even installing IDE 4.6 won't work as this auto-updates to 5.0 and breaks again before the first build

**Comment by Urban-M9** [comment]
> After wasting hours getting "Invalid password" errors every time I tried to build this project (or any project for that matter), I finally figured out what was going on. I'm leaving this info here so that you can either add it to the Readme or at least someone can find this Issue via Github search.
> 
> Basically, if you follow the Readme to a T using the latest Tizen Studio, your /profiles/profiles.xml will look like this:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <profiles active="strong" version="3.1">
> <profile name="strong">
> <profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/developer/tizen-developer-ca.cer" distributor="0" key="/home/ryan/tizen-studio-data/keystore/author/strong.p12" password="/home/ryan/tizen-studio-data/keystore/author/strong.pwd rootca=""/>
> <profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-ca.cer" distributor="1" key="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12" password="/home/ryan/tizen-studio-data/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.pwd" rootca=""/>
> <profileitem ca="" distributor="2" key="" password="" rootca=""/>
> </profile>
> </profiles>
> ```
> 
> But those .pwd files aren't ever created by the certificate manager and attempting to just put the correct passwords in plaintext in files with those names doesn't work. Instead, what you need to do is edit your profiles.xml accordingly:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <profiles active="strong" version="3.1">
> <profile name="strong">
> <profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/developer/tizen-developer-ca.cer" distributor="0" key="/home/ryan/tizen-studio-data/keystore/author/strong.p12" password="<yourStrongPasswordHere>" rootca=""/>
> <profileitem ca="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-ca.cer" distributor="1" key="/home/ryan/tizen-studio/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.p12" password="tizenpkcs12passfordsigner" rootca=""/>
> <profileitem ca="" distributor="2" key="" password="" rootca=""/>
> </profile>
> </profiles>
> ```
> 
> Finally, the stupid IDE will constantly attempt to overwrite these correct settings with its *.pwd garbage, so you'll need to do a `chmod a-w <tizen-studio-data>/profiles/profiles.xml`
> 
> Anyway, beautiful app, thanks so much for your work, but I'm hoping this will be helpful to anyone else that gets stuck using the latest Tizen Studio in Ubuntu.

I tried it but this still tries to override it anyway and I get " ERROR] Main.java(224) - java.io.FileNotFoundException: /home/tizen240/tizen-studio-data/profile/profiles.xml (Permission denied)" either i do Y or N
