### ISSUE TITLE
Feature request: Quick way to get to signed in user's profile 

### ISSUE THREAD

**Issue by ahendy** [fgl27/smarttv-twitch#47]
**Please describe the feature.**
Currently, I have to use the search function for my own name to look at my past vods. This is annoying.

Two options I see: 
1. Add the current user to the list of followers, then VOD content will be there.
2. Add this data to the user's page.

**Comment by fgl27** [comment]
OK.

**Comment by ahendy** [comment]
@fgl27 nice stuff!
