### ISSUE TITLE
Im Stuck

### ISSUE THREAD

**Issue by jokinha2015** [fgl27/smarttv-twitch#48]
Cant pass this step.. do not know these passwords.. any help guys?
![stuck](https://user-images.githubusercontent.com/54379849/63473127-41be1880-c46c-11e9-99a1-68329dd7334a.jpg)

**Comment by fgl27** [comment]
https://github.com/fgl27/smarttv-twitch/issues/16#issuecomment-489253873

**Comment by jokinha2015** [comment]
Thanks, i've made it!
