### ISSUE TITLE
All streams and videos come up as "has ended"

### ISSUE THREAD

**Issue by Steltek** [fgl27/smarttv-twitch#5]
**Behaviour**
No matter which stream I start or which video I try to play, I get a screen stating "XYZ has ended" "exiting in 3 ..." (and it counts down and exits). Clips seem to work though.

**To Reproduce**
1. Under Live or Videos, select any Live channel or video. (You can also select "Past Broadcasts" under Followed users, ...)
2. Click Play
3. Error pops up.

**Expected behavior**
Stream or video should play.

**Comment by fgl27** [comment]
Have you ever use the app before? So I know if this is new or you are new at using the app.
Can you open the site on yours network?and what a steam?

What are the information in the about of the app? (Key A or red -> about )

I need app version, tizen, tv and fw
the top two lines.

**Comment by Steltek** [comment]
First time using the app (not sure if it worked before).
App Version: 4.0.1.021319
Tizen Version: 4.0 | TV: QNQ9F | FW: T-KTM2DEUC-1202.3

(I tried sniffing the network traffic to see if there's anything obvious in there, but it's all encrypted to port HTTPS/443.)

**Comment by fgl27** [comment]
OK it worked for as long as I make it, I wanna to know if worked for you only...

The versions are OK at least on first look it should work.

I will need to see the logs...

To see the logs you going need you to install the application using the repo link and not the release download the bellow
https://github.com/fgl27/smarttv-twitch/archive/master.zip

The process is the same you just create another app in Tizen, and use the repo as **File System**.
And to install the app you click in "Debug as", to install it with debug enable...

It will open a new window from yours browser on the computer and in there the log will be showed...

After you press OK in the app screen to enable the logging don't change the screen stay in "Live", go to the console window in the computer, and press the key B or green in the remote, this will force the app to reload and show some information on the screen something like this:

![screenshot from 2018-11-28 13-43-52](https://user-images.githubusercontent.com/13755892/49163275-dd728c00-f313-11e8-9105-f58a9cc2084d.png)

After you see those logs try to replicated the problematic behavior.

Then share the logs result here in a text format you can drag a .txt file to the comment or make a new with the log...

After I may need some time and maybe change the app to generate more logs and from that we go.

**Comment by Steltek** [comment]
Here's the log from that.
[f2aea803-1b5c-4859-ae14-ad59c8c9e49c.txt](https://github.com/fgl27/smarttv-twitch/files/2891373/f2aea803-1b5c-4859-ae14-ad59c8c9e49c.txt)

Hope that helps. Let me know if you need anything else.

**Comment by Steltek** [comment]
I think I've located the problem (not tested yet). The app is trying to access http://user.ttvnw.net, but I have a redirect for *.ttvnw.net pointing to a local server, which redirects all HTTPS traffic to the actual site (via a specific line). The server is not set up to do the same for HTTP requests, and thus may be causing the 404 in the logs. I'm checking this right now.

**Comment by fgl27** [comment]
OK let me know the result.

**Comment by Steltek** [comment]
Yep, that's the problem. Twitch doesn't use HTTP anywhere, so it works fine with my HTTPS redirect when used in browsers and other apps, but since this app uses HTTP for that call, it hits the wrong server on my rerouting system and gets stuck there. (I'll have to rig up something that redirects the HTTP calls as well, I guess.)

**Comment by fgl27** [comment]
That link is from twitch official app, it didn't work with the HTTPS in the past.
I update the release to version 4.0.1-022119

Reopen the release app check if the version have change and try to play a a stream, to force update the app just hold the return key when it is open to force close it it update when reopened.

**Comment by Steltek** [comment]
Can confirm that using 4.0.1.022119 works here. Thanks for your work!

**Comment by fgl27** [comment]
You welcome, if need open a new issue (if is related to this just reopen this).

:+1:
