### ISSUE TITLE
Unable to connect error

### ISSUE THREAD

**Issue by Flatline9** [fgl27/smarttv-twitch#50]
**Describe what you need.**
I am currently stuck at: Setting up the build environment.

Once I attempt to connect my TV I get an error. Please see the screenshot.
I have double checked that I have everything installed properly and that my TV account is in Developer mode.
![connect error](https://user-images.githubusercontent.com/55036158/64480938-8a820b00-d1a8-11e9-988f-a96c22a02d2a.JPG)

**Additional context**
Add any other context or screenshots about this here.

**Comment by fgl27** [comment]
That is the ip and port that shows here

![image](https://user-images.githubusercontent.com/13755892/64481534-98895900-d1b3-11e9-9c4d-a3eadef93fc5.png)


when you click on scan?

if yes try to reboot the tv and the computer, the tv is needed power it off remove from the wall.

If that doesn't work I don't know exactly what can be, maye yours router or something related is blocking the communication check yours network configuration, sometimes is necessary to be on the same router, maybe you have more then one there connect both PC and TV on same and try again, things like that you can google two ip connection and etc to see what shows as help

a simple thing as a ping can you do, if not that is a issue.

![Screenshot from 2019-09-07 21-12-39](https://user-images.githubusercontent.com/13755892/64481570-62000e00-d1b4-11e9-9372-fbc00fa688d0.png)

let me know what you find...

**Comment by Flatline9** [comment]
I can successfully scan and find my device. The problem is when I select the "Connect" button.
I restarted my computer, and unplugged the TV.
I also went into my router and port forwarded the port that was needed in both TCP/UDP.
I disabled windows firewall.

After I attempted all these steps it did not work.

One thing that I will mention is that I am attempting all of the on Windows 7 64bit. I can see that this has only been tested on Windows 10 64bit.

**Comment by fgl27** [comment]
I don't thin os affects connection.

Are you sure about all steps before connect? Revise they

Setting up the TV as developer is demanding

When you open the APPS app does it show in red on the top "developer mode"?

**Comment by Flatline9** [comment]
Yes it does show "Developer mode".
From what I can tell I didn't have to do very much to place it into developer mode so that makes me suspicious
![devmode](https://user-images.githubusercontent.com/55036158/64481953-37b34e00-d1be-11e9-8cb9-b68dc86050b1.jpg)

**Comment by fgl27** [comment]
Redo that check the ip make sure is the same as the PC.

Router usually when dhcp server is enable give diff IP every connection so your PC ip may have changed after a reboot.

From what I can think noting else affects the connection.

**Comment by Flatline9** [comment]
Ok. Let me make sure this is correct.

The TV AND my PC have to have the same static IP Address?

**Comment by fgl27** [comment]
No read again the readme. You enable developer mode by adding the ip of the computer that will connect to the TV, that ip can't change until the app is installed.

In the computer that has the ip added to the developer mode you start a connection by scan then connect

**Comment by Flatline9** [comment]
Yeah I think I was at that step and completely botched it.
I'm certain this is my problem

**Comment by fgl27** [comment]
https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device

This link is there

**Comment by Flatline9** [comment]
I got it working! Thanks so much for your help
