### ISSUE TITLE
app wont install

### ISSUE THREAD

**Issue by ridoor** [fgl27/smarttv-twitch#52]
**Describe what you need.**
hi. i had 2019 samsung premium uhd
i reached all the way to end of guide for smart twitch app but when i press run  to install, nothing happens and nothing appears on TV, im sure i followed all the instructions. any help is appreciated

**Comment by fgl27** [comment]
are you doing exactly this

![image](https://user-images.githubusercontent.com/13755892/64911873-8486af80-d6fd-11e9-81fd-838da411cdd6.png)

you need to do exactly that, select the app folder, click the right mouse and click as on the picture.

if you are doing exactly that try to reboot (TV and computer) maybe something is stuck

**Comment by ridoor** [comment]
Yes exactly that.
After i press tizen web application, nothing happens at all.
On Sep 14, 2019, 8:41 PM +0300, Felipe Leon <notifications@github.com>, wrote:

are you doing exactly this

[image]<https://user-images.githubusercontent.com/13755892/64911873-8486af80-d6fd-11e9-81fd-838da411cdd6.png>

you need to do exactly that, select the app folder, click the right mouse and click as on the picture.

if you are doing exactly that try to reboot (TV and computer) maybe something is stuck

**Comment by fgl27** [comment]
does a reboot helps?

maybe you are missing something on the package manager

check if you have all of he bellow (see link) packages installed
https://github.com/fgl27/smarttv-twitch#bellow-imgs-showing-the-installed-packages-the-one-with-a-delete-option-are-installed

**Comment by ridoor** [comment]
I have all installed
On Sep 14, 2019, 8:47 PM +0300, Felipe Leon <notifications@github.com>, wrote:

does a reboot helps?

maybe you are missing something on the package manager

check if you have all of he bellow (see link) packages installed
https://github.com/fgl27/smarttv-twitch#bellow-imgs-showing-the-installed-packages-the-one-with-a-delete-option-are-installed

**Comment by fgl27** [comment]
If a reboot that I ask you yesterday to do didn't helped.

Start over, uninstall all and try again. Because I never had that issue reported.

**Comment by fgl27** [comment]
Open again if you wanna to work on the issue

**Comment by ridoor** [comment]
I have problem with app. I cannot watch any stream
Any stream i enter it says stream has ended exiting in 3..2...1
On Sep 23, 2019, 7:40 PM +0300, Felipe Leon <notifications@github.com>, wrote:

Open again if you wanna to work on the issue

**Comment by fgl27** [comment]
Works for me on any stream.

Check yours local network probably something related.

See this post https://github.com/fgl27/smarttv-twitch/issues/15#issuecomment-524453029

**Comment by ridoor** [comment]
Helo.
Any problem with app?
Stream keeps on stopping and buffering every few min.
Thanks
On Sep 30, 2019, 2:06 AM +0300, Felipe Leon <notifications@github.com>, wrote:

Works for me on any stream.

Check yours local network probably something related.

See this post #15 (comment)<https://github.com/fgl27/smarttv-twitch/issues/15#issuecomment-524453029>

**Comment by ridoor** [comment]
Hello.
May i ask why today all stream not working?
When i open any stream, i get “stream has ended , exiting in 2..1..”
Thank you

**Comment by fgl27** [comment]
> Hello. May i ask why today all stream not working? When i open any stream, i get “stream has ended , exiting in 2..1..” Thank you

Not the correct place to do so, this issue is for something else.

The app just works for me, so is a issue only on yours side

**Comment by ridoor** [comment]
What is solution?

**Comment by fgl27** [comment]
> What is solution?
> […](#)
> On Jun 29, 2020, 5:07 PM +0300, Felipe Leon ***@***.***>, wrote: > Hello. May i ask why today all stream not working? When i open any stream, i get “stream has ended , exiting in 2..1..” Thank you Not the correct place to do so, this issue is for something else. The app just works for me, so is a issue only on yours side — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Something that can't be reproduce can't have a solution.

Find what the proper issue is and fix it the share the solution

**Comment by ridoor** [comment]
U made the app
U should know how to fix

**Comment by fgl27** [comment]
What past of I can't reproduce the problem you don't get it?

The app is fine and working for me
