### ISSUE TITLE
Is the application still working?

### ISSUE THREAD

**Issue by ChungusAmongUs** [fgl27/smarttv-twitch#53]
**Describe the bug**
A few days ago, the application stopped working to view and watch streams. The application launches, shows the live streams and populates with live content, but when i actually click to watch a stream the loading icon displays and eventually says that the stream is now offline. If i go to my desktop PC, i can verify that the stream is infact live and not offline.

I've completely removed the application and reinstalled, but the same thing is happening. Everything launches and it shows live thumbnails and up-to-date information on who is currently streaming, but the streams do not actually play for me.

**To Reproduce**
1. Launch Application
2. Go to Channels Live
3. Select any channel
4. Loading icon displays
5. Eventually times out with error saying 'Stream has ended'
6. Returns to Channels Live page

**Expected behavior**
Expecting the stream to launch and play

**Comment by fgl27** [comment]
Works on here.

Check yours local network probably something related.

See this post https://github.com/fgl27/smarttv-twitch/issues/15#issuecomment-524453029

Maybe is related

**Comment by ChungusAmongUs** [comment]
Thanks for the reply, but it doesn't appear to be the issue. It works from my desktop PC, but not from my TV and they're both receiving the same DNS servers. Also, youtube, Netflix, Prime video, and all other streaming apps on the TV are working without issues.

I tried the suggestion in the previous comment by manually setting the DNS server to google's DNS (8.8.8.8), but that didn't seem to solve the issue.

I'm going to keep digging into my issue, and if it's working for others then it's definitely isolated to my app, but do you happen to have any other suggestions as to where to look?

**Comment by fgl27** [comment]
I have no idea what can be.

try to log this is how you do it... https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

share the full log result here maybe I can see something and help.

**Comment by fgl27** [comment]
Open again if you wanna to work on the issue
