### ISSUE TITLE
when pressing run like instructed I get an error stating "incompatible profile project requires tv-samsung profile, but target has none profile

### ISSUE THREAD

**Issue by EvilRoosterJr** [fgl27/smarttv-twitch#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable not demanding, add screenshots/picture to help explain your problem.

**Operation system (if is a installation problem):**
 - OS: Android
 - Version [e.g. 9, 8.1, etc...]

**Additional context**

**Comment by fgl27** [comment]
provide all information asked on the description of the issue included screen shots of the problem, and don't open a issue anywhere describing what you wanna/need on the title as makes no sense.

**Comment by fgl27** [comment]
If the problem persist post/comment here:

https://github.com/fgl27/smarttv-twitch/issues/16

with all proper necessary info.
