### ISSUE TITLE
Unable to view games list

### ISSUE THREAD

**Issue by rated91** [fgl27/smarttv-twitch#58]
When in the main screen if I go to “Games” to view the entire game list I get the error “Connection failed, unable to load content. Hit refresh to try again”. When refreshing the message still appears. Previously it was working fine, the issue started a few days ago.

I still am able to view followed games, live/all channels, clips, videos and the streams load fine. I have this issue with and without the ath key. Using Tizen on a samsung TV (2018 tv) and the latest version of smarttv twitch (4.0.1 v3)

Does the app update automatically of do I need to manually update?

If you need more info please do not hesitate to ask.

**Comment by fgl27** [comment]
If you install the correct zip it auto updates

![image](https://user-images.githubusercontent.com/13755892/67054694-ca2f0180-f11b-11e9-9bdf-3d42a9115d2e.png)

the correct one is that with only 12.8KB

I don't know why some user have this issue as I don't.

But is a know problem from twitch servers 
https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/4

No solution it must come from they side no need for app updates.

My question is do you have the issue all the time?

**Comment by rated91** [comment]
Ahh yes that is the one I installed so it should be fine.

For me the problem keeps occurring the entire time for at least a week or so now. All the other functions are working fine. May have something to do with the UI changes twitch has released. Since all other functions are working correctly I figured reïnstalling the app won't make much of a difference if it's and API/Server issue so I haven't tried that.

**Comment by Thares-cc** [comment]
i've installed the correct version as well and i'm getting the same error since a week. re-installing doesn't help either.

**Comment by fgl27** [comment]
I push a workaround, the new app version is 4.0.1.101819  check it in about, force close the app so it can update.

The workaround is to use a "not finished" new twitch api, that works but does not provide the same result, so now for those with 410 errors the app will load the new api the difference is visible you will not see the total live channel and viewers, just the game name.

When the old api gets fixed the app will just use it and the value will be visible.

Let me know if works.

**Comment by Thares-cc** [comment]
> I push a workaround, the new app version is 4.0.1.101819 check it in about, force close the app so it can update.
> 
> The workaround is to use a "not finished" new twitch api, that works but does not provide the same result, so now for those with 410 errors the app will load the new api the difference is visible you will not see the total live channel and viewers, just the game name.
> 
> When the old api gets fully fixed the app will just use it and the value will be visible.
> 
> Let me know if works.

thanks, how do you "force close" the app on a samsung TV? i haven't seen a function to completely close it

**Comment by fgl27** [comment]
hold back/return key, check controls dialog

![image](https://user-images.githubusercontent.com/13755892/67103283-33a22500-f19b-11e9-9d23-f967d6e8d9d3.png)

**Comment by Thares-cc** [comment]
Still not working. Now, when you select „games“ the loading indicator keeps spinning and app does not react to any input, you need to force close it

**Comment by fgl27** [comment]
Try again after force closing the app. let me know

**Comment by rated91** [comment]
For me it works now. Only the games list does not show the live channels/viewers anymore but the game list loads and the channels work.

Thanks!

**Comment by fgl27** [comment]
The day twitch fix the api, the values will show again then you guys come here and let me know it's showing again.

Will leave this open until all is OK.

**Comment by Thares-cc** [comment]
yes works.

**Comment by fgl27** [comment]
Someone shared a workaround to prevent the issue in the dev forum
https://discuss.dev.twitch.tv/t/410-gone-on-v5-games-top/22835/6

Let see if now the game screen always return OK, and show not just the game name but the viewers and channels live status.

**Comment by fgl27** [comment]
@Thares-cc and @rated91 did you notice the viewers and live channel not showing after this update two days ago?

I don't see the issue anymore I guess is all perfect after the improves.

Let me know.

**Comment by rated91** [comment]
I’ve just checked it and the viewers/channels are showing up like normal.

Thanks for all the help!

**Comment by fgl27** [comment]
If the problem shows up again let me know here...
