### ISSUE TITLE
Menus Unreachable, and Cannot Scroll Left

### ISSUE THREAD

**Issue by Zellidon** [fgl27/smarttv-twitch#59]
**Describe the bug**
This new update is just straight unusable on my Samsung UE55MU6449. When I'm scrolling through the list of streams if I try to go back to the left it opens the panel for followed streams. Then the main menu gets hidden and all the text is cut off. Is there some way to go to the previous version?

**To Reproduce**
1. Try using the app for anything.

**Expected behavior**
Being able to scroll left, and read menus.

![15717370105258770265187903702552](https://user-images.githubusercontent.com/18412234/67274234-50529b80-f4c0-11e9-9854-9c68315e5c07.jpg)

**Comment by fgl27** [comment]
The app is OK you can open it on any browser using this link and test

https://fgl27.github.io/smarttv-twitch/release/index.html

The key #1 is the back/return key on a browser

If you desires to use a old version of the app, you need to clone the repository, reset the head of the repo to a desired point and instal, but that installation will never ever received a update and can stop working.

the commit to use to reset the head is this
https://github.com/fgl27/smarttv-twitch/commit/b6bfa4340277ba9724625a15f5761b5c66d98142

the sequence of commands on a linux machine is

	git clone https://github.com/fgl27/smarttv-twitch
	cd smarttv-twitch
	git reset --hard b6bfa4340277ba9724625a15f5761b5c66d98142

**Comment by fgl27** [comment]
But I believed that the problem is fixed so you can just force close the app and see if all works

**Comment by Zellidon** [comment]
Interesting the web page does work fine, but it doesn't work on the TV. I'll try to reinstall and let you know what happens. Thanks.

**Comment by fgl27** [comment]
as I wrote before

> But I believed that the problem is fixed so you can just force close the app (hold back) and see if all works.

After all updates have already be pushed to solve the issue force closing the app and reopening it updatesit, but if that doesn't help reinstall must solve as the page is just fine.

**Comment by Zellidon** [comment]
Yes sorry for the late reply. I uninstalled and reinstalled the app completely and now it's working correctly. Thank you for doing all of this!
