### ISSUE TITLE
Carregando eternamente......

### ISSUE THREAD

**Issue by jhonpetter** [fgl27/smarttv-twitch#6]
Ola amigo este app funciona normalmente na minha 55un6100 2016, porem desde fevereiro nunca mais pegou, coloquei a ultima versão, porem as lives não carregam de jeito nenhum, somente videos e clips rodam.
Fiz debug e só carrega o arquivo m3u8. depois disso fica so dando que esta preparando o avplayer, e fecha a live sem rodar nada.
Oque pode ser? 
***Obs testei os m3u8 no vlc player e está rodando liso.
![Capturar](https://user-images.githubusercontent.com/20495715/56005838-d63b9180-5ca8-11e9-854a-b512585c56b5.PNG)

**Comment by fgl27** [comment]
Esta tudo ok, então assumo que tu não baixou o arquivo correto.

faz o download da ultima versão do release e instala o release e não o repositório.

https://github.com/fgl27/smarttv-twitch/releases/tag/4.0.1_V2

tem de baixar o zip com nome **4.0.1_V2.zip** 

e tudo deve funcionar

como tu pode ver na imagem abaixo, os links do twitch tem https os teus não ou seja versão velha que não deveria estar sendo usada e os link com somente http não funcionam algumas redes que bloqueio estes tipo de acesso:

![Screenshot from 2019-04-12 11-52-26](https://user-images.githubusercontent.com/13755892/56046551-e0e23f00-5d19-11e9-969e-88a8ded6e212.png)

**Comment by fgl27** [comment]
Me avisa como ficou apos instalar o zip correto.

**Comment by jhonpetter** [comment]
agora tá pegando + demora para carregar e fica dando live offline, + se não pegar de primeira umas tres tentativas depois funciona.
antigamente era mais rapido full de boas, neste ano o app não tá + a mesma coisa mais acho que é culpa da ultima atualização da samsung de 11/2018. depois dessa att nem no navegador a twitch pega mais.
tá funcionando, as vezes da uns bug de não carregar a live + tá de boas.
Vlw irmão, seu app é d++

**Comment by fgl27** [comment]
Aqui ta  sempre esteve perfeito nunca trava ou fica lente desde que a internet esteja OK.
deve ter algo ruim na tua internet ou na conexão da TV com a tua internet.
verifica isso.

**Comment by jhonpetter** [comment]
minha tv é uma um6100, conectada a cabo 200Mbs, assisto filmes em 4k tanto netflix como youtube sem problemas
Testei 👍 
function play(){
	  	
	  	webapis.avplay.open('https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CtUDFFqWeSxkiohLrJdoEvLNN3D4oRxQtX8bdfjQ1n01ljhR2y5qUWS0nBNAK9uUn-eQbLaxdP6D1i2RXsY2LUnp7iMnJzX8gDb5CfkiRBWT5-ULndiZAYAZ2O2sL7cVIGS4-osDp5AE30pMxKytXDyImqRuhSXKdDiznzuNLwJDN9AYB4zErlFzGsIDEVmV_tHBcwx25xxMwNNXQ061GEjwfNUxeg7KzAYH0vXxGXWikzCfpa9dWtZt_IjbU2SmW-yTrylYrMDS5TsWyxjTG2WemesrWN7rQaB1mMN-NlN5hMG_XNHXyKchXL1U53ruRRhf8xmo1h8haslXCgobRRopQUo34GXUddG3LjOVd6cR6O2q78mV2vFoAmREt-sODK3ZHQ5tyAasc2M9jcIeorjdDB41ZtZ9axzNXD3iBmNvPlN2SlMqkywR-ETddTej6kA7yEIBW92Ap248erd-VnLNaXvmzu0DpWLO7_O8i3ipXx-Ce-QrD5p1Dft6xrl2YPPwtPUPB1JqqaeRpL7n1LA04vbiIx_VWWRoy2b0x9h5FOIeQ4y1jgjgerUfXmcSGQNrNNS3hWc_jNU55H0r1NF6o3RVHDHQKSI7aEZy2VZdnycwcssHQxIQRocAIcfQ4J84T5YsTHoqcxoMoPvS2vwva3HK4MlY.m3u8');
	  	var bitRateString = 'BITRATES=2000~10000|STARTBITRATE=HIGHEST|SKIPBITRATE=LOWEST';
        webapis.avplay.setStreamingProperty('ADAPTIVE_INFO', bitRateString);
        webapis.avplay.setDisplayRect(0, 0, 1920, 1080);
		webapis.avplay.prepare();
		webapis.avplay.play();
}
e roda liso e na hora, mais no app não, desisto deixa assim ta funfando tá valendo

**Comment by fgl27** [comment]
netflix e youtube não é live stream?

testou live stream no youtube?

tem TV que tem bug de live stream, pois a unica diferença entre um video e uma live é a designação de live que contei dentro do arquivo m3u8.

teu teste tu não usou o método de carregar o video de forma assíncrona eu uso no app pois este método funciona melhor, mas tenta sem

baixa o repositório daqui
https://github.com/fgl27/smarttv-twitch/archive/master.zip

muda este bloco
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Play.js#L679-L683

	    Play_avplay.prepareAsync(function() {
		Play_avplay.play();
		Play_Playing = true;
		if (Play_ChatEnable && !Play_isChatShown()) Play_showChat();
	    });

para 

	    Play_avplay.prepare();
	    Play_avplay.play();
	    Play_Playing = true;
	    if (Play_ChatEnable && !Play_isChatShown()) Play_showChat();

instala e vê o que acontece.
