### ISSUE TITLE
Black screen after hitting return button during stream playback

### ISSUE THREAD

**Issue by Thares-cc** [fgl27/smarttv-twitch#62]
**Describe the bug**
Sometimes, after hitting the "back" button on the remote while watching a live stream, the app won't return to the main menu but will instead show a black screen and not react to inputs anymore. If force closed, the previous stream is re-opened and can be watched, but hitting return will only show a black screen again. 

**To Reproduce**
1. Open a live stream
2. Hit the "back" button on the remote
3. Sometimes, the app does not return to the main menu but shows a black screen instead
4. Force close app by holding down back button
5. Open app again and notice the previous stream playing
6. Hit "back" again and notice black screen

**Expected behavior**
Returning to the main menu from a stream should not show a black screen.

**Operation system (if is a installation problem):**
 - OS: Samsung UE7002

**Additional context**

**Comment by fgl27** [comment]
This issue was addressed and resolved on #60.

the last app version is App Version: 4.0.1.102919 on that no issue.

If you are on that app version post on issue #60 so I can reopen and work on it.
If you aren't on that app version hold key return so the app force closes and updates.
