### ISSUE TITLE
New Layout Streams buffering?

### ISSUE THREAD

**Issue by Diamond1337** [fgl27/smarttv-twitch#63]
Hi, i saw there was an visual Update for this app on my TV. Thank you for your service you have done a great job!

I wondering if someone else notice a stream buffering here and there. I have my tv connected with LAN and i got 100mbit on the TV. But sometimes the stream freezes and itseems to buffer and then reload the stream. Anyone else recognize this?

Thank you for an answer

**Comment by fgl27** [comment]
Twitch lags, doesn't depends on how good or high yours bandwidth is if it lags it lags, can also be a problem on yours internet provider in relation to Twitch servers they may not have a good bandwidth and some times that can lag.

Just search on the internet twitch buffer issues that you will find it all over.

You can controls the buffers values from settings test differents values and see what improves, if is lagging is not recommended to enable low latency that you can enable from the player it self keep that on (Disable).
