### ISSUE TITLE
JDK + tizen?

### ISSUE THREAD

**Issue by MantaDroid** [fgl27/smarttv-twitch#64]
**Describe what you need.**
Hi,

I'm trying to follow your guide on how to install the Smarttv Twitch app onto a samsung TV but this Tizen studio software doesn't want to run no matter what version of Java I'm installing. I feel like I've tried 4 different versions. I can't even properly uninstall the Tizen software because the uninstaller doesn't run without the JDK that it keeps asking for.

Here's an imgur of what error I get when trying to run the software - 
https://i.imgur.com/LyrT6PU.png

I've tried removing the software, tried uninstalling the javas, tried restarting the computer after each step etc.

Going mental here, I just want Twitch on my TV. 

**Additional context**

I should probably reach out to Tizen aswell. Just frustrated.

**Comment by fgl27** [comment]
Not a windows user.

Try to search ways to determinate what is the java version a you installed more then one things are probably conflicting, when yours java version became 8 you are OK.

I don't know how to again not on windows... google it until you manage.

**Comment by MantaDroid** [comment]
So weird though because I specifically try using the one you've linked here: https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I guess I should try and ask Tizen. Such a shame because from what I can see on the images the UI seems sweet.


Isn't there any other way to install your app on the samsung TV?

**Comment by MantaDroid** [comment]
@fgl27 

I somehow managed to solve it. I tried uninstalling everything once again, then I manually went into environment variables in my PC and set up the directory of it.

Basically went from this image - https://i.imgur.com/LyrT6PU.png

Googling around and followed these direct instructions - https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/

Idk why but I kinda assumed that step would be more automatically fixed while doing all the installations. Maybe they're supposed to, but in my case I had to do it all manually.



Now I just hope that the remaining steps will work smoothly. Just wanted to update in-case someone else encounters similar problem because I had trouble figuring out exactly what step was the issue as I generally don't do these kind of installations.

**Comment by fgl27** [comment]
> Isn't there any other way to install your app on the samsung TV?

Not that I know of for un-released app, has Amazon don't wanna a Twitch app this app can't be released on the Samsung store...

I assume as you are using a updated version of windows in relation to the one I tested the app with, because it was 2 3 years ago for me, you probably can use latest version of Java 8, making sure is Java 8 all must work, probably those issue related to installing java will not be there as the updated version of the sdk must deal with all the odd issue that you had, after all I didn't get those on the past and they must be related to windows/Java changes.
