### ISSUE TITLE
TV Packages not available in Main SDK from Package Manager

### ISSUE THREAD

**Issue by ldioten** [fgl27/smarttv-twitch#65]
**Describe the bug**
Following your guide, I was not able to install any packages in the Main SDK tab related to TV. Only packages for Wearables and Mobile is showing.

I went ahead and did the whole app installation anyway, but when running the app from Tizen studio, it just results in an error stating "Closed". I was able to succesfully install the "Web app. development" and "Emulator" packages from the Extension SDK-tab which allows me to run the application in Emulator-mode on my pc which seems to work fine (it just loads but returns no error). 

**To Reproduce**
1. Install Tizen Studio 3.5
2. Open Package Manager
3. Any packages for TV is missing

**Expected behavior**
I expected the TV packages to be available and the app to run on my TV after running it from the studio application :-)

**Screenshots**
https://i.imgur.com/bI5A7Nf.png
https://i.imgur.com/x4p0OEJ.png

Please notice that in these screenshots, Tizen has been re-installed and I haven't yet added the packages. Awaiting further instructions before I proceed...

**Operation system (if is a installation problem):**
 - OS: Windows 10 Pro
 - Tizen Studio 3.5
 - TV: Samsung UE55NU6035
 - TV: Tizen 4.0

**Comment by fgl27** [comment]
I have this now...

![Screenshot from 2019-11-03 09-59-50](https://user-images.githubusercontent.com/13755892/68085544-c4763300-fe20-11e9-8370-20b7276a498e.png)

Proceed with the process if you can't install the app with available packages report a issue showing the problem and what you manage to install and what is available to install in package manager.

**Comment by fgl27** [comment]
I push a new release to be used with Tizen SDK 3.5

redownload it from here

https://github.com/fgl27/smarttv-twitch#setup-the-application

**Comment by ldioten** [comment]
Thank you for quick response. That's very impressive!
I'll try it out.

**Comment by ldioten** [comment]
It works! You're brilliant. Thanks!

It did throw an error log right after importing your latest release (but I actually think it did it before as well). Anyway, it's running from my TV right now. I absolutely agree with all the comments I've read about it. It's lightning fast and so much better than the old, unofficial app.

![image](https://user-images.githubusercontent.com/16353339/68092340-69792600-fe8a-11e9-9c86-8a6055976455.png)

Thanks again!

**Comment by itsthe1-apps** [comment]
Hvaing the ave issue

**Comment by ashwaniRoshan** [comment]
tv package is not showing for mac
