### ISSUE TITLE
Couldn't connect to tv

### ISSUE THREAD

**Issue by thayr0ne** [fgl27/smarttv-twitch#66]
When trying to launch remote device manager, i'm abble to find my tv, but i cant connect to it.
It says 'failed to connect to mytvip'
Is there any way to make it work?

**Comment by fgl27** [comment]
recheck this step
https://github.com/fgl27/smarttv-twitch#account-and-downloads

make sure **developer mode** os showing as enable in the apps app

**Comment by thayr0ne** [comment]
Man, thank you so much.
It worked and I'm actually amazed at how good this app is...
Way better than the AndroidTV app...

Do you happen to know if there's anything like your app but for using Crunchyroll?
Thank you anyway

**Comment by fgl27** [comment]
You welcome.

Unfortunately at this moment is not on Twitch priority to make good application (I assume it never ever was) they focus seems only on others things as keeping they most successful streamers happy and streaming on they site :stuck_out_tongue_winking_eye: , hope someday they make good apps after all a billion dollar companies should be able to I guess :grin:.

This app also has a Android TV version https://github.com/fgl27/SmartTwitchTV and is a little better then the Samsung version as the AndroidTV OS is way better than the Tizen, allows to add more featurings and has a better performance on most devices.

I never used **Crunchyroll** so I can't help...

Enjoi it.
