### ISSUE TITLE
I can't download the TV sdk in the Package Manger (not showing it)

### ISSUE THREAD

**Issue by IdrilDevelop** [fgl27/smarttv-twitch#70]
Hello,

im using the Tizen Package Manager and I am at this point:

"Main tab (Main SDK) Install 5.0 TV(or wherever X.X TV version there is) and Tizen SDK tools, (on Linux it may request you to use apt-get to install missing dependencies)"

But the SDK for tv isn't there :( Anyone could help? Thanks!

Im using the latest version(macOS).  Also, I tried to do the next steps without that but I cant put the toggle button "ON" when the IDE show my device . Maybe because of that?

<img width="626" alt="Captura de pantalla 2019-11-09 a las 21 31 49" src="https://user-images.githubusercontent.com/33942836/68534762-7c7f7080-0338-11ea-8106-dedf48d183ed.png">

**Comment by fgl27** [comment]
> Im using the latest version(macOS). Also, I tried to do the next steps without that but I cant put the toggle button "ON" when the IDE show my device . Maybe because of that?

I don't think is related, you can see here
https://github.com/fgl27/smarttv-twitch/issues/65

after tizen update we had that issue but me and that user manage to use the sdk.

So you must be missing something else maybe this

https://camo.githubusercontent.com/d42f7ee7904ce1e6795957f6569bc423781fb938/68747470733a2f2f66676c32372e6769746875622e696f2f736d61727474762d7477697463682f73637265656e73686f742f696e7374616c6c2f73646b5f332e706e67
![image](https://user-images.githubusercontent.com/13755892/68543618-3e199e00-0398-11ea-9d20-2a8843f8b25f.png)

If not go back to this step
https://github.com/fgl27/smarttv-twitch#account-and-downloads

and redo until is all OK in the app apps.

If that doesn't help, tru to see if somewhere in the sdk you can read why you can't connect there is probably a error showing.

**Comment by MarcoV1980** [comment]
I had the same problem with 3.5, just install the TV 5.0 extensions and click the new project icon top left, then you get the wizard as shown in the helpfile.

My problem was that importing didn't go well, it imported the file instead of the contents, so I had to manually unpack them, overwrite them in the project directory and then run the project. 

Then it all worked fine

**Comment by fgl27** [comment]
closed due to inactivity.
