### ISSUE TITLE
View subscriber only VoDs

### ISSUE THREAD

**Issue by OllieStubley** [fgl27/smarttv-twitch#81]
Currently it does not seem that subscriber only VoDs can be viewed through the app. When will this feature be added? It is my main reason for Twitch on my Samsung TV.

**Comment by fgl27** [comment]
Are you receiving a warning, informing about the lost featuring? For third part apps.

**Comment by OllieStubley** [comment]
Yes, I receive an error stating that watching subscriber only videos is currently unsupported on the app (though I am a subscriber to the channel)

**Comment by fgl27** [comment]
I'm not Twitch you know that? I assume you do...

So is a Twitch issue they decide block the access, they can do wherever they wanna with they APIs, from what I have read about I assume that this measure is to stop spammer bots and things related and will not work again, there is a small chance it does get back but at this point I don't think so.

This is related to
https://github.com/fgl27/smarttv-twitch/issues/68
https://github.com/streamlink/streamlink/issues/2680

and there is only one know workaround
https://github.com/streamlink/streamlink-twitch-gui/issues/682#issuecomment-554757512

Using that workaround may be see as breaking ToS
https://www.twitch.tv/p/legal/developer-agreement/

more about it here
https://github.com/streamlink/streamlink/pull/2692

that means basically if you do use a similar workaround you can lose yours twitch account, other then this app stop working not just for SUB VOD but for anything else.

So do you wanna use that workaround?

**I can fix the app if Twitch decide to block it all, but if yours or anyone else lose your personal account I can't fix that.**
