### ISSUE TITLE
Black screen after insallation

### ISSUE THREAD

**Issue by outcore1** [fgl27/smarttv-twitch#82]
Well I have done everything on the tutorial, I have managed to send the app into the smart tv, but  once it starts all I get is a black screen, any ideas?

Thankyou.

**Comment by fgl27** [comment]
No. you also didn't follow the issue template NICE.

Install as a new project as I describe here 
https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

After share the log information that shows where the crash is..

**Comment by outcore1** [comment]
Ok thankyou so much for replying, I will try that and get back to tell you the outcome

**Comment by outcore1** [comment]
OMG Thankyou, you guys that developed this are the best... So I have installed both the master and the release and it works perfectlly, thankyou so mucho for your help, I think we can close this thread now.

**Comment by fgl27** [comment]
both work just fine?
are you sure? can you check the version of the release in the about of the app and let me know what it says, and does it says anything in red text?

**Comment by outcore1** [comment]
Alright so it says the following:

SmartTV Client for Twitch
APP Version: 4.0.1.111519
Tizer Version:  3.0 l TV: UMU6100 l  FW: t-ktmakuc-1270.3

Nothing on red text, everything seems normal white text.

**Comment by fgl27** [comment]
OK don't know why it fails before then... you are running the correct version is all fine.

:+1:
