### ISSUE TITLE
Release creation is bugged

### ISSUE THREAD

**Issue by mimagind** [fgl27/smarttv-twitch#85]
[release_4_0_1_V4.zip](https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V4/release_4_0_1_V4.zip) contains this in index.html:
`<script src="$WEBAPIS/webapis/webapis.min.js" defer>`
The result is black screen on startup.

Running the git master branch code directly works fine.

**Comment by fgl27** [comment]
release html
https://github.com/fgl27/smarttv-twitch/blob/master/release/index.html#L44

source html
https://github.com/fgl27/smarttv-twitch/blob/master/index.html#L1768

same line same script how that is a issue?

Share a log of the release so I can see why it crashes. Instruction how to log is on the **"Bug report"** template that you didn't fallow.

**Comment by mimagind** [comment]
I did follow the template.
There are no steps to reproduce because there are no steps that can be done on a black screen.
The instructions to get a log don't work either. Nothing shows up in the console.

**Comment by fgl27** [comment]
No see this is missing...

>  Operation system (if is a installation problem):
>  
>  OS: Windows, Linux or ...
>  Version [e.g. 10, 18.4, etc...]
>  Device:
>  
>  TV Model: UN40KU6000H, EH5000 or ...
>  Os version [e.g. Tizen 2.3, Tizen 2.4, Tizen 5...]
>  
> Additional context Add any other context about the problem here.
> 

+ log information you don't show I need to see things I'm not there to help you...

Then if nothing shows what is the answer for the question...

**same line same script how that is a issue?**

I don't know what happen... probably something on the creation of the app, if noting fail maybe is all empty there is not app there, is all blank included the app content...

when the app is successfully installed in a debug mode you must see something like this

![Screenshot from 2019-12-04 23-12-48](https://user-images.githubusercontent.com/13755892/70197813-c404dc80-16eb-11ea-8a87-64ecef39455f.png)

![Screenshot from 2019-12-04 23-13-15](https://user-images.githubusercontent.com/13755892/70197822-ccf5ae00-16eb-11ea-97b4-cbb165357f25.png)

so on the resource window what is there for you, any content is loaded?

**Comment by fgl27** [comment]
this issue was probably fixed on https://github.com/fgl27/smarttv-twitch/issues/86

**Comment by mimagind** [comment]
What use is the TV model or Tizen version if the git master branch version works perfectly fine?
The TV model is UE40KU6402 which [seems](https://developer.samsung.com/tv/develop/specifications/tv-model-groups/) to be Tizen 2.4.

When launching in debug mode it shows an alert box with this text scrolling:
`RWI mapping info 7011: <the Tizen application id from config.xml> 7012: N/A 7013: N/A`
I tried pressing the B extra button both before and after dismissing this alert but still nothing in the console.
![console](https://user-images.githubusercontent.com/20630344/70256722-a5592100-1791-11ea-80c3-d843d02d5ea2.png)
![scripts](https://user-images.githubusercontent.com/20630344/70256724-a5592100-1791-11ea-9684-e443d1b0df8f.png)

**Comment by fgl27** [comment]
You can open the app that works and go to about and get the full device info, TV model and FW plus Tizen version.
I don't think is Tizen 2.4...

The key B is not mapped on the release version is only for debug as pressing it it can cause a app crash and that is not welcome on a release version of a application.

No content from github is loaded in yours screenshot, as you can see on my previously picture there is a few files...

A script master.js
A few fonts, icons.woff and etc

So there is a few reasons for this issue, the app is be installed bugged for some local reason on yours machine and those file aren't be called some how or yours network or TV is blocking it from load.

So what is the content of that index.html file from the resource window?
When you click on that fille on that window you must be able to see the content...

can you open this links on yours TV?

https://fgl27.github.io/smarttv-twitch/release/githubio/css/font-awesome.min.css
https://fgl27.github.io/smarttv-twitch/release/githubio/css/master.css
https://fgl27.github.io/smarttv-twitch/release/githubio/js/master.js

I mean litley on the TV on its browser, as the TV may not be able to download the file by something on it or on yours network.

**Comment by mimagind** [comment]
App version: 4.0.1.112319
Tizen version: 2.4.0
TV: UKU6400
FW: T-JZMDEUC-1241.5
All three links were opened successfully by the browser on the TV.

**Comment by fgl27** [comment]
then I don't know way this happens
https://user-images.githubusercontent.com/20630344/70256724-a5592100-1791-11ea-9684-e443d1b0df8f.png

**Comment by mimagind** [comment]
I fixed the problem.
The instructions are wrong, not the package.

Creating a new project and then using Import Filesystem doesn't seem to work as expected.
Instead, I deleted the contents of the project directory in Tizen Studio workspace and replaced it with the contents of the release archive.

**Comment by fgl27** [comment]
Maybe for you or maybe as I wrote before there is something odd on yours PC or you didn't understand the process, I personally did the installation dozens of time and always work.

This app has thousands of installation and very few come to git post a issue, so the process works.
