### ISSUE TITLE
Cannot install properly on TV

### ISSUE THREAD

**Issue by MikkelAJ** [fgl27/smarttv-twitch#86]
After a few other problems I finally got to the part where I install the app on the TV. All looks good, I do the step Run As -> 1. Tizen Web Application and on the TV screen it says Twitch loading (I named the project Twitch). After a little while the loading screen disappears and I can see the Icon Smarttv Twitch in my apps. However it cannot launch. It does not launch by itself, when done and nothing happens is I click on the app. 

Pressing the Reinstall button in the appstore gives me an error (Unable to install. Please try again later. (Twitch: 52))

I have tried uninstalling, deleting and reinstalling Tizen Studio.
And I have never had another twitch app installed on the TV.

I hope you can hel :) 
Thanks in advance

**Comment by fgl27** [comment]
If you don't follow the proper issue template I can't make any relation on this issue in relation to others.
Seems related to https://github.com/fgl27/smarttv-twitch/issues/85

Maybe to a older one, but no one cares to share simple information and share a simple log screenshot.

Install the release app again but this time in debug mode

![image](https://user-images.githubusercontent.com/13755892/70235308-7dda6800-1741-11ea-976d-06739afee5e0.png)

After the app installation t auto starts and a browser windows shows up show me the information of this windows.

![image](https://user-images.githubusercontent.com/13755892/70235370-99457300-1741-11ea-83f0-17fec885e2ea.png)

![image](https://user-images.githubusercontent.com/13755892/70235378-9cd8fa00-1741-11ea-9f06-c2a082190b70.png)

on the resource window click to open the folder to show the same as I share.

**Comment by MikkelAJ** [comment]
I did not previously have a black screen, it just did nothing when I tried to open it. Now it is a black screen like the issue you linked.

**Comment by MikkelAJ** [comment]
I did not previously have a black screen when opening the app, instead it just did not do anything. Now there is a black screen like the issue you linked.

Here is a picture of the console 
![image](https://user-images.githubusercontent.com/56154145/70238706-1b499200-176a-11ea-8c8c-931571afde1a.png)

My window does not look exactly like yours, but I think this is what you want me to show:
![image](https://user-images.githubusercontent.com/56154145/70238837-6794d200-176a-11ea-9cf8-c7c51b30dccf.png)

**Comment by fgl27** [comment]
what is the full information of that line that is "cut"

the one that starts with "stack:"

**Comment by MikkelAJ** [comment]
Here:

stack
:
"SecurityError: Permission denied↵    at NativeManager.getErrorObject (<anonymous>:1:23480)↵    at Utils.checkPrivilegeAccess (<anonymous>:1:6907)↵    at TVInputDeviceManager.registerKey (<anonymous>:1:3921)↵    at https://fgl27.github.io/smarttv-twitch/release/githubio/js/master.js:1:66496"

**Comment by fgl27** [comment]
OK that doesn't help much, I have added extra log information on the function that registers keys.

Repeat the process show me what the result is now...

**Comment by MikkelAJ** [comment]
It seems to be working as it should on my tv now!
Thank you so much for your time - I am looking forward to using your app

Here is the console anyway (hope you can read it - I had to zoom out to get everything)
![image](https://user-images.githubusercontent.com/56154145/70242047-69619400-1770-11ea-8d91-6e0322f2fec3.png)

**Comment by fgl27** [comment]
All extra key fail to register, so you can use the app but that will not be a OK experience as the app uses those extra key to give you a better experience... even tho it works only with the d-pad...

So I made this new zip to see if the issue is now solved

try install the app the same way in debug mode but using that zip as its content. you need to start a new project in tizen for this to work properly.

[release_new.zip](https://github.com/fgl27/smarttv-twitch/files/3927188/release_new.zip)

**Comment by fgl27** [comment]
as this as privileged issue and is unknown way it happens on some TVs, is necessary to properly fix as there may be some app featuring not working do to missing permission...

So if that zip fix that issue, we OK, if not we must investigate why it fails...

**Comment by MikkelAJ** [comment]
So you want me to install a new version to see it is a fix?

**Comment by fgl27** [comment]
yes install that release_new.zip show me the log

**Comment by MikkelAJ** [comment]
This gives black screen on TV as well

![image](https://user-images.githubusercontent.com/56154145/70243484-ec83e980-1772-11ea-8f38-a9642325c558.png)

**Comment by fgl27** [comment]
I see I fix that... but the test remains the same it fails...

Maybe the keys can't be registered from a file from the web...

So I will make a new zip that registers key locally to see what happens

I share it in a few...

**Comment by fgl27** [comment]
please test this...
[release_new_2.zip](https://github.com/fgl27/smarttv-twitch/files/3927464/release_new_2.zip)

show me the log result

**Comment by MikkelAJ** [comment]
That seems to work too!

I wont be able to test anymore until tomorrow

![image](https://user-images.githubusercontent.com/56154145/70247949-7edbbb80-177a-11ea-8143-fe69f805855a.png)

**Comment by fgl27** [comment]
Yes all works I made two options of the function and they all now works but the version 2 (2Registering...) isn't needed, so isn't need a new zip, you can use the one you already have installed no problem, but the old **release_4_0_1_V4.zip** will also work just fine.

Thanks for the help.
