### ISSUE TITLE
Tizen Studio Remote Device Manager won't connect?

### ISSUE THREAD

**Issue by jpalojarvi** [fgl27/smarttv-twitch#87]
When clicking Scan it finds the TV fine, but after trying to Connect it gives me this error: https://i.imgur.com/2HVNKdg.png

The Samsung guide @ https://developer.samsung.com/tv/develop/getting-started/using-sdk/tv-device was no help either. Any advice?

Thanks!

**Comment by fgl27** [comment]
go back to here
https://github.com/fgl27/smarttv-twitch#account-and-downloads
after here
https://github.com/fgl27/smarttv-twitch#setting-up-the-build-environment

redo those and see what happens. you need to enable **developer mode** on the TV to connect, on that first link there is the full Samsung tutorial about it.

**Comment by fgl27** [comment]
closed due to inactivity.
