### ISSUE TITLE
Installation seems to go through but blank black screen

### ISSUE THREAD

**Issue by oldnavyshel** [fgl27/smarttv-twitch#89]
I need some help. I followed the instructions to a fault and it just won't install. I just get a black screen and nothing happens.

**Comment by fgl27** [comment]
You probably didn't get success on this step
https://github.com/fgl27/smarttv-twitch#setup-the-application

mostly this image
**Top menu > File > Import > General > File System ... next > Browse.. to find the extracted folder from the release_X_X_X.zip ... > click Select All, mark Overwrite existing ... > Finish**
![image](https://user-images.githubusercontent.com/13755892/70374993-e8bda780-18d7-11ea-861b-df74921bbaf3.png)

So delete the project and try again making sure you have the same result as on the screenshots...

After if no success, check if the files from the extracted zip are the same as the files on the project folder. If not manually overwrite them.

**Comment by oldnavyshel** [comment]
Its saying a warning on the config.XML. 
![Screenshot (6)](https://user-images.githubusercontent.com/58614227/70376336-9f685a80-18cd-11ea-8db7-ba1db8361a23.png)

**Comment by fgl27** [comment]
What warning? I don't see a thing... BTW don't open files like that on Tizen, as they may get corrupted.

You not supposed to overwrite a file content (by open the file and changing it's content), but yes by overwrite the file it self (copy the files don't change they content), close those file you open on tizen, close tizen and overwrite the file if they aren't be copy correct when you create the project and import the file system, then reopen tizen and try again...

Again just redo as I ask delete the project create a new one from start, if the app fails to install check if the files are be imported if not overwrite they.

**Comment by oldnavyshel** [comment]
I followed your instructions and this was the result
![Screenshot (9)](https://user-images.githubusercontent.com/58614227/70376681-31259700-18d1-11ea-844a-2c56d6f62729.png)

**Comment by fgl27** [comment]
You are doing something wrong, because that  isn't the correct config file.

**Comment by fgl27** [comment]
correct file screenshot

![Screenshot from 2019-12-07 14-19-51](https://user-images.githubusercontent.com/13755892/70378225-b96d6180-18fc-11ea-9499-0a3cafa138d6.png)

**Comment by oldnavyshel** [comment]
Maybe I'm downloading the wrong file. I click the link within the instructions but its still not working. Can you give me the link for the release version I'm supposed to to download?

**Comment by fgl27** [comment]
https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V4/release_4_0_1_V4.zip

is a zip need unzip before import

content 

![Screenshot from 2019-12-07 15-16-11](https://user-images.githubusercontent.com/13755892/70378877-89c25780-1904-11ea-9479-d50b39706f5d.png)

**Comment by oldnavyshel** [comment]
This is how it looks before I even import the files.
![Screenshot (11)](https://user-images.githubusercontent.com/58614227/70379231-c20b6b00-18ef-11ea-9b9c-e630da6e6499.png)

**Comment by oldnavyshel** [comment]
And by the way, this is what my application template page looks like.
![Screenshot (13)](https://user-images.githubusercontent.com/58614227/70379348-14995700-18f1-11ea-877f-55c604cf06bd.png)

**Comment by fgl27** [comment]
Did you understand that there is several steps after this

![image](https://user-images.githubusercontent.com/13755892/70380137-47eddd00-1915-11ea-933d-d53150b99a5e.png)


fallow all of this steps
https://github.com/fgl27/smarttv-twitch#setup-the-application

iclud

- Wait for it to load
- Back on Tizen Studio, left click on the folder symbol with AnyName-X.0 on the left corner under project explorer, just to select the folder (AnyName-X.0 is the default name given when you created a project in the last step; if you used a different name, click on that)
- Top menu > File > Import > General > File System ... next > Browse.. to find the extracted folder from the release_X_X_X.zip ... > click Select All, mark Overwrite existing ... > Finish
- Wait for it to load
- The name of the folder AnyName-X.0 changes to AnyName-tv-samsung-X.0

![image](https://user-images.githubusercontent.com/13755892/70380145-68b63280-1915-11ea-8524-707600f7b380.png)

![image](https://user-images.githubusercontent.com/13755892/70380147-6e137d00-1915-11ea-98fd-595667d66bdd.png)

![image](https://user-images.githubusercontent.com/13755892/70380148-75d32180-1915-11ea-9400-05b65c25e17a.png)


![image](https://user-images.githubusercontent.com/13755892/70380149-7966a880-1915-11ea-8f54-97849e9cc32a.png)


If you don't import the file sistem yours config.xml will never work.

just read the tutorial carefully and fallow it of the steps of the screenshots.

**Comment by oldnavyshel** [comment]
I did import. Those are the results after importing the file system.

**Comment by fgl27** [comment]
then if you are sure you did it didn't work, close Tizen and do it manually copy all the files from the extracted zip to the folder of the project. reopen tizen must work then.

**Comment by oldnavyshel** [comment]
Okay this is as far as I've gotten now.
![Screenshot (14)](https://user-images.githubusercontent.com/58614227/70380900-f2f79a00-1907-11ea-934f-14d11173a00c.png)

**Comment by oldnavyshel** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/58614227/70380952-8af58380-1908-11ea-96bc-0b9021c6b2fb.png)

**Comment by fgl27** [comment]
Don't know
