### ISSUE TITLE
Problem ocured while try to run

### ISSUE THREAD

**Issue by Aintheone** [fgl27/smarttv-twitch#9]
I just made all the steps...

But when i try to run, i get this error:

An internal error occurred during: "Launching tsundi".
org.tizen.web.editor.configuration.TizenConfiguratorImpl cannot be cast to org.tizen.web.editor.configuration.IMobileConfigurator

Can anyone pls help? :)

Thanks for ur time :)

**Comment by Aintheone** [comment]
I solved it myself thx

**Comment by jopedic** [comment]
I have the same problem.
How did you resolved the issue?

**Comment by lukedelapoer** [comment]
> I solved it myself thx

Sorry can you tell me how did you solve it? Thanks.

**Comment by megalhaes** [comment]
I've also encountered this problem. Any solution?

**Comment by Aintheone** [comment]
Sorry, i was in a hurry that time, so don't expalin it. But now i tell.

In the guide u see tv 4.0
But if u downloaded the tizen studio newest version there is TV - 5.0

U need install it too.
After that, u will find the missing extensions. (Wich should be under 4.0 according to the guide.)
Install them, and it 'll work fine.

**Comment by megalhaes** [comment]
> 
> 
> Sorry, i was in a hurry that time, so don't expalin it. But now i tell.
> 
> In the guide u see tv 4.0
> But if u downloaded the tizen studio newest version there is TV - 5.0
> 
> U need install it too.
> After that, u will find the missing extensions. (Wich should be under 4.0 according to the guide.)
> Install them, and it 'll work fine.

Thank you for the reply. Unfortunately I had already installed TV 5.0 so I'm facing a different issue.

**Comment by Aintheone** [comment]
What kind of error ? :)
