### ISSUE TITLE
Writing Into Twitch Chat from App

### ISSUE THREAD

**Issue by C0ACH123** [fgl27/smarttv-twitch#90]
I would like to request a feature to be able to contribute to the twitch chat.

I appreciate all of the features regarding the chat window. However, I still have to log-in to my twitch on the computer or phone to write into the chat. This would complete the chat functionality, I believe.

**Comment by fgl27** [comment]
This is not the simples feature to make not if you wanna it done in the proper way, as you wrote it can be achieved so easy on a mobile device so I never bother to do.

My idea is to make a new keyboard, as the onscreen one is unreliable ad incomplete.

This new keyboard must contain two main section that the user can show and hide on a key click , one section is the main keyboard all letter numbers and some etc keys, the keyboard must be in a small and half transparent UI this way it doesn't take much space and can show the stream on the background, the other section is a emoji keyboard, that must support all streamer emoji + BetterTTV, FrankerFaceZ and Twemoji emotes support.

But all of that is very boring to make and very time consuming, as I don't have enough free time or wanna to work at this time with something boring, I don't do it.

Technically I don't see me doing this is the span of the next year or so as life is too busy and I need to focus on life.

As this is a open source app and this feature can be implemented and tested on a normal computer browser is technically possible for anyone to do it, no need for any fancy Tizen knowledge just basic html/css/js + twitch api workflow with is [documented by twitch](knowledge), so I leave this open and maybe someone can do it.

**Comment by fgl27** [comment]
I made this for the android version of this app, probably release this month on android and next month on the samsung version

![Screenshot from 2020-04-18 01-42-44](https://user-images.githubusercontent.com/13755892/79628270-f7358e80-8115-11ea-8fd2-38570a67487a.png)

**Comment by eze92** [comment]
hi, it's possible yet to add this function ?

**Comment by fgl27** [comment]
No I don't have time maybe next year,
THe implementation is done and working but only on the android version of the app.
Next year I will try to port all possible the android features to samsung.

**Comment by eze92** [comment]
ok, I hope you can add these changes I saw a little and they are quite a few. Your work is appreciated since twitch refuses to make an official app

**Comment by fgl27** [comment]
Is a open source app, but in the past 5+ years I'm the only one working on adding anything to the app, I guess I just motivated to the the same as everybody else with is noting.

**Comment by fgl27** [comment]
The feature was added, update the app to take effect.

To update hold return key until the app closes then open it again.
