### ISSUE TITLE
I can't play live videos

### ISSUE THREAD

**Issue by lukaz914** [fgl27/smarttv-twitch#91]
First of all thank you for dedicating yourself to this project.

I have the following problem: I can't watch any live video. 
1) I open the app;
2) I put any live video to play;
3) The video does not load, thus being in the loading screen.

Attempts made:
1) Unplugged the television;
2) I put in all the qualities of video;
3) I changed the video buffer

I followed the installation smoothly and can browse the entire application and even watch clips and vods as normal. I also added my twitch account as well as the authentication key without problems.

Did I forget to take any steps or is it a problem with my television?

**Comment by fgl27** [comment]
I assume you aren't using the correct app version as is all fine here...

What is the app version?
in about, plus the full TV information... Tizen TV and FW?

mus be exactly this if not you are on a wrong version

![Frame001_w1920h1080](https://user-images.githubusercontent.com/13755892/71092501-1a5f2a00-2186-11ea-974a-7d23e2766a6b.png)


proper version link
https://github.com/fgl27/smarttv-twitch/releases/download/4.0.1_V4/release_4_0_1_V4.zip

**Comment by lukaz914** [comment]
Here is the information:

![image](https://user-images.githubusercontent.com/59019746/71093362-ce14e980-2187-11ea-904a-313f07422891.png)

**Comment by fgl27** [comment]
The version is OK, don't know why it fails.

Does it fails for VOD? for Clips?

This issue you will need to do a full log so I can see.
On the Bug report: template you can see how to debug. install as is wrote there this link https://github.com/fgl27/smarttv-twitch/issues/5#issuecomment-466170992

and share the log result when you play a few live, vods and clips.

**Comment by lukaz914** [comment]
Vods and Clips are ok.

I will try to do this as soon as possible and post.

**Comment by lukaz914** [comment]
Log:

`Main_Checktylesheet Main.js:904

Main_Checktylesheet loaded OK Main.js:916

Main_IsNotBrowser tizen = true Main.js:155

language is pt Main.js:188

TVKeyValue_regKey started Main.js:212

[productinfo.js] getFirmware  begin webapis.min.js:2

[productinfo.js] getFirmware  end [object Object] webapis.min.js:2

[productinfo.js] getFirmware message data T-HKM6UABC-1530.0 webapis.min.js:2

[productinfo.js] getModel  begin webapis.min.js:2

[productinfo.js] getModel  end [object Object] webapis.min.js:2

[productinfo.js] getModel message data UJU6100 webapis.min.js:2

App version: 121619 Main.js:703

Tizen Version: 2.3 | TV: UJU6100 | FW: T-HKM6UABC-1530.0 Main.js:719

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1

GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
`

**Comment by lukaz914** [comment]
Full log [B(green) --> stream --> vod --> clip]:


> Main_Checktylesheet Main.js:904
> Main_Checktylesheet loaded OK Main.js:916
> Main_IsNotBrowser tizen = true Main.js:155
> language is pt Main.js:188
> TVKeyValue_regKey started Main.js:212
> [productinfo.js] getFirmware  begin webapis.min.js:2
> [productinfo.js] getFirmware  end [object Object] webapis.min.js:2
> [productinfo.js] getFirmware message data T-HKM6UABC-1530.0 webapis.min.js:2
> [productinfo.js] getModel  begin webapis.min.js:2
> [productinfo.js] getModel  end [object Object] webapis.min.js:2
> [productinfo.js] getModel message data UJU6100 webapis.min.js:2
> App version: 121619 Main.js:703
> Tizen Version: 2.3 | TV: UJU6100 | FW: T-HKM6UABC-1530.0 Main.js:719
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> Play_onPlayer: 
> 
> "https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CpUD-7nboEf1Fpqly30uIY0Zp1Lw0broFwd94O5gOEfkvX8fzize3TpENYYdriuV_RDWy8nGSzSrL1mHwODZpFAbmO60yzo89wzc8sizfleRWGWhchNCWucIfNRCG2Rmb7lITwlr-YI5ar6HEwwnArNfqGkRh9JNVaRcVOsRMvilZJRG98DyJ1Xus0jFCyO4pVoL6LjUZBUyiLyIG18zuO4yn__mfCQ9p9dVP330RImnKoA7Gla8-I1XPFPARE-6XHH_Brf7sn9R8OMcXrkp6YWWYHlKzSewD3vomuwZoeG1G9zcDZy9I2HMUhfIAXYhcgnjW0xmYR7-y9RD9zh6U5mXOq3uj5sA8lofOTiuYNCs3QpDVDiK329z7lRq75UAMV7mmMtPm9NCTdA33UMnQKnxFaXU3KW9oA5joH03LIp7FNWzgNKvLZY12qpSudAGg6wJ0WLElteg0IG7yVZvkmwByE25YFqgHcq2irOY9itD3UOG0g5S2MW2hEO2h5GNdjwj4k5OWLjnfXUzHm-03VJtgR7YZpFfEhAWQoEnHmR5HDmMWlCXZ0JzGgxpqeSsaVSIWa2bKPY.m3u8"
>  Play.js:890
> Play_onPlayer: date: Wed Dec 18 2019 12:15:49 GMT-0300 (BRT) Play.js:966
> Play_onPlayer: 
> 
> "https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CpUD-7nboEf1Fpqly30uIY0Zp1Lw0broFwd94O5gOEfkvX8fzize3TpENYYdriuV_RDWy8nGSzSrL1mHwODZpFAbmO60yzo89wzc8sizfleRWGWhchNCWucIfNRCG2Rmb7lITwlr-YI5ar6HEwwnArNfqGkRh9JNVaRcVOsRMvilZJRG98DyJ1Xus0jFCyO4pVoL6LjUZBUyiLyIG18zuO4yn__mfCQ9p9dVP330RImnKoA7Gla8-I1XPFPARE-6XHH_Brf7sn9R8OMcXrkp6YWWYHlKzSewD3vomuwZoeG1G9zcDZy9I2HMUhfIAXYhcgnjW0xmYR7-y9RD9zh6U5mXOq3uj5sA8lofOTiuYNCs3QpDVDiK329z7lRq75UAMV7mmMtPm9NCTdA33UMnQKnxFaXU3KW9oA5joH03LIp7FNWzgNKvLZY12qpSudAGg6wJ0WLElteg0IG7yVZvkmwByE25YFqgHcq2irOY9itD3UOG0g5S2MW2hEO2h5GNdjwj4k5OWLjnfXUzHm-03VJtgR7YZpFfEhAWQoEnHmR5HDmMWlCXZ0JzGgxpqeSsaVSIWa2bKPY.m3u8"
>  Play.js:967
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/2546740c961b2bdf55ee_stray228_292435585_18326983/storyboards/520105640-strip-0.jpg". Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/af7ae78b9eb90bb10941_dota2mc_ru_317729009_19908071/storyboards/522536437-strip-0.jpg". Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/d77a9ad8aea07f6347fe_stray228_296612161_18588057/storyboards/520532657-strip-0.jpg". Screens.js:641
> GET https://vod-storyboards.twitch.tv/b47f657e7b212ae056b4_ybicanoooobov_297350993_18634234/storyboards/520579029-strip-0.jpg 403 (Forbidden) Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/ea3afc078cddc3ecf473_stray228_315485185_19767806/storyboards/522331125-strip-0.jpg". Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/4c6022dac08009757982_stray228_312621873_19588790/storyboards/521999707-strip-0.jpg". Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/99a22919a4b1118961bb_oneesportsgg_a_317719329_19907466/storyboards/522532706-strip-0.jpg". Screens.js:641
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/fac72b4eefbe91ec9c83_stray228_300769809_18847957/storyboards/520947147-strip-0.jpg". ScreensObj.js:167
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://vod-storyboards.twitch.tv/18ea31d55078bf567e46_oneesportsgg_36432774432_1345769903/storyboards/522526789-strip-0.jpg". Screens.js:641
> GET https://api.twitch.tv/api/vods/522526789/access_token?platform=_ 410 (Gone) [native code]:1
> Play_410ERROR true PlayVod.js:333
> PlayVod_onPlayer: date: Wed Dec 18 2019 12:16:44 GMT-0300 (BRT) PlayVod.js:534
> PlayVod_onPlayer: 
> 
> "https://vod-secure.twitch.tv/18ea31d55078bf567e46_oneesportsgg_36432774432_1345769903/chunked/index-dvr.m3u8"
>  PlayVod.js:535
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.betterttv.net/2/channels/oneesportsgg 404 (Not Found) [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/oneesportsgg SSL handshake failed [native code]:1
> onbufferingstart: date: Wed Dec 18 2019 12:16:48 GMT-0300 (BRT) PlayVod.js:487
> Play_avplay.prepareAsync Vod OK: date: Wed Dec 18 2019 12:16:48 GMT-0300 (BRT) PlayVod.js:562
> onbufferingprogress > 98: date: Wed Dec 18 2019 12:16:50 GMT-0300 (BRT) PlayVod.js:514
> onbufferingcomplete: date: Wed Dec 18 2019 12:16:50 GMT-0300 (BRT) PlayVod.js:497
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/vod-520751121-offset-32944-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/314479857-offset-8574-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/301941601-offset-26996-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/36439577616-offset-31088-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/322227777-offset-1824-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/321946353-offset-24164-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/317719329-offset-29492-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/321928737-offset-7876-preview-480x272.jpg". Screens.js:250
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/36402210576-offset-25276-preview-480x272.jpg". Screens.js:250
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> PlayClip_onPlayer: 
> 
> "https://clips-media-assets2.twitch.tv/AT-cm%7C582841473.mp4"
>  PlayClip.js:345
> PlayClip_onPlayer: date: Wed Dec 18 2019 12:17:18 GMT-0300 (BRT) PlayClip.js:356
> PlayClip_onPlayer: 
> 
> "https://clips-media-assets2.twitch.tv/AT-cm%7C582841473.mp4"
>  PlayClip.js:357
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/vod-522536437-offset-32196-preview-480x272.jpg". Screens.js:250
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/room/singsing SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> onbufferingstart: date: Wed Dec 18 2019 12:17:20 GMT-0300 (BRT) PlayClip.js:248
> Play_avplay.prepareAsync Clip OK: date: Wed Dec 18 2019 12:17:20 GMT-0300 (BRT) PlayClip.js:385
> onbufferingprogress > 98: date: Wed Dec 18 2019 12:17:24 GMT-0300 (BRT) PlayClip.js:276
> onbufferingcomplete: date: Wed Dec 18 2019 12:17:24 GMT-0300 (BRT) PlayClip.js:258
> Resource interpreted as Image but transferred with MIME type binary/octet-stream: "https://clips-media-assets2.twitch.tv/321925809-offset-8356-preview-480x272.jpg". Screens.js:250
>

**Comment by fgl27** [comment]
after this

Play_onPlayer: date: Wed Dec 18 2019 12:15:49 GMT-0300 (BRT) Play.js:966
Play_onPlayer:

"https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CpUD-7nboEf1Fpqly30uIY0Zp1Lw0broFwd94O5gOEfkvX8fzize3TpENYYdriuV_RDWy8nGSzSrL1mHwODZpFAbmO60yzo89wzc8sizfleRWGWhchNCWucIfNRCG2Rmb7lITwlr-YI5ar6HEwwnArNfqGkRh9JNVaRcVOsRMvilZJRG98DyJ1Xus0jFCyO4pVoL6LjUZBUyiLyIG18zuO4yn__mfCQ9p9dVP330RImnKoA7Gla8-I1XPFPARE-6XHH_Brf7sn9R8OMcXrkp6YWWYHlKzSewD3vomuwZoeG1G9zcDZy9I2HMUhfIAXYhcgnjW0xmYR7-y9RD9zh6U5mXOq3uj5sA8lofOTiuYNCs3QpDVDiK329z7lRq75UAMV7mmMtPm9NCTdA33UMnQKnxFaXU3KW9oA5joH03LIp7FNWzgNKvLZY12qpSudAGg6wJ0WLElteg0IG7yVZvkmwByE25YFqgHcq2irOY9itD3UOG0g5S2MW2hEO2h5GNdjwj4k5OWLjnfXUzHm-03VJtgR7YZpFfEhAWQoEnHmR5HDmMWlCXZ0JzGgxpqeSsaVSIWa2bKPY.m3u8"
Play.js:967

is when as you wrote "The video does not load, thus being in the loading screen."

so leave it there until a log shows up leave there even if takes 2 3 minuts.

**Comment by lukaz914** [comment]
Ok.
One thing I didn't give is that chat works perfectly.

Log (1080p --> 480p):

> Main_Checktylesheet Main.js:904
> Main_Checktylesheet loaded OK Main.js:916
> Main_IsNotBrowser tizen = true Main.js:155
> language is pt Main.js:188
> TVKeyValue_regKey started Main.js:212
> [productinfo.js] getFirmware  begin webapis.min.js:2
> [productinfo.js] getFirmware  end [object Object] webapis.min.js:2
> [productinfo.js] getFirmware message data T-HKM6UABC-1530.0 webapis.min.js:2
> [productinfo.js] getModel  begin webapis.min.js:2
> [productinfo.js] getModel  end [object Object] webapis.min.js:2
> [productinfo.js] getModel message data UJU6100 webapis.min.js:2
> App version: 121619 Main.js:703
> Tizen Version: 2.3 | TV: UJU6100 | FW: T-HKM6UABC-1530.0 Main.js:719
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> GET https://api.frankerfacez.com/v1/set/global SSL handshake failed [native code]:1
> Play_onPlayer: 
> 
> "https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CqAD4EU2003EyhyQhwCV3vICQ0fhkZv6cUe8JStp-ejICznMzSBRP45fnk3mrMU6oR2CYEXf6drVR9DK8T-dBDqbfQWVjD8MRUIUuYNAErx48RsQc2oJZk3mLkFMFjv3qMs4F6Pbqp7OpyM0e3EKXR4SCRYPKs-XqUYB7eYeZdBh9n8rXvgffmd8r6dM532TXi3IM_XYUH2CCkTvZX6OSgNXY15q7f23rq2YDqyNH5JDujWtSDfK3nBBFhxP8wmSXY-reWzi7LsZgskFUXwM9oTallPYDCpbYwIwtr_DIWqNFzRDGCI-CvuubqgWzEjW56AZOaooWyzSM57hjb7b0X-v72e95pR9f6zGqiFFG3a0GXthMG9i3H9Vnp38FrRKE8iNuHcKy3BbMvvg70rvvSg8UIkq2kCQhlG7fU-yAUI7p7u756O2MxPew8A7p916dkGQN3iBWYiztXmkemK1-ZI308e0DGyg8S9C8aRshZFgOlg2RIjVh6VXOcsHW3di-xIZRHP2oPHpe9-py3sTBkgP2GgK2to0Fn2the1wL3YZSUsSEJEnDYcTBAjsbpHeGcrvOLEaDK5ApO4LtJT5ASwUdA.m3u8"
>  Play.js:890
> Play_onPlayer: date: Wed Dec 18 2019 12:36:49 GMT-0300 (BRT) Play.js:966
> Play_onPlayer: 
> 
> "https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/CqAD4EU2003EyhyQhwCV3vICQ0fhkZv6cUe8JStp-ejICznMzSBRP45fnk3mrMU6oR2CYEXf6drVR9DK8T-dBDqbfQWVjD8MRUIUuYNAErx48RsQc2oJZk3mLkFMFjv3qMs4F6Pbqp7OpyM0e3EKXR4SCRYPKs-XqUYB7eYeZdBh9n8rXvgffmd8r6dM532TXi3IM_XYUH2CCkTvZX6OSgNXY15q7f23rq2YDqyNH5JDujWtSDfK3nBBFhxP8wmSXY-reWzi7LsZgskFUXwM9oTallPYDCpbYwIwtr_DIWqNFzRDGCI-CvuubqgWzEjW56AZOaooWyzSM57hjb7b0X-v72e95pR9f6zGqiFFG3a0GXthMG9i3H9Vnp38FrRKE8iNuHcKy3BbMvvg70rvvSg8UIkq2kCQhlG7fU-yAUI7p7u756O2MxPew8A7p916dkGQN3iBWYiztXmkemK1-ZI308e0DGyg8S9C8aRshZFgOlg2RIjVh6VXOcsHW3di-xIZRHP2oPHpe9-py3sTBkgP2GgK2to0Fn2the1wL3YZSUsSEJEnDYcTBAjsbpHeGcrvOLEaDK5ApO4LtJT5ASwUdA.m3u8"
>  Play.js:967
> onerror: date: Wed Dec 18 2019 12:38:23 GMT-0300 (BRT) eventType: PLAYER_ERROR_INVALID_OPERATION Play.js:942
> Play_onPlayer: date: Wed Dec 18 2019 12:40:02 GMT-0300 (BRT) Play.js:966
> Play_onPlayer: 
> 
> "https://video-weaver.sao01.hls.ttvnw.net/v1/playlist/Cp4DbBdfCBuNxw5EjEdxEHEJeSqVOrTcewUd89Ro9akMyHY9-rZPSm2ttnT3OdGc7M-UbGJupbX4oA7lYCNA0El_JSEtGYYb7XX25QhGk78n6NffYActps0RbGkIHksnzABhsmh8ELYDFT1Px1fnWLKj9GSHv0CiKUjFTDcEJw3eJ82QpZwRgJe5xOA73SyZOzPTqmFxGcpvsobAijtz-zFaobgo6_r5X8aWGryR47n2gOwen1rkfxzYu1pvPGy2CWpaIEU7gfDfYU0EPZWEiSeePmvu17zWnnxzOiGLKVIzai8CQIsd3c9ZPqE2Xaq_d0UYshEC3SVDZjWu8GHeK6mpzMK5l62x3puDQZXhc2cX6hJMGZRuTmbfxfdx4dbhKjiwbx2m529w3kGZ9E_y9z10AKgpbGqR_tklq478G6JpcSGB5YygB1Ez8RMvHeflirrwLNzn-0THa6jFLA6tJNbzgE2WfRE9C-BpFglRypFPlw2MOnT7tt7MV6RDNh1qRbgxv27XTEuefNqyPCw6cMd_eWwGJDmgacLS70WIAiO9EhAbsQF__ANzpBrkACwTsMrGGgx3TES0dP4BVmmKiHI.m3u8"
>  Play.js:967
> onerror: date: Wed Dec 18 2019 12:41:37 GMT-0300 (BRT) eventType: PLAYER_ERROR_INVALID_OPERATION Play.js:942
>

**Comment by fgl27** [comment]
last tie this happened was this the solution
https://github.com/fgl27/smarttv-twitch/issues/15#issuecomment-524453029

**Comment by lukaz914** [comment]
> last time this happened was this the solution
> [#15 (comment)](https://github.com/fgl27/smarttv-twitch/issues/15#issuecomment-524453029)
> 
> that error is too generic to know what is exactly.

Ok, I will try it now.

**Comment by lukaz914** [comment]
Google DNS - no sucess
Open DNS - no sucess
Cloudflare DNS - no sucess

**Comment by fgl27** [comment]
Did you ever used the app successfully on that TV? For live content.

**Comment by lukaz914** [comment]
> Did you ever used the app successfully on that TV? For live content.

I learned about your app earlier today, in no time I could make live videos work on my television, unfortunately.

**Comment by fgl27** [comment]
OK. This seems related to

![image](https://user-images.githubusercontent.com/13755892/71120793-e3a40680-21bb-11ea-8d9a-237fdb6d9e40.png)

Samsung warn about the missing support for 2015 and older TVs, as yours is running Tizen 2.3 I assume that is the case a old 2015 TV.

In the past we had another issue like this https://github.com/fgl27/smarttv-twitch/issues/10

As you can see in that old issue users manage to help and find a solution with is be used till today, but for some reason doesn't work on yours TV, maybe just doesn't work on yours TV, maybe was a FW update fully removing the featuring...

Samsung is know to do that kind of thing, after all if one can play VOD why not a Live is basically the same process is the same codec and etc related to the video format minor differences on how the stream is played and parsed, but if it can parse a VOD it can a Live.

Maybe there is a solution but I can't think on one also can't work on a solution as I don't have a defective device.

**Comment by lukaz914** [comment]
I understand. This is not the first time I have had problems with samsung and surely this is not the last haha.

I am available to perform tests on my television if you wish. My email is enabled to receive notifications from github.

Thanks for the support and the quick answers!

**Comment by jodafi** [comment]
Hi i have the same issue with 2 off my samsung (model 2018) it have work fin for a long time, but now they are slow to load, some time the wont play live..

**Comment by jodafi** [comment]
Could it be a router error? i have replaced my Nighthawk with a newer... But im not sure if it startede after that.

**Comment by jodafi** [comment]
i have just tested.. If i click more than ones I have a better chance for the stream or video will start??

**Comment by fgl27** [comment]
@jodafi you don't have the same issue, this is a 2015 or older issue only, that cause any live stream not to play.

There is not relation to slow to start or anything that is probably related to a bad internet, check yours local network or with yours internet provider, try a cable if you are on wifi to see what happens.

**Comment by fsalata** [comment]
I have the same issue on a Q80T (2020) I've just bought.
I have a 50KU6000 in bedroom and it works perfectly.

**Comment by fgl27** [comment]
TV issue... can you udebug @fsalata ?

Here is the how to debug .....

Install the app in debug mode... with is a similar process as you did in here https://github.com/fgl27/smarttv-twitch#install-the-application ... but now you click on "Debug as" see on the below image

![image](https://user-images.githubusercontent.com/13755892/112761920-e05d1480-8fd3-11eb-809e-217c6d2c89c0.png)


When it finishes installing will open on the computer a window from the default browser click on the console tab as on bellow image

![image](https://user-images.githubusercontent.com/13755892/112762033-287c3700-8fd4-11eb-8cbe-bd484b4d79b2.png)

Then try to play Live, VOD and clip, make sure after it start of the playback you let the player open for at least 60 seconds if it doesn't auto close...

**Comment by fsalata** [comment]
Debug shows nothing, only a blank screen.
I've tried to play online channels, VODs and clips, and every time it shows the "channel is offline" message

**Comment by fgl27** [comment]
Connection issue, have you tried to used Google DNS, in the past that was a fix..

8.8.8.8
8.8.4.4

Are goggles DNS

**Comment by fsalata** [comment]
I'm using 1.1.1.1 on both TVs.

**Comment by fsalata** [comment]
I've just added my twitch user and it loads my subscriptions. The problem seems to be only playing videos...

**Comment by fsalata** [comment]
I can't add my twitch key code. I receive a validation error message but the code is correct.

**Comment by fgl27** [comment]
1.1.1.1 may be the issue, as I where DNS is a know issue for some TV

**Comment by fsalata** [comment]
I've tried changing to 8.8.8.8 with no success...

**Comment by fgl27** [comment]
OK is just like the user that open the issue.

I can't do a thing as all my TV just work, as yours that works, I have no idea what different is on device that don't work.

The only thing we can guess is that some twitch request just don't work do to a connection issue, and here is no replacement.

**Comment by fsalata** [comment]
Ok.
I've found the "problem". I've download the release and the master branch source code and I've messed up and installed the "test only" version.
Installed the release version and now all works fine.
Sorry and thank you for the help.

**Comment by fgl27** [comment]
Don't worry, I assume you used the same project on both TV so didn't botter checking that.

But yes the about screen will let you know if you install the wrong zip, and the wrong will have all of those issues.

:+1:

**Comment by fgl27** [comment]
inform to reopen if any news
