### ISSUE TITLE
Failed to connect to the TV

### ISSUE THREAD

**Issue by dobrelaurentiu** [fgl27/smarttv-twitch#92]
Hello, 
I am trying to install your app and I'm at the point where it needs to connect to the TV but I cannot manage to do it. I followed the account steps and everything looks alright, in my opinion. But still, I get the following error:
![image](https://user-images.githubusercontent.com/21999697/71646828-c449c500-2cf5-11ea-91f4-782817285f32.png)
What am I missing ?

**Comment by fgl27** [comment]
have you read all the info on
[Setting up the build environment](https://github.com/fgl27/smarttv-twitch#setting-up-the-build-environment)

???

last line

> If you have a problem on connecting refer back to [Account and Downloads](https://github.com/fgl27/smarttv-twitch#account-and-downloads), without properly enabling developer mode on the TV this will fail.

maybe that

**Comment by dobrelaurentiu** [comment]
Yes, I read all the info and followed all the steps. The problem was that I entered the wrong IP. I used one of those random websites that show you IP address and it seems that it was wrong. I entered the correct one and the app is installed now and it seems to be working properly. 
Thanks a lot !

**Comment by fgl27** [comment]
Yes I can improve the readme on that, you used the yours IP see by the internet side, but you need the local IP that yours local router (probably yours wifi router or related) asings to yours local computer...

I guess I can add info on a cmd line that shows the IP of the computer to use.
