### ISSUE TITLE
App no longer opening

### ISSUE THREAD

**Issue by ryanrohypnol** [fgl27/smarttv-twitch#93]
I’ve been using your version of Twitch for over a year now. It’s absolutely incredible, I turned on my Samsung and the app doesn’t load, nor gives any type of error message. I’ve tried resetting it and closing all apps. Any suggestions?

**Comment by fgl27** [comment]
What "resetting it" mean for you?

The app is fine here. Try a reinstall from computer see if fixes.

**Comment by ryanrohypnol** [comment]
Unplugging, and plugging it back in. I will try to reinstall.

Thank you, I will update in this thread later.

**Comment by AtomicStryker** [comment]
Experiencing a similar issue - yesterday the app worked fine (and had for a long time), today i hit it in the source selection menu and nothing happens. I get the "accepted" sound but nothing else, i remain in the source selection menu.

I will try reinstalling the app - but is there anything else to be done, some kind of logfile to get?

**Comment by AtomicStryker** [comment]
OK very strange effect - when navigating to the APPS app and then selecting smarttv-twitch, it opens. But when i then retry the "quickbar" icon it does not work.

**Comment by fgl27** [comment]
Remove from quick and add back?

Seems a TV issue as only you ever had it.

**Comment by AtomicStryker** [comment]
Removing from quick and re-adding didn't help. I uninstalled it using APPS and tried to re-connect my old tizen workspace, connecting to the TV failed. Now when i try to open APPS its a blackscreen. 💃

**Comment by AtomicStryker** [comment]
Alright! I've used the "Smart Hub reset" in the advanced settings to recover APPS, logged back into the dev acc, connected it to the PC, got the dumb eclipse backend of Tizen to refresh by massive amounts of force, re-installed the app, and now the quickbutton works again.

**Comment by fgl27** [comment]
OK... TV was going bananas for some reason...odd behavior like that is not expected but happens.

**Comment by ryanrohypnol** [comment]
I kept it unplugged for 60 seconds, and it magically started working again. Odd!

**Comment by BaiMaoLi** [comment]
> Remove from quick and add back?
> 
> Seems a TV issue as only you ever had it.

I have also issue.

**Comment by fgl27** [comment]
> > Remove from quick and add back?
> > Seems a TV issue as only you ever had it.
> 
> I have also issue.

This is a closed resolve issue, if you have one open a new one and properly describe it.
