### ISSUE TITLE
Amend installation instructions - file import insufficient

### ISSUE THREAD

**Issue by AtomicStryker** [fgl27/smarttv-twitch#94]
Your (very nice) installation instructions have a hitch in the part where you import the release file contents into the user created app structure.

As your own screenshot states, the import does not include the subfolder "app" and critically, the images/app_icon.png deeper inside.

Eclipse/Tizen then fails when attempting to start the app, as it correctly detects that the app icon path points to an invalid file. This can be fixed by manually copying over the "app" folder.

Perhaps you could change the installation instructions like so:

Right-click the project folder, select "Show In" and "System Explorer". Then open the project folder and copy-paste the release zipfile contents in here. You should get "overwrite" warnings if done correctly.

**Comment by fgl27** [comment]
Even the screenshot not showing the app folder be imported it is

![Screenshot from 2020-01-08 17-25-32](https://user-images.githubusercontent.com/13755892/72013059-e97d8c80-323b-11ea-8db5-ec38d55025f5.png)

I fallow my own instruction and that is how I know the work and my SS are fine.

I guess you have a permission or related fle issue.

The correct fix is then MOD the release so the image is in the root with all other files

**Comment by AtomicStryker** [comment]
I suspect a difference - i toggled all the checkboxes in the right screen by hand. This does not include "app", as it is probably hidden in a submenu on the left screen.
