### ISSUE TITLE
Viewer count sorting problem

### ISSUE THREAD

**Issue by missiah** [fgl27/smarttv-twitch#96]
**Describe the bug**
Since today the sorting of channel viewers is broken
it doesn't go any more from maximum viewers to the lowest viewers

**To Reproduce**
1. Go to 'User Menu'
2. Click on 'Live'

**Expected behavior**
Before this bug I was able to have my followed channels with the most viewers on top and the lowest viewers at the bottom

**Screenshots**
https://imgur.com/a/G0T7NUP

**Device:**
 - TV Model: UK6300
 - Os version: Tizen 2.4.0

**Comment by fgl27** [comment]
Not a app issue

https://discuss.dev.twitch.tv/t/kraken-streams-followed-not-ordered-by-viewers/23772

**Comment by missiah** [comment]
Okay thank you very much for the quick response.
Let's hope Twitch Dev's will fix this asap.


Can be closed

**Comment by fgl27** [comment]
Let's give some time... I make a workaround if they don't fix it.
