### ISSUE TITLE
Unable to install Newest version

### ISSUE THREAD

**Issue by Flatline9** [fgl27/smarttv-twitch#99]
I was having major issues with the app buffering and having bad video quality so I came here and found that the app version I have is out of date.

I removed the old app from my TV

I downloaded  release_4_0_1_V4.zip
Followed the instructions and got the app easily installed onto the TV again only to find out that installed the same old APP Version: 4.0.1.011520
The new APP Version I have seen in other trouble tickets is: 4.0.1.121619

Did I download the wrong ZIP? If so can you give me a link to the new version because I can't seem to find it here.

**Comment by fgl27** [comment]
app version is a date get it?
latest is
https://github.com/fgl27/smarttv-twitch/blob/master/app/specific/Main.js#L121

**Comment by fgl27** [comment]
The app is a self update app... if I change that line and push the app update
Will show the new in about...

**Comment by Flatline9** [comment]
Okay. It looks like I have the correct version. It looks like I'm having some issues with the live streaming buffering so badly that it goes down to 360p and I have no idea what's causing the problem. All my other apps like YouTube or Netflix run 1080p or even 4k with zero buffering

**Comment by fgl27** [comment]
Twitch servers aren't from YouTube or Netflix... They all lag but separated...

Not all streams are from the same server, simple tests as open a clip or a vod or a different live and the problem is not there meaning that server is lagging for you.

**Comment by Flatline9** [comment]
Ok that is a bit frustrating. I will have to test to see if it lags on my computer vs my TV. My guess I won't run into the issue on my computer. Is there a feature to switch to a different server when you can bad lag?

**Comment by fgl27** [comment]
No. On my tests of one twitch app lags they all lag when testing the same steam at the same time.
